README.md

Related [AB#172](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/172)

AB#169 Add description + link to README

---

interfaces/HO-Portal/.prettierrc.yaml
interfaces/HO-Portal/azure-pipelines.yml
interfaces/HO-Portal/package-lock.json
interfaces/HO-Portal/package.json
interfaces/HO-Portal/tslint.json
interfaces/README.md

AB#87 Setup Azure Pipeline to test HO-Portal interface

---

interfaces/HO-Portal/azure-pipelines.yml
interfaces/HO-Portal/package.json
interfaces/HO-Portal/src/karma.conf.js

Related [AB#182](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/182)

AB#87 Tweak CI test script(s)/steps

---

services/programs-service/azure-pipelines.yml

Related [AB#87](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/87)

Tweak CI with Azure Pipelines

---

interfaces/HO-Portal/src/app/programs/programs.page.html
interfaces/HO-Portal/src/app/programs/programs.page.spec.ts
interfaces/HO-Portal/src/app/programs/programs.page.ts

+ Missing update to Unit-test, to test trigger of CI (Related [AB#87](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/87))

AB#44 Cleanup list-view to start with clean slate

---

interfaces/HO-Portal/azure-pipelines.yml
services/programs-service/azure-pipelines.yml

Related [AB#181](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/181)

AB#87 Tweak 'include' syntax for triggers

---

interfaces/HO-Portal/src/app/programs/programs.page.spec.ts
interfaces/HO-Portal/src/app/programs/programs.page.ts

Related [AB#181](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/181)

AB#87 Test to break CI

---

interfaces/HO-Portal/azure-pipelines.yml
services/programs-service/azure-pipelines.yml

Related [AB#181](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/181)
Related [AB#182](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/182)

AB#87 Limit pipelines to PRs only

---

interfaces/HO-Portal/package-lock.json
interfaces/HO-Portal/package.json
interfaces/HO-Portal/src/app/app.component.html
interfaces/HO-Portal/src/app/app.component.spec.ts
interfaces/HO-Portal/src/app/app.component.ts
interfaces/HO-Portal/src/app/app.module.ts
interfaces/HO-Portal/src/app/home/home.module.ts
interfaces/HO-Portal/src/app/home/home.page.html
interfaces/HO-Portal/src/app/home/home.page.spec.ts
interfaces/HO-Portal/src/app/programs/programs.module.ts
interfaces/HO-Portal/src/app/programs/programs.page.html
interfaces/HO-Portal/src/app/programs/programs.page.spec.ts
interfaces/HO-Portal/src/assets/i18n/en.json
interfaces/HO-Portal/src/assets/i18n/nl.json

Fixes [AB#73](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/73)

AB#87 : Make texts translatable

---

services/programs-service/package-lock.json

Reverts global-121/121-platform#48

Revert "Set/Update dependencies to current versions"

---

interfaces/HO-Portal/README.md
interfaces/HO-Portal/src/app/mocks/api.programs.mock.ts
interfaces/HO-Portal/src/app/mocks/programs.mock.ts
interfaces/HO-Portal/src/app/models/program.model.ts
interfaces/HO-Portal/src/app/programs/programs.page.spec.ts
interfaces/HO-Portal/src/app/programs/programs.page.ts
interfaces/HO-Portal/src/app/services/api.service.ts
interfaces/HO-Portal/src/app/services/jwt.service.ts
interfaces/HO-Portal/src/app/services/programs-service-api.service.ts
interfaces/HO-Portal/src/environments/environment.prod.ts
interfaces/HO-Portal/src/environments/environment.ts
interfaces/HO-Portal/tslint.json

Note: Setting the correct Authentication-header/Token data needs to happen 'by hand' in the browser/session (for now).
Fixes [AB#45](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/45)
Fixes [AB#222](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/222)

AB#44 Use API to request "all programs"

---

interfaces/HO-Portal/src/app/programs/programs.page.html

Fixes [AB#46](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/46)
Fixes [AB#54](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/54)

AB#44 Show program details in list-view

---

interfaces/HO-Portal/src/app/app-routing.module.ts
interfaces/HO-Portal/src/app/login/login.module.ts
interfaces/HO-Portal/src/app/login/login.page.html
interfaces/HO-Portal/src/app/login/login.page.spec.ts
interfaces/HO-Portal/src/app/login/login.page.ts
interfaces/HO-Portal/src/app/services/api.service.ts
interfaces/HO-Portal/src/app/services/programs-service-api.service.ts
interfaces/HO-Portal/src/assets/i18n/en.json
interfaces/HO-Portal/src/assets/i18n/nl.json
interfaces/HO-Portal/src/environments/environment.ts

Fixes [AB#223](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/223)

AB#87 Add Login-page/form/feature

---

greenkeeper.json

Pending a fix/merge of this PR: https://github.com/greenkeeperio/monorepo-definitions/pull/24

Ignore Angular-CLI updates

---

interfaces/PA-App/package-lock.json
interfaces/PA-App/package.json
interfaces/PA-App/src/app/app.component.spec.ts
interfaces/PA-App/src/app/app.component.ts
interfaces/PA-App/src/app/app.module.ts
interfaces/PA-App/src/app/tabs/tabs.module.ts
interfaces/PA-App/src/app/tabs/tabs.page.html
interfaces/PA-App/src/app/tabs/tabs.page.spec.ts
interfaces/PA-App/src/assets/i18n/en.json
interfaces/PA-App/src/assets/i18n/nl.json

Related [AB#42](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/42)

AB#42 Add (initial) i18n support to PA-App

---

interfaces/PA-App/src/app/shared/dialogue-turn/dialogue-turn.component.html
interfaces/PA-App/src/app/shared/dialogue-turn/dialogue-turn.component.scss
interfaces/PA-App/src/app/shared/dialogue-turn/dialogue-turn.component.ts

Fixes [AB#507](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/507)

AB#42 Add "moment" to dialogue-turn speech-bubbles

---

services/121-service/src/sovrin/credential/credential.controller.ts
services/121-service/src/sovrin/credential/credential.service.ts
services/121-service/src/sovrin/credential/dto/prefilled-answers.dto.ts

Changed 'sovrin/credential/attributes' to only have body instead AB#519

---

interfaces/PA-App/src/app/models/program.model.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.html
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.spec.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal-components/personal-components.module.ts
interfaces/PA-App/src/app/personal-components/select-program/select-program.component.ts
interfaces/PA-App/src/app/personal/personal.page.ts
interfaces/PA-App/src/assets/i18n/en.json

Related [AB#588](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/588)
Fixes [AB#593](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/593)

AB#372 Generate speech-bubbles per question dynamically

---

interfaces/PA-App/src/app/personal-components/select-program/select-program.component.html
interfaces/PA-App/src/app/personal-components/select-program/select-program.component.ts

Related [AB#593](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/593)

AB#372 Show program-properties in chosen Language, or default fallback

---

README.md
interfaces/PA-App/src/app/models/timeslot.model.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.html
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.html
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.ts
interfaces/PA-App/src/app/personal-components/select-program/select-program.component.html
interfaces/PA-App/src/app/services/conversation.service.ts
interfaces/PA-App/src/app/services/programs-service-api.service.ts
interfaces/PA-App/src/app/shared/dialogue-turn/dialogue-turn.component.html
interfaces/PA-App/src/app/shared/dialogue-turn/dialogue-turn.component.scss
interfaces/PA-App/src/assets/i18n/en.json

Related [AB#347](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/347)
Fixes [AB#588](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/588)

AB#42 Refactor SelectAppointment etc

---

interfaces/PA-App/src/app/personal-components/choose-credential-type/choose-credential-type.component.html
interfaces/PA-App/src/app/personal-components/create-password/create-password.component.html
interfaces/PA-App/src/app/personal-components/identity-form/identity-form.component.html
interfaces/PA-App/src/app/personal-components/initial-needs/initial-needs.component.html
interfaces/PA-App/src/app/personal-components/select-country/select-country.component.html
interfaces/PA-App/src/app/personal-components/select-language/select-language.component.html
interfaces/PA-App/src/app/personal-components/select-program/select-program.component.html

Fixes [AB#628](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/628)

AB#603 Convert use of [hidden] to Angular *ngIf

---

interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.html
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal-components/personal-component.class.ts

Fixes [AB#528](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/528)

AB#372 Make questions appear one-by-one

---

interfaces/PA-App/src/app/services/conversation.service.ts
interfaces/PA-App/src/app/shared/dialogue-turn/dialogue-turn.component.html
interfaces/PA-App/src/app/shared/dialogue-turn/dialogue-turn.component.ts

+ Fix time-formatting
Fixes [AB#600](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/600)

AB#603 Hand-over completion-time to conversation-history

---

interfaces/PA-App/src/app/personal-components/create-password/create-password.component.html
interfaces/PA-App/src/app/personal-components/create-password/create-password.component.ts

Fixes [AB#664](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/664)

AB#42 Prevent executing Sovrin-flow more then once

---

services/tykn-ssi-services/azure-pipelines.yml

Related [AB#661](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/661)

Add empty Azure Pipeline configuration

---

interfaces/PA-App/src/app/app.scss
interfaces/PA-App/src/app/personal-components/create-password/create-password.component.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal-components/identity-form/identity-form.component.ts
interfaces/PA-App/src/app/personal-components/initial-needs/initial-needs.component.ts
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.ts
interfaces/PA-App/src/app/personal-components/select-country/select-country.component.ts
interfaces/PA-App/src/app/personal-components/select-program/select-program.component.ts
interfaces/PA-App/src/app/personal/personal.page.html
interfaces/PA-App/src/app/personal/personal.page.ts
interfaces/PA-App/src/app/services/conversation.service.ts
interfaces/PA-App/src/assets/i18n/en.json
interfaces/PA-App/src/assets/i18n/nl.json

Fixes [AB#119](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/119)

Add loading-indicator(s) + cleanup fixes

---

interfaces/PA-App/src/app/personal-components/personal-component.class.ts
interfaces/PA-App/src/app/shared/dialogue-turn/dialogue-turn.component.html
interfaces/PA-App/src/app/shared/dialogue-turn/dialogue-turn.component.ts
interfaces/PA-App/src/environments/environment.prod.ts
interfaces/PA-App/src/environments/environment.ts

Fixes [AB#671](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/671)

AB#603 Add feature-switch for animations

---

interfaces/PA-App/src/app/services/programs-service-api.service.ts

Fixes [AB#680](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/680)

Update API-endpoint to request published programs only

---

interfaces/AW-App/config.xml
interfaces/AW-App/package-lock.json
interfaces/AW-App/package.json
interfaces/AW-App/src/app/scan-qr/scan-qr.page.ts
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.html
interfaces/README.md

- Enable building a native android-build
- Update format of QR-code contents
- Fix colors of QR-code to enable cordova-plugin-qrscanner to scan it
Fixes [AB#685](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/685)

AB#685 Fix QR-code scanning

---

interfaces/PA-App/src/app/personal/personal.page.ts
interfaces/PA-App/src/environments/environment.prod.ts
interfaces/PA-App/src/environments/environment.ts

Fixes [AB#684](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/684)

AB#696 Setup PA-App for MVP-test

---

services/121-service/README.md
services/121-service/src/scripts/seed-init.ts
services/121-service/src/secrets.ts.example
services/121-service/src/user/auth.middlewareAW.ts
services/121-service/src/user/auth.middlewareAdmin.ts
services/121-service/src/user/auth.middlewarePM.ts
services/121-service/src/user/dto/create-user.dto.ts
services/121-service/src/user/dto/login-user.dto.ts
services/121-service/src/user/user.controller.spec.ts
services/121-service/src/user/user.service.spec.ts
services/PA-accounts-service/README.md
services/PA-accounts-service/src/scripts/seed-init.ts

Related [AB#713](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/713)

AB#713 Use proper examples + FieldWorker=AidWorker

---

tools/README.md
tools/git-hooks/README.md
tools/git-hooks/pre-commit

Fixes [AB#728](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/728)

Add git-hook script(s) + explanations to Tools-folder

---

interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts

Fixes [AB#738](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/738)

AB#372 Show "submit answers"-button before filling the last question

---

interfaces/PA-App/src/app/personal-components/choose-credential-type/choose-credential-type.component.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.ts
interfaces/PA-App/src/app/personal/personal.page.ts
interfaces/PA-App/src/app/services/conversation.service.ts

Related [AB#596](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/596)

AB#603 Add method to ScrollDown within ConversationSections

---

interfaces/PA-App/src/app/personal-components/choose-credential-type/choose-credential-type.component.html
interfaces/PA-App/src/app/personal-components/choose-credential-type/choose-credential-type.component.spec.ts
interfaces/PA-App/src/app/personal-components/choose-credential-type/choose-credential-type.component.ts
interfaces/PA-App/src/assets/i18n/en.json

+ Simplify component logic - move into template
Fixes [AB#757](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/757)

Make submit-button only appear after choice of credential-type

---

interfaces/PA-App/src/app/personal-components/initial-needs/initial-needs.component.ts
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.html
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.ts

- Make the (fake) wait-time optional; Remove during development
- Add check for SameDay to change the syntax of appointment-dates/times

Small things

---

interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.html
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts

Fixes [AB#759](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/759)

Add input-field for AnswerType: Date

---

interfaces/PA-App/src/app/mocks/padata.service.mock.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal-components/select-program/select-program.component.ts
interfaces/PA-App/src/app/services/padata.service.ts

Fixes [AB#489](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/489)

AB#395 Store filled-in answers in paData-store(s)

---

interfaces/PA-App/src/environments/environment.prod.ts.template.js

Remove default-value as it breaks a native-build

---

interfaces/PA-App/config.xml
tools/webhook.js

Reverts global-121/121-platform#379

Revert "remove 121-indy plugin from config.xml"

---

interfaces/PA-App/package-lock.json
interfaces/PA-App/package.json

Reverts global-121/121-platform#378

Revert "removed cordova global-121-indy plugin"

---

interfaces/PA-App/config.xml
interfaces/PA-App/package-lock.json
interfaces/PA-App/package.json

Related [AB#1086](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1086)

Remove Indy SDK from PA-App dependencies

---

tools/webhook.js

Related [AB#1088](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1088)
Salvaged from #382 / #379

Include HO-Portal in post-merge deployment webhook

---

interfaces/HO-Portal/src/app/auth/auth.guard.ts
interfaces/HO-Portal/src/app/auth/auth.service.ts
interfaces/HO-Portal/src/app/login/login.page.html
interfaces/HO-Portal/src/app/login/login.page.ts
interfaces/HO-Portal/src/app/services/jwt.service.ts
interfaces/HO-Portal/src/app/services/programs-service-api.service.ts

Related [AB#1092](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1092)

Stay logged-in as long as you have a token

---

tools/121-platform-https.conf
tools/121-platform.conf

+ Fix handling of URLs used by Angular router
Fixes [AB#1087](https://dev.azure.com/global121/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1087)

Include security/performance optimisations/best-practices in server-config

---

interfaces/PA-App/src/app/personal-components/login-identity/login-identity.component.ts
interfaces/PA-App/src/app/personal/personal.page.html
interfaces/PA-App/src/app/personal/personal.page.ts
interfaces/PA-App/src/app/services/conversation.service.ts
interfaces/PA-App/src/app/services/padata.service.ts

Related [AB#388](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/388)
Related [AB#957](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/957)

AB#388 Restore conversationHistory when logging back in

---

interfaces/PA-App/src/app/services/padata.service.ts

Fixes [AB#1126](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1126)

Prevent store/retrieve of PaData without an account (in server-scenario)

---

interfaces/PA-App/src/app/personal-components/create-identity/create-identity.component.ts
interfaces/PA-App/src/app/services/ui.service.ts
interfaces/PA-App/src/app/tabs/tabs.page.html
interfaces/PA-App/src/app/tabs/tabs.page.ts

[AB#1127](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1127)

Make the User-menu toggleable from 'outside'

---

interfaces/AW-App/src/app/validation-components/main-menu/main-menu.component.ts
interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.ts

Related [AB#1090](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1090)

Fix async-syntax, reorder methods, remove unused methods

---

interfaces/PA-App/src/app/services/padata.service.ts

Related [AB#388](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/388)

AB#1127 Add UIService-call to show UserMenu initially as well

---

interfaces/AW-App/src/app/account/account.page.html
interfaces/AW-App/src/app/account/account.page.spec.ts
interfaces/AW-App/src/app/account/account.page.ts
interfaces/AW-App/src/app/app.scss
interfaces/AW-App/src/app/scan-qr/scan-qr.page.html
interfaces/AW-App/src/app/scan-qr/scan-qr.page.spec.ts
interfaces/AW-App/src/app/scan-qr/scan-qr.page.ts
interfaces/AW-App/src/app/services/session-storage.service.ts
interfaces/AW-App/src/app/validation-components/scan-qr/scan-qr.component.spec.ts
interfaces/AW-App/src/app/validation-components/scan-qr/scan-qr.component.ts
interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.spec.ts
interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.ts
interfaces/AW-App/src/app/validation/validation.page.spec.ts
interfaces/AW-App/src/assets/i18n/en.json
interfaces/PA-App/src/app/app.scss

Related [AB#1135](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1135)

AB#1090 Refactor AW-app scanning data, accounts page, test, etc

---

services/docker-compose.yml
services/tykn-ssi-services/UserIMS/userims/server.py
services/tykn-ssi-services/UserIMS/userims/service.py
services/tykn-ssi-services/tests/credentialReqResp.postman_collection.json

Delete wallet apis and some changes in create wallet api response

Delete wallet apis

---

interfaces/PA-App/src/app/services/pa-account-api.service.ts
interfaces/PA-App/src/app/services/padata.service.ts
interfaces/PA-App/src/app/services/sovrin.service.ts
interfaces/PA-App/src/app/services/user-ims-api.service.ts
interfaces/PA-App/src/app/user-menu/user-menu.component.html
interfaces/PA-App/src/app/user-menu/user-menu.component.ts
interfaces/PA-App/src/assets/i18n/en.json
services/PA-accounts-service/src/user/auth.middleware.ts
services/PA-accounts-service/src/user/user.controller.ts
services/PA-accounts-service/src/user/user.module.ts
services/PA-accounts-service/src/user/user.service.ts

Related [AB#1105](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1105)
Related [AB#1109](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1109)
Related [AB#1107](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1107)

AB#807 Add deleteUser/Account to PA-app + some error handling

---

tools/webhook.js

Related [AB#1130](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1130)

Cleanup webhook-script

---

interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.html
interfaces/HO-Portal/src/assets/i18n/en.json
interfaces/PA-App/src/app/personal-components/personal-components.module.ts
interfaces/PA-App/src/app/personal/personal.page.ts
interfaces/PA-App/src/app/user-menu/user-menu.component.html
interfaces/PA-App/src/app/user-menu/user-menu.component.ts
interfaces/PA-App/src/assets/i18n/en.json

Related [AB#807](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/807)

Various fixes+tweaks to UserMenu UI

---

interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.html
services/121-service/src/programs/program/financial-service-provider.entity.ts
services/121-service/src/sovrin/create-connection/connection.entity.ts
services/121-service/src/sovrin/create-connection/create-connection.module.ts
services/121-service/src/sovrin/create-connection/create-connection.service.ts

AB#1193 relationship connection vs fsp

---

README.md
features/README.md
features/View_funds_overview.feature
interfaces/README.md
tools/README.md

+ Add initial feature "View funds overview"

AB#993 Add documentation about testing/defining features

---

interfaces/HO-Portal/src/app/app.component.html
interfaces/HO-Portal/src/app/app.component.spec.ts
interfaces/HO-Portal/src/app/app.component.ts
interfaces/HO-Portal/src/app/auth/auth.service.ts
interfaces/HO-Portal/src/assets/i18n/en.json

Related [AB#260](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/260)

Add log-out option to HO-Portal

---

interfaces/HO-Portal/src/app/models/program-funds.model.ts
interfaces/HO-Portal/src/app/programs/program-funds/program-funds.component.spec.ts
interfaces/HO-Portal/src/app/programs/program-funds/program-funds.component.ts

Related [AB#993](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/993)

Fix test via a TestHostComponent + handle Dates as strings

---

interfaces/HO-Portal/src/app/models/program.model.ts
interfaces/HO-Portal/src/app/programs/program-details/program-details.component.html
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.html
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.spec.ts
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.ts
interfaces/HO-Portal/src/app/programs/programs.module.ts
interfaces/HO-Portal/src/app/services/programs-service-api.service.ts
interfaces/HO-Portal/src/assets/i18n/en.json

Related [AB#1211](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1211)
Related [AB#1212](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1212)
Related [AB#1225](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1225)

AB#707 Add "program-payout"-component

---

interfaces/HO-Portal/src/app/programs/program-details/program-details.component.html
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.html
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.ts
interfaces/HO-Portal/src/app/services/programs-service-api.service.ts
interfaces/HO-Portal/src/assets/i18n/en.json

Related [AB#1222](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1222)

AB#707 Add calculation of total amount in confirmation-alert 

---

interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.html
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.ts

Reverts global-121/121-platform#464

Revert "Input transfer value"

---

interfaces/HO-Portal/src/app/help/help.module.ts
interfaces/HO-Portal/src/app/home/home.module.ts
interfaces/HO-Portal/src/app/login/login.page.html
interfaces/HO-Portal/src/app/login/login.page.ts
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.html
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.spec.ts
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.ts
interfaces/HO-Portal/src/app/programs/programs.module.ts

Related [AB#707](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/707)
Related [AB#1231](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1231)
Closes #464

Make TransferValue-input editable + align forms handling via ngModels

---

features/Send_payment_instructions.feature

Related [AB#707](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/707)
Related [AB#1231](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1231)

Update test-scenario's to reuse first 2 steps + tweak wording

---

interfaces/HO-Portal/src/app/programs/program-details/program-details.component.html
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.html
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.ts

+ Fix payout-without-change scenario
Related [AB#707](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/707)

Use only transferValue inside component

---

interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.html
interfaces/HO-Portal/src/app/programs/program-payout/program-payout.component.ts
interfaces/HO-Portal/src/app/programs/program-people/program-people.component.html
interfaces/HO-Portal/src/app/programs/program-people/program-people.component.ts
interfaces/HO-Portal/src/app/shared/confirm-prompt/confirm-prompt.component.ts
interfaces/HO-Portal/src/assets/i18n/en.json

Related [AB#1303](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1303)
Related [AB#1283](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1283)

AB#1097 Improve "Are you sure?"-prompt(s)

---

tools/121-platform-https.conf

as it is more complex then 1-line-of-code :(

Remove Content-Security-Policy

---

services/121-service/examples/fsp-bank.json
services/121-service/examples/fsp-mixed-attributes.json
services/121-service/examples/fsp-mobile-money.json
services/121-service/examples/fsp-no-attributes.json
services/121-service/examples/program-anonymous1.json
services/121-service/examples/program-anonymous2.json
services/121-service/src/scripts/seed-dev.ts
services/121-service/src/scripts/seed-helper.ts
services/121-service/src/scripts/seed-mvp.ts
services/121-service/src/scripts/seed-pilot.ts
services/121-service/src/scripts/seed-publish.ts

Fixes [AB#1359](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1359)

AB#1191 Add more FSP-attributes + Update seed-scripts

---

interfaces/PA-App/src/app/personal-components/personal-component.class.ts
interfaces/PA-App/src/app/personal-components/set-notification-number/set-notification-number.component.html
interfaces/PA-App/src/app/personal-components/set-notification-number/set-notification-number.component.ts
interfaces/PA-App/src/app/services/pa-account-api.service.ts
interfaces/PA-App/src/app/services/padata.service.ts

Related [AB#1347](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1347)

AB#1306 Add check for pre-existing phone-number to cancel immediately

---

interfaces/PA-App/src/app/models/q-and-a.models.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.html
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal-components/personal-component.class.ts
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.spec.ts
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.ts
interfaces/PA-App/src/app/shared/shared.module.ts

Related [AB#1339](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1339)

AB#1191 Extract new Q-and-A-component

---

interfaces/PA-App/src/app/models/fsp.model.ts
interfaces/PA-App/src/app/models/program.model.ts
interfaces/PA-App/src/app/models/q-and-a.models.ts
interfaces/PA-App/src/app/models/translatable-string.model.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal-components/meeting-reminder/meeting-reminder.component.ts
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.ts
interfaces/PA-App/src/app/personal-components/select-fsp/select-fsp.component.html
interfaces/PA-App/src/app/personal-components/select-fsp/select-fsp.component.ts
interfaces/PA-App/src/app/personal-components/select-program/select-program.component.ts
interfaces/PA-App/src/assets/i18n/en.json

Related [AB#1228](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1228)

AB#1191 Show FSP-atributes fields + save input + refactor

---

interfaces/PA-App/src/app/personal/personal.page.html
interfaces/PA-App/src/app/personal/personal.page.ts

+ Tweak position/size of debug-buttons

Add "StartFromHistory"-button to debug-toolbar + change default init

---

interfaces/PA-App/src/app/personal-components/select-fsp/select-fsp.component.ts
interfaces/PA-App/src/app/personal-components/set-notification-number/set-notification-number.component.ts
interfaces/PA-App/src/app/services/programs-service-api.service.ts

- store in PA-accounts-service for reuse later
Related [AB#1347](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1347)
Related [AB#1306](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1306)

AB#1373 Add exception for phoneNumber

---

interfaces/PA-App/src/app/personal-components/select-fsp/select-fsp.component.html

Related [AB#1348](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1348)

AB#1306 Fix: Only show additional-questions form when there are actual questions

---

features/HO-Portal/Manage_payment_installments.feature
features/README.md

Related [AB#1310](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1310)
@jannisvisser Don't forget to rename links/titles when renaming a file. ;)

AB#1358 Fix .feature-filename/title + TOC

---

interfaces/HO-Portal/src/app/login/login.page.html
interfaces/HO-Portal/src/app/login/login.page.spec.ts
interfaces/HO-Portal/src/app/login/login.page.ts

Fix validation + ENTER-key for HO-login form

---

interfaces/HO-Portal/src/app/login/login.page.ts

Use generic reset, instead of overwriting values specifically

---

features/PA-App/Create_Digital_ID.feature
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.ts
interfaces/PA-App/src/app/personal-components/set-notification-number/set-notification-number.component.ts

Related [AB#1306](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1306)

AB#1412 Update the order of the "create digital ID"-flow

---

interfaces/PA-App/src/app/shared/phone-number-input/phone-number-input.component.html

Related [AB#1307](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1307)
Related [AB#1447](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1447)

Allow more different characters in phone-numbers

---

interfaces/PA-App/src/app/shared/phone-number-input/phone-number-input.component.html
interfaces/PA-App/src/app/shared/phone-number-input/phone-number-input.component.ts
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.ts

Related [AB#1497](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1497)

AB#1307 Fix too eager validation-checks on the server

---

interfaces/PA-App/src/app/app.module.ts
interfaces/PA-App/src/app/http-interceptors/index.ts
interfaces/PA-App/src/app/http-interceptors/retry-interceptor.ts
interfaces/PA-App/src/app/services/pa-account-api.service.ts
interfaces/PA-App/src/assets/i18n/en.json

Related [AB#1415](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1415)
Related [AB#1416](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1416)
It works for all types of requests.
Also:
Related [AB#1501](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1501)
Related [AB#1390](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1390)

Use interceptor to retry failed request when there is no connection

---

interfaces/PA-App/src/app/shared/phone-number-input/phone-number-input.component.ts
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.html

Related [AB#1390](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1390)
Related [AB#1307](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1307)

AB#1503 Fix phone number storage

---

interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.ts
interfaces/PA-App/src/assets/i18n/en.json

Related [AB#1520](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1520)
Related [AB#1519](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1519)
Related [AB#1518](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1518)

AB#1307 Make validation-message 'more connected' to input-component

---

interfaces/HO-Portal/src/app/program/phase-navigation/phase-navigation.component.html
interfaces/HO-Portal/src/app/program/phase-navigation/phase-navigation.component.scss
interfaces/HO-Portal/src/app/program/phase-navigation/phase-navigation.component.ts

Related [AB#1517](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1517)

AB#1282 Communicate active/selected state also via indicator/fill-style

---

interfaces/HO-Portal/src/app/models/program-metrics.model.ts
interfaces/HO-Portal/src/app/program/metrics/metrics.component.html
interfaces/HO-Portal/src/app/program/metrics/metrics.component.scss
interfaces/HO-Portal/src/app/program/metrics/metrics.component.spec.ts
interfaces/HO-Portal/src/app/program/metrics/metrics.component.ts
interfaces/HO-Portal/src/app/program/phase-next/phase-next.component.html
interfaces/HO-Portal/src/app/program/phase-next/phase-next.component.scss
interfaces/HO-Portal/src/app/program/program.component.html
interfaces/HO-Portal/src/app/program/program.module.ts
interfaces/HO-Portal/src/app/services/programs-service-api.service.ts
interfaces/HO-Portal/src/assets/i18n/en.json
services/121-service/src/programs/program/dto/pa-metrics.dto.ts
services/121-service/src/programs/program/dto/program-metrics.dto.ts
services/121-service/src/programs/program/program.controller.ts
services/121-service/src/programs/program/program.service.ts

Related [AB#1465](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1465)
Related [AB#1496](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1496)

AB#1405 Create/Add Metrics-component to Program page

---

interfaces/AW-App/src/app/models/program.model.ts
interfaces/AW-App/src/app/models/translatable-string.model.ts
interfaces/AW-App/src/app/services/translatable-string.service.ts
interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.ts
interfaces/HO-Portal/src/app/models/program.model.ts
interfaces/HO-Portal/src/app/models/translatable-string.model.ts
interfaces/HO-Portal/src/app/program/program-details/program-details.component.ts
interfaces/HO-Portal/src/app/program/program.component.ts
interfaces/HO-Portal/src/app/programs-list/programs-list.component.html
interfaces/HO-Portal/src/app/programs-list/programs-list.component.ts
interfaces/HO-Portal/src/app/services/programs-service-api.service.ts
interfaces/HO-Portal/src/app/services/translatable-string.service.ts
interfaces/PA-App/src/app/models/program.model.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal-components/meeting-reminder/meeting-reminder.component.ts
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.ts
interfaces/PA-App/src/app/personal-components/select-fsp/select-fsp.component.ts
interfaces/PA-App/src/app/personal-components/select-program/select-program.component.ts
interfaces/PA-App/src/app/services/translatable-string.service.ts

- to have more predictable code
- aligns all interfaces to do the same
- replaces copy-paste-code
- adds more specific Types

AB#1371 Add TranslatableStringService to all interfaces

---

interfaces/HO-Portal/src/app/mocks/api.programs.mock.ts
interfaces/HO-Portal/src/app/program/metrics/metrics.component.spec.ts
interfaces/HO-Portal/src/app/program/metrics/metrics.component.ts

AB#1548 Make metrics-list more resilient to unknown/empty data

---

interfaces/HO-Portal/src/app/program/metrics/metrics.component.html
interfaces/HO-Portal/src/app/program/metrics/metrics.component.scss
interfaces/HO-Portal/src/app/program/metrics/metrics.component.spec.ts
interfaces/HO-Portal/src/app/program/metrics/metrics.component.ts
interfaces/HO-Portal/src/app/program/program.component.html
interfaces/HO-Portal/src/assets/i18n/en.json

AB#1521 Make Metrics-component collapsable

---

interfaces/HO-Portal/src/app/program/metrics/metrics.component.scss

Fix icon styles/position

---

interfaces/HO-Portal/src/app/program/program.component.html

Fix layout issues with 2-column-grid

---

interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.ts
services/121-service/examples/fsp-mixed-attributes.json

Related [AB#1307](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1307)

AB#1522 Fix validation error flow

---

features/HO-Portal/View_metrics_overview.feature
features/README.md

Related [AB#1549](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1549)

AB#1405 Update test-scenario's for Metrics-component

---

interfaces/HO-Portal/src/app/program/phase-next/phase-next.component.ts
interfaces/HO-Portal/src/app/program/program-payout/program-payout.component.ts
interfaces/HO-Portal/src/app/program/program-people/program-people.component.ts
interfaces/HO-Portal/src/app/program/program.component.ts

Related [AB#1563](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1563)

Small tweaks to syntax / remove unused properties/variables

---

interfaces/PA-App/src/app/personal-components/create-identity/create-identity.component.html
interfaces/PA-App/src/app/personal-components/create-identity/create-identity.component.ts
interfaces/PA-App/src/app/shared/password-toggle-input/password-toggle-input.component.html
interfaces/PA-App/src/app/shared/password-toggle-input/password-toggle-input.component.ts
interfaces/PA-App/src/assets/i18n/en.json

Add password check and show feedback to user AB#1579

---

interfaces/PA-App/src/app/personal-components/create-identity/create-identity.component.html
interfaces/PA-App/src/app/personal-components/create-identity/create-identity.component.ts
interfaces/PA-App/src/app/shared/password-toggle-input/password-toggle-input.component.ts
interfaces/PA-App/src/assets/i18n/en.json

Related [AB#1279](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1279)

AB#1580 Enable enter-to-submit/proceed + simplify submit-check-logic

---

interfaces/PA-App/README.md
interfaces/PA-App/package-lock.json
interfaces/PA-App/package.json
interfaces/PA-App/src/app/shared/play-text-audio/play-text-audio.component.html
interfaces/PA-App/src/app/shared/play-text-audio/play-text-audio.component.spec.ts
interfaces/PA-App/src/app/shared/play-text-audio/play-text-audio.component.ts
interfaces/PA-App/src/app/shared/shared.module.ts
interfaces/PA-App/src/assets/i18n/en.json

Related [AB#823](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/823)

AB#1607 Add SpeakTextAudio-component to map translatable text to audio-files

---

interfaces/PA-App/src/app/personal-components/select-language/select-language.component.html
interfaces/PA-App/src/app/shared/info-popup/info-popup.component.html
interfaces/PA-App/src/app/shared/info-popup/info-popup.component.ts

Related [AB#823](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/823)

AB#1654 Enable InfoPopup to use SpeakText-components

---

interfaces/HO-Portal/src/app/program/manage-aidworkers/manage-aidworkers.component.html
interfaces/HO-Portal/src/app/program/manage-aidworkers/manage-aidworkers.component.ts
interfaces/HO-Portal/src/app/program/program.component.html

Related [AB#1626](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1626)

AB#997 Tidy up Add-aidworkers-form

---

tools/webhook.js

+ syntax-fixes for readability

Make sure the git-environment on the server is clean before 'upgrading'

---

interfaces/PA-App/src/app/services/padata.service.ts

Related [AB#1124](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1124)

AB#1672 Store username in sessionStorage only

---

interfaces/PA-App/src/app/personal-components/create-identity/create-identity.component.html
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.html
interfaces/PA-App/src/app/personal-components/login-identity/login-identity.component.html
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.html
interfaces/PA-App/src/app/personal-components/select-country/select-country.component.html
interfaces/PA-App/src/app/personal-components/select-fsp/select-fsp.component.html
interfaces/PA-App/src/app/personal-components/select-language/select-language.component.html
interfaces/PA-App/src/app/personal-components/select-program/select-program.component.html
interfaces/PA-App/src/app/personal-components/set-notification-number/set-notification-number.component.html
interfaces/PA-App/src/app/personal-components/signup-signin/signup-signin.component.html
interfaces/PA-App/src/app/shared/more-info-button/more-info-button.component.html
interfaces/PA-App/src/app/shared/play-text-audio/play-text-audio.component.html
interfaces/PA-App/src/app/shared/play-text-audio/play-text-audio.component.scss
interfaces/PA-App/src/app/shared/play-text-audio/play-text-audio.component.ts
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.html

Related [AB#823](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/823)

AB#1668 Make PlayTextAudio-button size/type configurable

---

interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.html
interfaces/PA-App/src/app/personal-components/meeting-reminder/meeting-reminder.component.html
interfaces/PA-App/src/app/personal-components/select-country/select-country.component.html
interfaces/PA-App/src/app/personal-components/select-fsp/select-fsp.component.html
interfaces/PA-App/src/app/personal-components/select-language/select-language.component.html
interfaces/PA-App/src/app/personal-components/select-language/select-language.component.ts
interfaces/PA-App/src/app/personal-components/set-notification-number/set-notification-number.component.html
interfaces/PA-App/src/app/personal-components/store-credential/store-credential.component.html
interfaces/PA-App/src/assets/i18n/en.json
interfaces/PA-App/src/assets/i18n/ny_MW.json

Related [AB#1694](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1694)

Fix bug for select-language intro + Remove need for HTML

---

interfaces/PA-App/src/app/personal/personal.page.html
interfaces/PA-App/src/app/personal/personal.page.ts

Related [AB#1152](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1152)

AB#1700 Include a language-switcher for debugging

---

features/PA-App/Listen_to_text_in_conversation-view.feature
features/README.md

Related [AB#823](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/823)

AB#1604 Add test-scenarios for "Listen to text"-feature

---

interfaces/AW-App/package-lock.json
interfaces/AW-App/package.json
interfaces/HO-Portal/package-lock.json
interfaces/HO-Portal/package.json
interfaces/PA-App/package-lock.json
interfaces/PA-App/package.json
services/121-service/package-lock.json
services/121-service/package.json
services/PA-accounts-service/package-lock.json
services/PA-accounts-service/package.json

AB#1707 Remove optional version numbers as they could be confusing

---

CHANGELOG.md
README.md
tools/webhook.js

Related [AB#1701](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1701)

AB#1640 Update README with release/deployment checklists

---

tools/webhook.js

Related [AB#1719](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1719)

Fix permissions error for outputting file in web-root

---

README.md

Related [AB#1729](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1729)
Related [AB#1733](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1733)

Improve release-checklist in README

---

tools/deploy.sh

Fix typo in build-script

---

tools/webhook.js
tools/webhook.service

Include repo-location via ENV-variable in webhook.service

---

tools/deploy.sh
tools/webhook.js

Related [AB#1708](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1708)

Enable automatic deploy of (patch-)releases via webhook on production-env

---

CHANGELOG.md
README.md

Related [AB#1767](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1767)
Related [AB#1768](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1768)

Align CHANGELOG + README regarding deployments/releases

---

CHANGELOG.md
tools/webhook.js

- Fix syntax of targetted deploy
- Make webhook-port configurable from outside

Merge back hotfix from release v0.2.1

---

CHANGELOG.md
tools/.env.example
tools/.gitignore
tools/README.md
tools/example.secrets.json
tools/webhook.js
tools/webhook.service

Set Webhook secret via Environment, not secrets.json

---

interfaces/AW-App/src/app/validation-components/download-data/download-data.component.ts

Related [AB#1475](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1475)

AB#1793 Store program-data for offline-use later

---

services/121-service/README.md
services/121-service/src/scripts/seed-dev.ts
services/121-service/src/scripts/seed-multi-program.ts
services/121-service/src/scripts/seed-pilot.ts
services/121-service/src/scripts/seed-single-program.ts

@elwinschmitz @RubenGeo see this change

remove publish from seed-scripts

---

interfaces/PA-App/src/app/personal-components/personal-components.enum.ts
interfaces/PA-App/src/app/personal-components/personal-components.module.ts
interfaces/PA-App/src/app/personal-components/preprinted-qrcode/preprinted-qrcode.component.html
interfaces/PA-App/src/app/personal-components/preprinted-qrcode/preprinted-qrcode.component.spec.ts
interfaces/PA-App/src/app/personal-components/preprinted-qrcode/preprinted-qrcode.component.ts
interfaces/PA-App/src/app/personal-components/select-appointment/select-appointment.component.ts
interfaces/PA-App/src/app/personal/personal.page.ts
interfaces/PA-App/src/app/services/programs-service-api.service.ts
interfaces/PA-App/src/assets/i18n/en.json
interfaces/README.md

Related [AB#1778](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1778)
Related [AB#1779](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1779)
Related [AB#1780](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1780)

AB#1777 preprinted-qrcode question in new component

---

features/AW-App/Download_validation_data.feature
features/PA-App/Create_Digital_ID.feature
features/PA-App/Link-preprinted-QR-code.feature
features/PA-App/Listen_to_text_in_conversation-view.feature
features/PA-App/Verify_phone_number_input.feature
features/README.md

Related [AB#1725](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1725)

AB#1833 Add "preprinted qr-code" test scenarios

---

interfaces/PA-App/src/app/personal-components/meeting-reminder/meeting-reminder.component.html
interfaces/PA-App/src/app/personal-components/meeting-reminder/meeting-reminder.component.ts
interfaces/PA-App/src/app/personal-components/preprinted-qrcode/preprinted-qrcode.component.ts
interfaces/PA-App/src/app/services/padata-types.enum.ts

Related [AB#1725](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1725)

AB#1869 Hide QR-code from Meeting-reminder when using pre-printed QR-code

---

interfaces/PA-App/src/app/shared/qr-scanner/qr-scanner.component.html
interfaces/PA-App/src/app/shared/qr-scanner/qr-scanner.component.ts
interfaces/PA-App/src/assets/i18n/en.json

Related [AB#1725](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1725)

AB#1874 QR-scanner generic error + option to "try again"

---

interfaces/AW-App/src/app/tabs/tabs.page.html
interfaces/AW-App/src/app/tabs/tabs.page.scss
interfaces/AW-App/src/theme/variables.scss
interfaces/PA-App/src/app/tab1/tab1.page.html
interfaces/PA-App/src/app/tabs/tabs.page.html
interfaces/PA-App/src/app/tabs/tabs.page.scss
interfaces/PA-App/src/theme/variables.scss

Related [AB#1834](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1834)
Related [AB#1835](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1835)

AB#1803 Align colors between AW-app and PA-app

---

interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.ts

Related [AB#1918](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1918)
Related [AB#1821](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1821)

Fix: Add did of PA

---

interfaces/AW-App/src/app/models/pa-data.model.ts
interfaces/AW-App/src/app/services/session-storage-types.enum.ts
interfaces/AW-App/src/app/services/session-storage.service.ts
interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.spec.ts
interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.ts

Related [AB#1918](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1918)
Related [AB#1873](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1873)

Add Types, fix mocks to get predictable results

---

interfaces/HO-Portal/src/app/models/person.model.ts
interfaces/HO-Portal/src/app/models/program.model.ts
interfaces/HO-Portal/src/app/program/program-people-affected/program-people-affected.component.html
interfaces/HO-Portal/src/app/program/program-people-affected/program-people-affected.component.ts
interfaces/HO-Portal/src/app/services/bulk-actions.models.ts
interfaces/HO-Portal/src/app/services/bulk-actions.service.ts

Related [AB#1853](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1853)
Related [AB#1854](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1854)

Refactoring of PeopleAffected-table + bulk-actions

---

interfaces/HO-Portal/src/app/models/person.model.ts
interfaces/HO-Portal/src/app/services/bulk-actions.service.ts

Related [AB#1576](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1576)

AB#2124 Make criteria for "select-for-validation" explicit and exhaustive

---

interfaces/PA-App/src/app/services/pa-account-api.service.ts
interfaces/PA-App/src/app/services/padata.service.ts
services/PA-accounts-service/src/data-storage/data-storage.controller.ts
services/PA-accounts-service/src/data-storage/data-storage.service.ts

Conclusion... not a real improvement. :(

AB#2341 [PoC] Refactor PA-data handling

---

interfaces/AW-App/src/app/services/conversation.service.ts
interfaces/AW-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
interfaces/AW-App/src/app/shared/q-and-a-set/q-and-a-set.component.ts
interfaces/AW-App/src/app/validation-components/main-menu/main-menu.component.ts
interfaces/AW-App/src/app/validation-components/scan-qr/scan-qr.component.spec.ts
interfaces/AW-App/src/app/validation-components/validate-fsp/validate-fsp.component.html
interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.html
interfaces/AW-App/src/assets/i18n/en.json
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.ts

Related [AB#1519](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1519)

AB#2775 Handle pre-filled form mode in Q-and-A-set-component

---

interfaces/AW-App/src/assets/i18n/en.json
interfaces/PA-App/src/assets/i18n/en.json

Related [AB#1519](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1519)

AB#2794 Adjust error-message to be more generic

---

interfaces/AW-App/src/app/shared/numeric-input/numeric-input.component.html
interfaces/AW-App/src/app/shared/numeric-input/numeric-input.component.ts
interfaces/AW-App/src/app/shared/phone-number-input/phone-number-input.component.html
interfaces/AW-App/src/app/shared/phone-number-input/phone-number-input.component.ts
interfaces/AW-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
interfaces/AW-App/src/app/shared/q-and-a-set/q-and-a-set.component.ts
interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.html
interfaces/PA-App/src/app/shared/numeric-input/numeric-input.component.html
interfaces/PA-App/src/app/shared/numeric-input/numeric-input.component.ts
interfaces/PA-App/src/app/shared/phone-number-input/phone-number-input.component.html
interfaces/PA-App/src/app/shared/phone-number-input/phone-number-input.component.ts
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.ts

Related [AB#2793](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/2793)
Related [AB#2785](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/2785)

AB#1519 Fix/refactor issues with validation on all fields + setting answer-data

---

README.md

Related [AB#2779](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/2779)

docs: Fix syntax of heading/lists + add specifics for interfaces [SKIP-CD]

---

CHANGELOG.md

Also: fix syntax issues
Related [AB#3002](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/3002)

Include details of hotfix-release v0.7.2

---

interfaces/README.md

Hey Elwin, 
README within interfaces contains instructions and details regarding unit test cases, and why we should write them and how.

AB#3011 README update for unit test cases

---

services/121-service/src/programs/fsp/dto/fsp-payment-results.dto.ts
services/121-service/src/programs/fsp/fsp.service.spec.ts
services/121-service/src/programs/fsp/fsp.service.ts

@omendram 
1.  Do you have any comments on these tests?
2. Do you have any insights with regards to the amount of effort we can put into these vs the value they add to the 121 project? Does it makes sense to work backwards and create these sort of tests for all our functions?
@jannisvisser So you can also see how the more extended tests look

AB#3101 Create tests for payment details

---

interfaces/PA-App/package-lock.json

Reverts global-121/121-platform#1214

Revert "Build(deps): bump @ionic/cli from 6.11.7 to 6.11.8 in /interfaces/PA-App"

---

CHANGELOG.md

This release will include the hotfixes that where added to "Release v0.8.0"-PR: #1277

Hotfix release v0.8.1

---

interfaces/PA-App/src/app/personal-components/select-language/select-language.component.html
interfaces/PA-App/src/app/personal-components/select-language/select-language.component.ts

To prevent 'jumpyness' of the conversation and/or weird scroll-behaviour
Related [AB#3724](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/3724)

AB#596 Restructure disabled-state of "select-language"

---

interfaces/PA-App/src/app/personal-components/personal-component.class.ts
interfaces/PA-App/src/app/personal/personal.page.html
interfaces/PA-App/src/app/personal/personal.page.ts
interfaces/PA-App/src/app/services/conversation.service.ts
interfaces/PA-App/src/app/shared/dialogue-turn/dialogue-turn.component.scss
interfaces/PA-App/src/app/shared/dialogue-turn/dialogue-turn.component.ts
interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.html

Related [AB#3739](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/3739)
Related [AB#3738](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/3738)

AB#596 Change loading/scrolling behaviour on reload/login

---

interfaces/PA-App/src/app/shared/more-info-button/more-info-button.component.html

Reverts global-121/121-platform#1437

Revert "AB#4076 Tweak styling of more-info-buttons"

---

interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.html
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.scss
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal/personal.page.ts
interfaces/PA-App/src/app/services/conversation.service.ts

Related [AB#3068](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/3068)

Tweak layout + scroll behaviour of "enroll-in-program"-component

---

interfaces/PA-App/package-lock.json
interfaces/Referral-App/package.json
interfaces/Referral-App/src/app/services/help.service.spec.ts
interfaces/Referral-App/src/app/services/offers.service.spec.ts
interfaces/Referral-App/src/app/services/spreadsheet.service.spec.ts
interfaces/Referral-App/src/app/services/spreadsheet.service.ts

monitor failed spreadsheet load exception

AB#4024 monitor referral app

---

CHANGELOG.md

Related [AB#4020](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/4020)

Create release v0.10.0

---

CHANGELOG.md
README.md
tools/.env.example
tools/deploy.sh

Related [AB#4152](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/4152)

Deploy.sh can log to file (and has more verbose output)

---

interfaces/HO-Portal/src/app/models/installment.model.ts
interfaces/HO-Portal/src/app/models/past-installments.model.ts
interfaces/HO-Portal/src/app/program/program-payout/program-payout.component.html
interfaces/HO-Portal/src/app/program/program-payout/program-payout.component.ts
interfaces/HO-Portal/src/app/services/programs-service-api.service.ts

Refactor program-payout page, cleanup Types/Models, etc

AB#4138 Fix: Create Payout-confirmation-message directly

---

interfaces/Referral-App/src/app/components/category/category.component.html
interfaces/Referral-App/src/app/components/category/category.component.scss
interfaces/Referral-App/src/app/components/sub-category/sub-category.component.scss
interfaces/Referral-App/src/app/referral/referral.page.html
interfaces/Referral-App/src/app/referral/referral.page.scss
interfaces/Referral-App/src/app/referral/referral.page.ts
interfaces/Referral-App/src/app/services/spreadsheet.service.ts
interfaces/Referral-App/src/theme/variables.scss

Related [AB#4993](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/4993)
Related [AB#4994](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/4994)

AB#4351 Change colors + refactor layout (retry)

---

services/121-service/seed-data/instance/instance-pilot-nl-2.json
services/121-service/seed-data/program/program-pilot-nl-2.json
services/121-service/src/scripts/scripts.controller.ts
services/121-service/src/scripts/scripts.module.ts
services/121-service/src/scripts/seed-program-pilot-nl-2.ts

Related [AB#5288](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/5288)
Related [AB#5289](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/5289)

Add new pilot seed-data

---

services/121-service/seed-data/program/program-pilot-nl-2.json

Related [AB#5288](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/5288)

fix: Add missing program-property

---

services/121-service/seed-data/instance/instance-pilot-nl-2.json
services/121-service/seed-data/program/program-pilot-nl-2.json

Related [AB#5288](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/5288)
Related [AB#5289](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/5289)

fix: stick to same NGO-name

---

services/docker-compose.yml

Related [AB#3207](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/3207)

Revert changes from #1686

---

services/docker-compose.yml

Reverts global-121/121-platform#1690

Revert "Revert changes from #1686"

---

services/121-service/src/main.ts
services/PA-accounts-service/src/main.ts
services/docker-compose.yml
tools/deploy.sh

Related [AB#1706](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1706)
Related [AB#4871](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/4871)

Show version-number in Swagger-UIs

---

services/PA-accounts-service/package-lock.json
services/PA-accounts-service/package.json

Align TypeScript-versions between services

---

tools/README.md

AB#5418 add nodejs install for webhook to readme

---

README.md
services/121-service/src/programs/fsp/intersolve.service.ts

[AB#5469](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/5469)

Use original balance to determine unused balance

---

interfaces/PA-App/src/app/mocks/conversation.service.mock.ts
interfaces/PA-App/src/app/mocks/instance.service.mock.ts
interfaces/PA-App/src/app/models/logging-event.enum.ts
interfaces/PA-App/src/app/personal-components/consent-question/consent-question.component.spec.ts
interfaces/PA-App/src/app/personal-components/create-identity/create-identity.component.spec.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.spec.ts
interfaces/PA-App/src/app/personal-components/handle-proof/handle-proof.component.spec.ts
interfaces/PA-App/src/app/personal-components/login-identity/login-identity.component.spec.ts
interfaces/PA-App/src/app/personal-components/monitoring-question/monitoring-question.component.spec.ts
interfaces/PA-App/src/app/personal-components/preprinted-qrcode/preprinted-qrcode.component.spec.ts
interfaces/PA-App/src/app/personal-components/registration-summary/registration-summary.component.spec.ts
interfaces/PA-App/src/app/personal-components/select-fsp/select-fsp.component.spec.ts
interfaces/PA-App/src/app/personal-components/select-language/select-language.component.spec.ts
interfaces/PA-App/src/app/personal-components/select-language/select-language.component.ts
interfaces/PA-App/src/app/personal-components/select-program/select-program.component.spec.ts
interfaces/PA-App/src/app/personal-components/set-notification-number/set-notification-number.component.spec.ts
interfaces/PA-App/src/app/personal-components/signup-signin/signup-signin.component.spec.ts
interfaces/PA-App/src/app/personal/personal.page.spec.ts
interfaces/PA-App/src/app/services/conversation.service.ts

AB#5464 Add event-logging to ConversationService

---

.github/dependabot.yml

See #1749 
See #1752 
See #1754 
See #1756

Ignore major release of `karma`

---

LICENSE
README.md
interfaces/AW-App/LICENSE
interfaces/AW-App/README.md
interfaces/AW-App/package.json
interfaces/HO-Portal/LICENSE
interfaces/HO-Portal/README.md
interfaces/HO-Portal/package.json
interfaces/PA-App/LICENSE
interfaces/PA-App/README.md
interfaces/PA-App/package.json
interfaces/Referral-App/LICENSE
interfaces/Referral-App/README.md
package.json
services/121-service/LICENSE
services/121-service/README.md
services/121-service/package.json
services/PA-accounts-service/LICENSE
services/PA-accounts-service/README.md
services/PA-accounts-service/package.json

Related [AB#186](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/186)
Related [AB#187](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/187)
Related [AB#189](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/189)

Add License

---

.github/dependabot.yml

See #1777
See #1779 
See #1783

Ignore Ionic-Native dependencies that require Angular 10+

---

interfaces/HO-Portal/src/app/app.module.ts
interfaces/HO-Portal/src/global.scss

+ Force "Material design"-mode for consistency/predictability of styles

AB#5810 Re-enable selecting text for touch-screen devices

---

interfaces/HO-Portal/src/app/components/user-state/user-state.component.html
interfaces/HO-Portal/src/app/components/user-state/user-state.component.spec.ts
interfaces/HO-Portal/src/app/components/user-state/user-state.component.ts

Related [AB#5913](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/5913)

AB#5940 Remove user-role from header

---

interfaces/AW-App/src/app/http-interceptors/retry-interceptor.ts
interfaces/PA-App/src/app/http-interceptors/retry-interceptor.ts
interfaces/PA-App/src/app/mocks/padata.service.mock.ts
interfaces/PA-App/src/app/models/logging-event.enum.ts
interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.ts
interfaces/PA-App/src/app/personal-components/handle-proof/handle-proof.component.ts
interfaces/PA-App/src/app/personal-components/select-program/select-program.component.ts
interfaces/PA-App/src/app/personal-components/store-credential/store-credential.component.ts
interfaces/PA-App/src/app/services/padata.service.ts
interfaces/PA-App/src/app/user-menu/user-menu.component.ts

Related [AB#984](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/984)

Refactor handling of `programId` in PA-app + add request-retry logging

---

CHANGELOG.md
services/.env.example
services/121-service/src/config.ts
services/121-service/src/main.ts
services/121-service/src/notifications/whatsapp/whatsapp.module.ts
services/121-service/src/scripts/seed-publish.ts
services/PA-accounts-service/src/config.ts
services/PA-accounts-service/src/main.ts
services/PA-accounts-service/src/roles.guard.ts

Creating a specific colored `ENV_ICON` can be done with tools like:
https://shoonia.github.io/1x1/#f5c242ff

AB#4796 Add human-readable ENV_NAME to services-config/Swagger-UI

---

CHANGELOG.md
interfaces/AW-App/src/environments/environment.prod.ts.template.js
interfaces/HO-Portal/src/environments/environment.prod.ts.template.js
interfaces/PA-App/src/environments/environment.prod.ts.template.js

Related [AB#4796](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/4796)

AB#6240 Fix that "undefined" ENV_NAME is always visible

---

interfaces/PA-App/_generate-assets-audio.js
interfaces/PA-App/package-lock.json
interfaces/PA-App/package.json

Hopefully the `install` step of the CI-workflow becomes more predictable this way... 🤞

Replace `ffmpeg-cli` with `ffbinaries` for generating audio

---

services/121-service/src/notifications/imagecode/image-code.service.ts

Related [AB#6830](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/6830)

AB#6829 Fix mapping of month to month-name in Dutch

---

interfaces/AW-App/src/app/http-interceptors/retry-interceptor.ts
interfaces/PA-App/src/app/http-interceptors/retry-interceptor.ts
tools/121-platform-https.conf
tools/deploy.sh

Related [AB#4967](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/4967)
Related [AB#6854](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/6854)

AB#7040 Add "maintenance mode" to set proper headers during deployment(s)

---

tools/deploy.sh

+ Also prevent blocking the whole server while needlessly deleting all `node_modules/`-folders every time

Speed up install+deployment of interfaces

---

features/AW-App/Download_validation_data.feature
features/AW-App/Upload_validation_data.feature

Related [AB#7106](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/7106)
Related [AB#7141](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/7141)

AB#5065 Update/align test/feature scenario's

---

services/121-service/src/connection/connection.service.ts

Related [AB#7404](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/7404)

AB#7403 Retry bulk-import with source-input

---

interfaces/HO-Portal/src/app/program/edit-person-affected-popup/edit-person-affected-popup.component.html
interfaces/HO-Portal/src/app/program/edit-person-affected-popup/edit-person-affected-popup.component.ts
interfaces/HO-Portal/src/app/program/program-people-affected/program-people-affected.component.ts
interfaces/HO-Portal/src/app/services/programs-service-api.service.ts
services/121-service/src/connection/connection.controller.ts
services/121-service/src/connection/connection.service.ts

Related [AB#6674](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/6674)

Refactor handling of "note" in PA-edit pop-up

---

services/121-service/package-lock.json
services/121-service/package.json

Reverts global-121/121-platform#2120

Revert "Test add a dependency"

---

services/121-service/src/connection/connection.controller.ts
services/121-service/src/connection/connection.service.ts
services/121-service/src/connection/validation-data/validation-data.controller.ts
services/121-service/src/programs/program/program.controller.ts
services/121-service/src/programs/program/program.service.ts
services/121-service/src/user/user.controller.ts

Related [AB#8057](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/8057)
Related [AB#6474](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/6474)

AB#8140 fix: Align all programId/userId type uses

---

interfaces/HO-Portal/src/app/models/actions.model.ts
interfaces/HO-Portal/src/app/models/import-type.enum.ts
interfaces/HO-Portal/src/app/program/bulk-import/bulk-import.component.html
interfaces/HO-Portal/src/app/program/bulk-import/bulk-import.component.ts
interfaces/HO-Portal/src/app/program/export-list/export-list.component.html
interfaces/HO-Portal/src/app/program/export-list/export-list.component.ts
interfaces/HO-Portal/src/app/program/make-payment/make-payment.component.spec.ts
interfaces/HO-Portal/src/app/program/make-payment/make-payment.component.ts
interfaces/HO-Portal/src/app/program/test-payment/test-payment.component.ts
interfaces/HO-Portal/src/app/services/programs-service-api.service.ts
interfaces/HO-Portal/src/app/shared/file-picker-prompt/file-picker-prompt.component.html
interfaces/HO-Portal/src/app/shared/file-picker-prompt/file-picker-prompt.component.spec.ts
interfaces/HO-Portal/src/app/shared/file-picker-prompt/file-picker-prompt.component.ts
interfaces/HO-Portal/src/assets/i18n/en.json
services/121-service/src/actions/action.entity.ts
services/121-service/src/connection/connection.controller.ts
services/121-service/src/connection/connection.service.ts
services/121-service/src/connection/dto/bulk-import.dto.ts

- Add template-download endpoint
- Move responsibility of CSV-file-download to shared programs-api-service
-
Related [AB#8314](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/8314)
Related [AB#8313](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/8313)

Add "import as registered"-feature to HO-Portal

---

interfaces/HO-Portal/src/app/program/metrics-states/metrics-states.component.html
interfaces/HO-Portal/src/app/program/metrics-states/metrics-states.component.scss

Add grouping of rows structure to HTML + move styling to CSS

---

interfaces/AW-App/package-lock.json
interfaces/HO-Portal/package-lock.json
interfaces/PA-App/package-lock.json

Closes #2316
Closes #2315 
Closes #2311

build(deps-dev): bump @types/node [SKIP CD]

---

interfaces/AW-App/package-lock.json
interfaces/HO-Portal/package-lock.json
interfaces/PA-App/package-lock.json

Closes #2312 
Closes #2313 
Closes #2314

build(deps-dev): bump jasmine-core [SKIP CD]

---

interfaces/HO-Portal/src/app/components/header/header.component.html
interfaces/HO-Portal/src/app/components/header/header.component.spec.ts
interfaces/HO-Portal/src/app/models/program-metrics.model.ts
interfaces/HO-Portal/src/app/pages/dashboard/dashboard.module.ts
interfaces/HO-Portal/src/app/pages/dashboard/dashboard.page.html
interfaces/HO-Portal/src/app/program/metrics-states/metrics-states.component.html
interfaces/HO-Portal/src/app/program/metrics-states/metrics-states.component.scss
interfaces/HO-Portal/src/app/program/metrics-states/metrics-states.component.spec.ts
interfaces/HO-Portal/src/app/program/metrics-totals/metrics-totals.component.html
interfaces/HO-Portal/src/app/program/metrics-totals/metrics-totals.component.scss
interfaces/HO-Portal/src/app/program/metrics-totals/metrics-totals.component.spec.ts
interfaces/HO-Portal/src/app/program/metrics-totals/metrics-totals.component.ts
interfaces/HO-Portal/src/app/services/programs-service-api.service.ts
interfaces/HO-Portal/src/assets/i18n/en.json
services/121-service/src/export-metrics/dto/pa-metrics.dto.ts
services/121-service/src/export-metrics/export-metrics.service.ts

AB#8630 Add "Total PA helped" to metrics-overview

---

interfaces/HO-Portal/src/app/program/program-payout/program-payout.component.ts

[AB#10602](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/10602)

fix-ngif-haspi

---

interfaces/HO-Portal/ionic.config.json
interfaces/HO-Portal/src/assets/i18n/en.json
interfaces/HO-Portal/src/index.html
interfaces/HO-Portal/src/manifest.json

Related [AB#9966](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/9966)

Rename HO-Portal to 121 Portal in visible places

---

interfaces/AW-App/_check-icons-in-use.js
interfaces/AW-App/angular.json

Related [AB#6668](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/6668)

Move icon-list to "production"-configuration, to allow any icon during development

---

services/121-service/seed-data/program/program-pilot-eth.json
services/121-service/seed-data/program/program-pilot-lbn.json

DevOps #10371: update ZOA seed script with latest info from ZOA.

Update seed script to final version

---

interfaces/AW-App/src/app/directives/only-allowed-input.directive.spec.ts
interfaces/AW-App/src/app/directives/only-allowed-input.directive.ts
interfaces/AW-App/src/app/shared/dialogue-turn/dialogue-turn.component.ts
interfaces/AW-App/src/app/shared/numeric-input/numeric-input.component.spec.ts
interfaces/AW-App/src/app/shared/phone-number-input/phone-number-input.component.html
interfaces/AW-App/src/app/shared/phone-number-input/phone-number-input.component.spec.ts
interfaces/AW-App/src/app/shared/phone-number-input/phone-number-input.component.ts
interfaces/AW-App/src/app/shared/qr-scanner/qr-scanner.component.html
interfaces/AW-App/src/tsconfig.app.json
interfaces/AW-App/src/tsconfig.spec.json
interfaces/AW-App/tsconfig.json
interfaces/HO-Portal/src/app/components/update-fsp/update-fsp.component.html
interfaces/HO-Portal/src/app/components/update-property-item/update-property-item.component.html
interfaces/HO-Portal/src/app/components/update-property-item/update-property-item.component.ts
interfaces/HO-Portal/src/app/directives/only-allowed-input.directive.spec.ts
interfaces/HO-Portal/src/app/directives/only-allowed-input.directive.ts
interfaces/HO-Portal/src/app/login/login.page.html
interfaces/HO-Portal/src/app/shared/shared.module.ts
interfaces/HO-Portal/src/app/user/user.page.html
interfaces/HO-Portal/src/global.scss
interfaces/HO-Portal/src/tsconfig.app.json
interfaces/HO-Portal/src/tsconfig.spec.json
interfaces/HO-Portal/tsconfig.json
interfaces/PA-App/src/app/directives/only-allowed-input.directive.spec.ts
interfaces/PA-App/src/app/directives/only-allowed-input.directive.ts
interfaces/PA-App/src/app/shared/numeric-input/numeric-input.component.spec.ts
interfaces/PA-App/src/app/shared/phone-number-input/phone-number-input.component.html
interfaces/PA-App/src/app/shared/phone-number-input/phone-number-input.component.spec.ts
interfaces/PA-App/src/app/shared/qr-scanner/qr-scanner.component.html
tools/check-shared-code.sh

Related [AB#10993](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/10993)
Related [AB#11004](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/11004)

AB#9899 Improve re-usability of "update-property"-component in Portal

---

interfaces/AW-App/src/app/account/account.page.html
interfaces/AW-App/src/app/shared/date-input/date-input.component.html
interfaces/AW-App/src/app/shared/numeric-input/numeric-input.component.html
interfaces/AW-App/src/app/shared/phone-number-input/phone-number-input.component.html
interfaces/AW-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
interfaces/AW-App/src/app/tabs/tabs.page.html
interfaces/AW-App/src/app/validation-components/download-data/download-data.component.html
interfaces/AW-App/src/app/validation-components/find-by-phone/find-by-phone.component.html
interfaces/AW-App/src/app/validation-components/find-by-phone/find-by-phone.component.spec.ts
interfaces/AW-App/src/app/validation-components/find-by-phone/find-by-phone.component.ts
interfaces/AW-App/src/app/validation-components/main-menu/main-menu.component.html
interfaces/AW-App/src/app/validation-components/scan-qr/scan-qr.component.html
interfaces/AW-App/src/app/validation-components/validate-fsp/validate-fsp.component.html
interfaces/AW-App/src/app/validation-components/validate-fsp/validate-fsp.component.ts
interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.html

Fix template type-issues, to prepare for stricter compiler-rules
By using: `angularCompilerOptions: { strictTemplates: true }` in tsconfig.app.json (in the future)

Cleanup AW-app templates

---

interfaces/HO-Portal/src/app/login/login.page.html
interfaces/HO-Portal/src/app/shared/password-toggle-input/password-toggle-input.component.html
interfaces/HO-Portal/src/app/user/user.page.html
interfaces/PA-App/src/app/shared/password-toggle-input/password-toggle-input.component.html
tools/check-shared-code.sh

Related [AB#10292](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/10292)

Mock native behaviour of form-input labels

---

tools/README.md
tools/deploy.sh

- Do Single deploy of interface
Related [AB#11697](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/11697)
Related [AB#11694](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/11694)
Related [AB#1130](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1130)

Add option(s) to deploy-script

---

tools/deploy.sh

Related [AB#11721](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/11721)

Restart webhook service as a final step, as it will/could kill the deploy.sh-process

---

interfaces/PA-App/src/assets/i18n/ru.json
interfaces/PA-App/src/assets/i18n/uk.json

These source-texts are already in en.json

AB#13097 Remove unused translations from individual language-files

---

interfaces/PA-App/_check-icons-in-use.js
interfaces/PA-App/angular.json

Related [AB#13731](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/13731)

Fix: Add missing icons in build that are used in code not templates

---

interfaces/HO-Portal/src/app/program/edit-person-affected-popup/edit-person-affected-popup.component.html
interfaces/HO-Portal/src/app/program/edit-person-affected-popup/edit-person-affected-popup.component.ts
interfaces/HO-Portal/src/app/program/program-people-affected/program-people-affected.component.ts

Related [AB#14396](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/14396)

AB#14376 Add permissions-check around Message History

---

interfaces/AW-App/src/app/validation-components/main-menu/main-menu.component.ts

[AB#15851](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/15851)

Dynamically refresh programs in AW-app

---

features/121-Portal/Edit_Info_Person_Affected.feature
features/121-Portal/Export_Payment_Details.feature
features/121-Portal/Import_people_affected.feature
features/121-Portal/Import_registrations.feature
features/README.md

AB#15845 Update Portal test-scenarios

---

tools/webhook.js

See https://github.com/global-121/121-platform/security/code-scanning/20

fix: workaround for branch-name check

---

interfaces/HO-Portal/src/app/program/payment-status-popup/payment-status-popup.component.html

AB#16439 Always enable downloading voucher-images

---

interfaces/AW-App/package-lock.json
interfaces/HO-Portal/package-lock.json
interfaces/PA-App/package-lock.json
services/121-service/package-lock.json

Closes #3470 
Closes #3471 
Closes #3472 
Closes #3469

Upgrade json5 dependency AB#17250

---

.github/dependabot.yml

- Added "tests"-app
- Sorted all "Apps" alphabetically
- Sorted all dependencies alphabetically
- use generic types instead of versions
- ignore some dependencies fully

AB#17371 Cleanup Dependabot config/versions

---

interfaces/AW-App/package-lock.json
interfaces/AW-App/package.json
interfaces/HO-Portal/package-lock.json
interfaces/HO-Portal/package.json
interfaces/PA-App/package-lock.json
interfaces/PA-App/package.json

This includes:
#3527 
#3528 
#3529

Chore.update frontend deps

---

.github/workflows/cypress-workflow.yml

> ⚠️ This PR should be rebased after #3547 is merged.
So only the changes from https://github.com/global-121/121-platform/pull/3553/commits/50e0b8cee54b16b60bbb8f8be4adc9b4bb896115 remain.

ci: Split build-steps to work parallel and add caching

---

.github/workflows/cypress-workflow.yml

Reverts global-121/121-platform#3600

Revert "Never run Integratrion tests on draft PRs AB#17864 [SKIP CD]"

---

README.md

Instructions for setting up interfaces updated [AB#18864](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/18864)
Instructions on creating a pull request added [AB#18841](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/18841)

Docs.update readme with new instructions AB#18824 [SKIP CD]

---

.github/workflows/deploy_test_portal.yml
.github/workflows/deploy_test_registration.yml
.github/workflows/deploy_test_verification.yml
CHANGELOG.md
interfaces/AW-App/package.json
interfaces/AW-App/staticwebapp.config.json
interfaces/HO-Portal/package.json
interfaces/HO-Portal/staticwebapp.config.json
interfaces/PA-App/staticwebapp.config.json

[AB#18974](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/18974)

Create GitHub Actions deployment workflow(s) to Azure Static Web Apps (for test-environment) AB#12399

---

features/Other/Edit_Info_Person_Affected_From_EspoCRM.feature

Created a feature file with test scenarios for testing in Swagger

New feature added for manual testing AB#18557

---

.github/workflows/deploy_client-dorcas-ethiopia_all.yml
.github/workflows/deploy_client-dorcas-ethiopia_portal.yml
.github/workflows/deploy_client-dorcas-ethiopia_register.yml
.github/workflows/deploy_client-dorcas-ethiopia_service.yml

See [AB#19202](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/19202)

feat: Add workflows to deploy to Dorcas-Ethiopia instance

---

.github/workflows/deploy_client-dorcas-ethiopia_all.yml
.github/workflows/deploy_client-dorcas-ethiopia_portal.yml
.github/workflows/deploy_client-dorcas-ethiopia_register.yml

See [AB#19202](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/19202)

feat: Set ApplicationInsights-credentials/config for Dorcas-Ethiopia

---

features/Admin-user/Reset_program.feature
features/Admin-user/Update_program.feature

Created a test scenario for AB#19202 and AB#19113

---

.github/workflows/deploy_client-krcs_all.yml
.github/workflows/deploy_client-krcs_portal.yml
.github/workflows/deploy_client-krcs_register.yml
.github/workflows/deploy_client-krcs_service.yml

See [AB#19113](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/19113)

feat: Add deployment workflow(s) for new instance KRCS

---

services/121-service/src/config.ts
services/121-service/src/main.ts

Resolves [AB#19534](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/19534)

feat: redirect any visits to a non-EXTERNAL_121_SERVICE_URL

---

features/121-Portal/View_payment_history_popup.feature

'View payment history popup for a PA' scenario update

Update view payment history test scenario AB#19418

---

interfaces/HO-Portal/src/app/program/payment-history-popup/payment-history-popup.component.scss

Fixed box-sizing for accordion content.

Fix.payment history popup design #AB19418

---

features/121-Portal/Make_new_payment.feature

Added test scenarios for paying with safaricom

Test.do payment with safaricom AB#19528

---

.github/workflows/test_service_api.yml
services/121-service/src/user/user.controller.ts
services/121-service/test/payment/do-payment-fsp-jumbo.test.ts
services/121-service/test/payment/do-payment-fsp-voucher.test.ts

For use in preview-environments of interfaces communication with the test-environment API

fix: Enable cross-origin PA-creation

---

services/121-service/src/user/user.controller.ts

refactor: Clear up logic for PA cookies

---

services/121-service/seed-data/fsp/fsp-commercial-bank-ethiopia.json
services/121-service/seed-data/program/program-joint-response-ANE.json
services/121-service/seed-data/program/program-joint-response-EKHCDC.json
services/121-service/seed-data/program/program-joint-response-dorcas.json
services/121-service/seed-data/program/program-krcs-baringo.json
services/121-service/seed-data/program/program-krcs-turkana.json
services/121-service/seed-data/program/program-krcs-westpokot.json

updated JR and KRCS seed scripts

Feat.update seedscripts

---

.github/dependabot.yml

And exclude Angular from automatic updates

Make dependabot-groups more specific

---

.github/workflows/deploy_client-jrethiopia_all.yml
.github/workflows/deploy_client-krcs_all.yml
.github/workflows/deploy_client-nlrc_all.yml
.github/workflows/deploy_staging_all.yml
.github/workflows/deploy_test_all.yml

Reverts global-121/121-platform#4347

Revert "Change order of deployment + make interface wait on service AB#23711"

---

.github/dependabot.yml

See also [AB#23806](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/23806) [AB#23802](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/23802)

ci: Reduce frequency of Lint-tool updates

---

.github/dependabot.yml

Reverts global-121/121-platform#4403

Revert "ci: Reduce frequency of Lint-tool updates"

---

interfaces/HO-Portal/src/app/components/select-typeahead/select-typeahead.component.html
interfaces/HO-Portal/src/app/components/select-typeahead/select-typeahead.component.ts
interfaces/HO-Portal/src/app/components/status-table-filter/status-table-filter.component.spec.ts
interfaces/HO-Portal/src/app/program/program-people-affected/program-people-affected.component.ts
interfaces/HO-Portal/src/app/program/table-filter-row/table-filter-row.component.spec.ts
interfaces/HO-Portal/src/app/program/table-filter-row/table-filter-row.component.ts
interfaces/HO-Portal/src/app/services/filter.service.ts

See [AB#23856](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/23856)
See [AB#24091](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/24091)

feat: make new text-filters override existing filters AB#23849

---

.github/dependabot.yml

See [AB#23354](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/23354)

Tweak 121-service version upgrades config

---

CHANGELOG.md

Reverts global-121/121-platform#4567

Revert "fix: typo in syntax of CHANGELOG"

---

CHANGELOG.md
services/.env.example
services/121-service/src/main.ts

feat: Remove CORS use (moved to Azure App Services configuration) AB#19333

---

services/twilio-mock-service/src/app.module.ts
services/twilio-mock-service/src/load-test.ts/load-test.controller.ts
services/twilio-mock-service/src/load-test.ts/load-test.module.ts
services/twilio-mock-service/src/load-test.ts/load-test.service.ts
services/twilio-mock-service/src/twilio/twilio.controller.ts

[AB#25180](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/25180)

Chore.test import AB#

---

features/121-Portal/View_messages.feature

(cherry picked from commit 87fd26122c159fcae4ea75a08edd9bba667968e4)

Add feature file to test viewing messages AB#26247

---

interfaces/PA-App/src/app/models/fsp.model.ts
interfaces/PA-App/src/app/personal-components/select-fsp/select-fsp.component.html
interfaces/PA-App/src/app/personal-components/select-fsp/select-fsp.component.ts
interfaces/Portal/src/app/components/registration-activity-overview/registration-activity-overview.component.ts
interfaces/Portal/src/app/components/registration-personal-information/registration-personal-information.component.ts
interfaces/Portal/src/app/components/update-fsp/update-fsp.component.html
interfaces/Portal/src/app/components/update-fsp/update-fsp.component.ts
interfaces/Portal/src/app/models/fsp.model.ts
interfaces/Portal/src/app/models/person.model.ts
interfaces/Portal/src/app/program/edit-person-affected-popup/edit-person-affected-popup.component.html
interfaces/Portal/src/app/program/edit-person-affected-popup/edit-person-affected-popup.component.ts
interfaces/Portal/src/app/program/program-people-affected/program-people-affected.component.ts
interfaces/Portal/src/app/services/table.service.ts
interfaces/Portal/src/assets/i18n/ar.json
interfaces/Portal/src/assets/i18n/en.json
interfaces/Portal/src/assets/i18n/es.json
interfaces/Portal/src/assets/i18n/fr.json
interfaces/Portal/src/assets/i18n/nl.json
services/121-service/test/registrations/send-message-with-placeholder.test.ts

feat: change portal and PaAPP to use `displayName` instead of `fspDisplayNamePortal` and `fspDisplayNamePaApp` [AB#26919](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/26919)

feat: change portal and PaAPP to use `displayName` instead of `fspDisplayNamePortal` and `fspDisplayNamePaApp` AB#26919

---

.github/actions/build-interface/action.yml
.github/actions/build-service/action.yml
.github/workflows/test_workflows.yml

See also [AB#26977](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/26977)

feat: Upgrade used GitHub Action to latest stable version

---

.github/actions/build-interface/action.yml
.github/workflows/deploy_client-nlrc_portal.yml
CHANGELOG.md
interfaces/Portal/angular.json
interfaces/Portal/package.json
interfaces/Portal/staticwebapp.config.json

Related [AB#27368](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27368)

Hotfix for Portal service-worker(s):  v1.115.5

---

services/.env.example
services/121-service/src/main.ts

[AB#27478](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27478)

Cleanup PA-app / AW-app specific redirects in 121-service

---

interfaces/Portal/src/app/enums/filters.enum.ts
interfaces/Portal/src/app/models/program.model.ts
interfaces/Portal/src/app/program/make-payment/make-payment.component.ts
interfaces/Portal/src/app/program/program-people-affected/program-people-affected.component.ts
interfaces/Portal/src/app/program/table-filter-row/table-filter-row.component.ts
interfaces/Portal/src/app/services/filter.service.ts
interfaces/Portal/src/app/services/programs-service-api.service.ts
interfaces/Portal/src/app/services/registrations.service.ts
interfaces/Portal/src/app/shared/payment.utils.ts

[AB#27546](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27546)

fix: Take "quickSearch" into account for all Registrations-endpoints

---

.github/workflows/test_e2e_linting.yml
e2e/.eslintrc.js
e2e/.prettierrc.yml
e2e/package-lock.json
e2e/package.json
e2e/pages/Helpers/Helpers.ts
e2e/pages/Home/HomePage.ts
e2e/pages/Login/LoginPage.ts
e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/pages/Table/TableModule.ts
e2e/playwright.config.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenEditPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenProfilePage.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewPersonalInformationTable.spec.ts
e2e/tsconfig.json

- Reset tsconfig to avoid weirdness that leads to having to use "ts-no-check"
- Add eslint to e2e folder
- Add prettier to e2e folder
- Import eslint & prettier config from other folders
- Fix existing linting issues in files
- Add linting step for e2e folder in CI

Clean TS setup for new `e2e` folder + add eslint/prettier

---

interfaces/Portal/src/app/components/registration-personal-information/registration-personal-information.component.ts
interfaces/Portal/src/app/components/update-fsp/update-fsp.component.html
interfaces/Portal/src/app/components/update-fsp/update-fsp.component.ts
interfaces/Portal/src/app/models/fsp.model.ts
interfaces/Portal/src/app/models/person.model.ts
interfaces/Portal/src/app/program/edit-person-affected-popup/edit-person-affected-popup.component.html
interfaces/Portal/src/app/program/edit-person-affected-popup/edit-person-affected-popup.component.ts
interfaces/Portal/src/app/program/program-payout/program-payout.component.ts
interfaces/Portal/src/app/program/program-people-affected/program-people-affected.component.ts
interfaces/Portal/src/app/shared/payment-result.ts

…n the table [AB#27550](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27550)

fix: display the correct FSP name in the PA popup and the FSP names in the table AB#27550

---

e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityFspOverview.spec.ts
services/121-service/test/helpers/program.helper.ts

This PR adds new API test that edits FSP used by PA and validates history of changes on PAs Activity Overview.

AB#27748 Add e2e TC & program.helper function

---

.github/workflows/test_e2e_linting.yml
.github/workflows/test_interface_portal.yml
.github/workflows/test_mock-service_code.yml
.github/workflows/test_prettier.yml
.github/workflows/test_service_api.yml
.github/workflows/test_service_code.yml
.github/workflows/test_workflows.yml
README.md
docs/CONTRIBUTING.md
docs/pull_request_template.md

Consolidation of the PR review guidelines doc.
More info:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates

Add PR guidelines to repository

---

e2e/tests/121-Portal/ViewPaProfilePage/ValidateFspInPaPopUp.spec.ts

Adds second ID for the test imported from Feature file .

AB#27814 Add additional TC ID

---

interfaces/Portal/src/app/components/status-table-filter/status-table-filter.component.ts
interfaces/Portal/src/app/mocks/api.program-metrics.mock.ts
interfaces/Portal/src/app/models/person.model.ts
interfaces/Portal/src/app/models/program-metrics.model.ts
interfaces/Portal/src/assets/i18n/ar.json
interfaces/Portal/src/assets/i18n/en.json
interfaces/Portal/src/assets/i18n/es.json
interfaces/Portal/src/assets/i18n/fr.json
interfaces/Portal/src/assets/i18n/nl.json
services/121-service/migration/1713363871246-remove-startedRegistration-state.ts
services/121-service/src/metrics/dto/pa-metrics.dto.ts
services/121-service/src/registration/dto/registration-response.model.ts
services/121-service/src/registration/enum/registration-status.enum.ts
services/121-service/src/registration/registrations.service.ts
services/121-service/src/registration/services/registrations-bulk.service.spec.ts
services/121-service/src/shared/const.ts

[AB#27475](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27475)

Remove startedRegistration state

---

.github/workflows/test_prettier.yml

In #5192 we realised that the changes in #5191 broke the prettier job in CI.
This change fixes the issue by changing the definition of how files are checked in the relevant yaml file

Fix Prettier job in CI

---

services/121-service/migration/1713363871246-remove-startedRegistration-state.ts

fix: fixed the migration related to startedRegistration status change which was failing against production data

fix: fixed the migration related to startedRegistration status change

---

interfaces/Portal/src/app/models/program.model.ts
services/121-service/migration/1714129715256-remove-meeting-documents.ts
services/121-service/seed-data/program/program-demo.json
services/121-service/seed-data/program/program-drc.json
services/121-service/seed-data/program/program-eth-joint-response.json
services/121-service/seed-data/program/program-joint-response-ANE.json
services/121-service/seed-data/program/program-joint-response-EKHCDC.json
services/121-service/seed-data/program/program-joint-response-dorcas.json
services/121-service/seed-data/program/program-krcs-baringo.json
services/121-service/seed-data/program/program-krcs-turkana.json
services/121-service/seed-data/program/program-krcs-westpokot.json
services/121-service/seed-data/program/program-nlrc-ocw.json
services/121-service/seed-data/program/program-nlrc-pv.json
services/121-service/seed-data/program/program-pilot-dorcas-eth.json
services/121-service/seed-data/program/program-pilot-lbn.json
services/121-service/seed-data/program/program-pilot-ukr.json
services/121-service/seed-data/program/program-pilot-zoa-eth.json
services/121-service/seed-data/program/program-test.json
services/121-service/seed-data/program/program-validation.json
services/121-service/src/programs/dto/create-program.dto.ts
services/121-service/src/programs/dto/program-return.dto.ts
services/121-service/src/programs/dto/update-program.dto.ts
services/121-service/src/programs/program.entity.ts
services/121-service/src/programs/programs.service.ts

[AB#27476](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27476)

Remove unused "meetingDocuments"-property from Program(s)

---

README.md

[AB#27845](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27845)
Added 2 lines about creating migrations, following recent learnings.

Add explainer text for data migrations: no imports and no changes after merge to main

---

e2e/README.MD
e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewPaymentsTab.spec.ts

E2E test validating Payments tab in PA Activities. Test Follows simpler setup and adds new function for validating the payment log tile.

Test.view activity overview 'payments tab'

---

services/121-service/src/metrics/metrics.service.ts
services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts

[AB#1234](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1234) 
Added referenceId to unused voucher export

add referenceId to unused voucher export #AB27868

---

services/121-service/src/utils/waitFor.helper.spec.ts

[AB#1234](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/1234) 
This test randomly fails like here https://github.com/global-121/121-platform/actions/runs/8911133421/attempts/1?pr=5229

Fix.failing test

---

services/121-service/migration/1713363871246-remove-startedRegistration-state.ts

When I tested the feat.remove-registration-status branch with production data I ran into a foreig key constraint error. This fixes that

Also delete notes related to started registration

---

services/121-service/src/registration/services/registrations-import.service.ts
services/121-service/src/registration/validators/registrations-input-validator.ts
services/121-service/test/registrations/import-registration.test.ts
services/docker-compose.development.yml

[AB#27674](https://dev.azure.com/redcrossnl/121%20Platform/_sprints/taskboard/121%20Development%20Team/121%20Platform/Sprint%20127?workitem=27674) 
fix: if phoneNumber is not in body, /api/programs/{programId}/registrations/import returns 500 without explanation

Fix.allow empty phonenumber v2

---

services/121-service/migration/1713363871246-remove-startedRegistration-state.ts

I was still getting an error when running this migration against production data. With the help of Ashish I was able to fix it.

Fix startedRegistration migration

---

e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/QuickSearch/QuickFilterBulkActionsBug.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenEditPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenProfilePage.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ValidateFspInPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverview.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewPaymentsTab.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewPersonalInformationTable.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewVisaDebitCardsTable.spec.ts
interfaces/Portal/src/app/components/registration-activity-detail/registration-activity-detail.component.html

Refactor of e2e test to fix issues on CI test execution and overall performance:
All before each setup functions are either reusing same seeding script or if necessary are adapted to each use case.
bulkActionsBug test now has hardcoded 5 second wait for simplicity reasons to avoid hassle in refactoring FE at this moment.

Refactor.e2e test cases

---

interfaces/Portal/src/app/components/status-table-filter/status-table-filter.component.ts

[AB#27921](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27921)

AB#27921 View declined PA in inclusion phase

---

e2e/pages/Home/HomePage.ts
e2e/pages/Login/LoginPage.ts
e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenEditPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenProfilePage.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ValidateFspInPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityFspOverview.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverview.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewMessageTab.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewPaymentsTab.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewPersonalInformationTable.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewVisaDebitCardsTable.spec.ts
interfaces/Portal/src/app/components/registration-activity-detail/registration-activity-detail.component.html
interfaces/Portal/src/app/components/registration-activity-overview/registration-activity-overview.component.html
interfaces/Portal/src/app/components/registration-page-table/registration-page-table.component.html
interfaces/Portal/src/app/components/registration-personal-information/registration-personal-information.component.html
interfaces/Portal/src/app/components/registration-physical-card-overview/registration-physical-card-overview.component.html
interfaces/Portal/src/app/components/registration-profile/registration-profile.component.html
interfaces/Portal/src/app/pages/home/components/programs-list/programs-list.component.html

[AB#27896 Add test ids and refactor functions](https://github.com/global-121/121-platform/commit/a8ce1e4c19b732bb5e4c626de287c59a72541d46)
First batch of significant changes in POM:
- Moving away from CSS selectors
-  Added "data-testid" in Portal that will make tests less vulnerable to refactoring and easier to maintain for everyone included in the process

AB#27896 Add test ids and refactor functions

---

services/121-service/src/metrics/metrics.service.ts

[AB#27988](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27988)

feat: add registrationStatus to payment export

---

e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/QuickSearch/QuickFilterBulkActionsBug.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenEditPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenProfilePage.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ValidateFspInPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityFspOverview.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverview.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewMessageTab.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewPaymentsTab.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewPersonalInformationTable.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewVisaDebitCardsTable.spec.ts

Added new function for switching table based on new feature "Open default on 'People affected' page"

AB#27993 fix tests based on UI changes

---

services/121-service/src/programs/utils/overwrite-fsp-display-name.helper.ts

Weird error happening in the test environment based on the latest changes I introduced in #5274
This might fix it. Or it might just highlight another error. We shall see.

fix: attempt to fix test environment

---

e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/ViewPaProfilePage/WrongLanguagesInTemplatedMessagesBug.spec.ts
interfaces/Portal/src/app/program/edit-person-affected-popup/edit-person-affected-popup.component.html
interfaces/Portal/src/app/program/registration-activity-detail-accordion/registration-activity-detail-accordion.component.html
interfaces/Portal/src/app/shared/input-prompt/input-prompt.component.html

Add e2e test case based on the bug item: 
https://dev.azure.com/redcrossnl/121%20Platform/_sprints/taskboard/121%20Development%20Team/121%20Platform/Sprint%20128?workitem=27895

AB#27910 add e2e test

---

services/121-service/test/helpers/program.helper.ts
services/121-service/test/payment/do-payment-fsp-voucher.test.ts
services/121-service/test/payment/payment-count-completed.test.ts
services/121-service/test/registrations/send-message-with-placeholder.test.ts
services/121-service/test/registrations/send-templated-message.test.ts

I tried increasing retries here: https://github.com/global-121/121-platform/pull/5240
But it seems that is not enough because it still fails 3 times in a row at times.
Now I'm trying to increase the timeouts, and increase frequency of checking, in the relevant helpers, with the hope that this is caused by a slow inner network in CI (at times).

chore: fix flaky test - attempt #2

---

services/121-service/src/registration/dto/registration-status-patch.dto.ts
services/121-service/src/registration/dto/send-custom-text.dto.ts
services/121-service/src/registration/validators/is-not-both-empty.class.validator.spec.ts
services/121-service/src/registration/validators/is-not-both-empty.class.validator.ts
services/121-service/src/registration/validators/is-not-both-present.class.validator.spec.ts
services/121-service/src/registration/validators/is-not-both-present.class.validator.ts
services/121-service/test/registrations/send-templated-message.test.ts

[AB#27976](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27976) 
Better validation for sending messages (on status change and custom message). This is to prevent that both a message and a messageTemplateKey are added to the body.

AB#27976 Better validation for message sending

---

e2e/tests/121-Portal/ViewPaProfilePage/SuccessfullyViewNote.spec.ts

E2E test case validating added note in PAs profile overview notes tab

AB#27991 add e2e test case

---

CHANGELOG.md

Release v1.119.0

---

e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/tests/121-Portal/ViewPaProfilePage/UnsuccessfullyAddNote.spec.ts

E2E test to check if user can add note without the content

AB#27990  add e2e test

---

services/121-service/src/financial-service-providers/dto/update-financial-service-provider.dto.ts
services/121-service/src/instance/dto/update-instance.dto.ts
services/121-service/src/metrics/dto/export-details.dto.ts
services/121-service/src/notifications/message-template/dto/message-template.dto.ts
services/121-service/src/notifications/twilio.dto.ts
services/121-service/src/notifications/twilio.entity.ts
services/121-service/src/payments/dto/import-fsp-reconciliation.dto.ts
services/121-service/src/payments/fsp-integration/africas-talking/dto/africas-talking-notification.dto.ts
services/121-service/src/payments/fsp-integration/africas-talking/dto/africas-talking-validation.dto.ts
services/121-service/src/payments/fsp-integration/belcash/dto/belcash-payment-status.dto.ts
services/121-service/src/programs/dto/create-program-custom-attribute.dto.ts
services/121-service/src/programs/dto/create-program.dto.ts
services/121-service/src/programs/dto/program-question.dto.ts
services/121-service/src/programs/dto/update-program.dto.ts
services/121-service/src/registration/dto/bulk-import.dto.ts
services/121-service/src/registration/dto/bulk-update.dto.ts
services/121-service/src/registration/dto/registration-status-patch.dto.ts
services/121-service/src/registration/dto/search-registration.dto.ts
services/121-service/src/registration/dto/send-custom-text.dto.ts
services/121-service/src/registration/dto/set-fsp.dto.ts
services/121-service/src/registration/dto/set-phone-request.dto.ts
services/121-service/src/registration/dto/update-registration.dto.ts
services/121-service/src/registration/registration.entity.ts
services/121-service/src/user/dto/assign-aw-to-program.dto.ts
services/mock-service/src/twilio/twilio.dto.ts

[AB#28066](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28066)
Spin-off of https://github.com/global-121/121-platform/pull/5274 (see comment: https://github.com/global-121/121-platform/pull/5274/files/d93c075e5e6ec3ec2187d886a90988ba41607cc5#discussion_r1599594636)

Make sure `isOptional` properties are marked as optional in TypeScript

---

e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/EditInfoPersonAffected/ViewInformationIconInTable.spec.ts
interfaces/Portal/src/app/program/program-people-affected/program-people-affected.component.html

Refactors TableModule aligning it with the suite's pattern and adds e2e test: [View information icon in table](https://dev.azure.com/redcrossnl/121%20Platform/_workitems/edit/28035)

Test.view information icon in table

---

.github/workflows/test_e2e.yml
.github/workflows/test_service_api.yml
services/121-service/Dockerfile
services/docker-compose.yml
services/mock-service/Dockerfile

Fix: healthcheck wait

---

e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/EditInfoPersonAffected/NoPermissionToViewInformationIconInTable.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/ViewInformationIconInTable.spec.ts
interfaces/Portal/src/app/program/program-people-affected/program-people-affected.component.html
services/.env.example
services/121-service/src/scripts/seed-helper.ts
services/121-service/src/scripts/seed-init.ts
services/121-service/src/user/user-role.enum.ts

E2E test case that adds new user and tests against PII view permissions

Test.no permission to view information

---

e2e/pages/Home/HomePage.ts
e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/EditInfoPersonAffected/OpenPopUpViewAndEdit.spec.ts
e2e/tests/121-Portal/QuickSearch/QuickFilterBulkActionsBug.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ValidateFspInPaPopUp.spec.ts
interfaces/Portal/src/app/components/update-property-item/update-property-item.component.html
interfaces/Portal/src/app/pages/home/components/programs-list/programs-list.component.html
interfaces/Portal/src/app/program/edit-person-affected-popup/edit-person-affected-popup.component.html
interfaces/Portal/src/app/shared/confirm-prompt/confirm-prompt.component.html

Slightly updates homePage POM with data-testIds and removes unnecessary okButton locator.

Refactor.home page pom

---

e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdatePaymentMultiplierSuccessfully.spec.ts

Test.update payment amount multiplier successfully

---

README.md
package.json

[AB#28108](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28108)

chore: update release process

---

e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/playwright.config.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdatePreferredLanguageSuccessfully.spec.ts

Add e2e test for prefferedLanguage dropdown

AB#28058 add e2e test case

---

e2e/pages/Helpers/Helpers.ts
e2e/pages/Navigation/NavigationModule.ts
e2e/pages/Payments/PaymentsPage.ts
e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/MakeNewPayment/MakeSuccessfulPaymentOCW.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/SuccessfullyAddNote.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/SuccessfullyViewNote.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityFspOverview.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverview.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewMessageTab.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewPaymentsTab.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewPersonalInformationTable.spec.ts
interfaces/Portal/src/app/program/make-payment/make-payment.component.html
interfaces/Portal/src/app/program/program-tabs-navigation/program-tabs-navigation.component.html

Adding an e2e test for "Do Payment". To be used on #5322 to verify a bug

feat: add test for "do payment"

---

.github/workflows/codeql-analysis.yml
.github/workflows/test_codeql-analysis.yml
.github/workflows/test_formatting.yml
.github/workflows/test_workflows.yml

To 'optimize' how the left-hand menu looks on the "All workflows"-overview: https://github.com/global-121/121-platform/actions
The only way to have some control over this, is to rename the workflows in a "namespaced" way.

feat: Rename Workflows to reorder the list on GitHub Actions

---

interfaces/Portal/src/app/services/logging.service.ts

See: [AB#28369](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28369)

fix: Disable loading of external config for ApplicationInsights AB#28369

---

services/121-service/src/financial-service-providers/enum/financial-service-provider-name.enum.ts
services/121-service/src/payments/dto/split-payment-lists.dto.ts
services/121-service/src/payments/payments.service.ts

[AB#28258](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28258)
Similarly to what was done in this commit: https://github.com/global-121/121-platform/commit/e8737a3d638d0b7d8d6259187989dde134d2d835
Quoting the above commit:
> This is always preferable for [speed and ease of readability](https://dev.to/b3ns44d/alternative-to-if-else-and-switch-object-literals-in-javascript-3nde)

chore: [payments.service] clean long if/else chain into a map

---

interfaces/Portal/src/app/auth/permission.enum.ts
interfaces/Portal/src/app/components/physical-card-popup/physical-card-popup.component.ts
interfaces/Portal/src/app/components/registration-physical-card-overview/registration-physical-card-overview.component.ts
interfaces/Portal/src/app/components/registration-profile/registration-profile.component.ts
interfaces/Portal/src/app/enums/event-type.enum.ts
interfaces/Portal/src/app/enums/fsp-name.enum.ts
interfaces/Portal/src/app/enums/interface-names.enum.ts
interfaces/Portal/src/app/enums/registration-status.enum.ts
interfaces/Portal/src/app/enums/status-dates.enum.ts
interfaces/Portal/src/app/models/bulk-actions.models.ts
interfaces/Portal/src/app/models/physical-card.model.ts
interfaces/Portal/src/app/program/export-fsp-instructions/export-fsp-instructions.component.ts
interfaces/Portal/src/app/program/export-list/export-list.component.ts
interfaces/Portal/src/app/program/program-payout/program-payout.component.ts
interfaces/Portal/src/app/shared/payment.utils.ts
interfaces/Portal/tsconfig.json

[AB#28381](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28381)

chore: add 121-service alias to portal

---

interfaces/Portal/src/app/program/program-tabs-navigation/program-tabs-navigation.component.ts

https://dev.azure.com/redcrossnl/121%20Platform/_workitems/edit/28376
fix: hide monitoring dashboard if program doesn't have monitoringDashboardUrl configured

fix: hide monitoring dashboard if program doesn't have monitoringDashboardUrl configured

---

CHANGELOG.md

Update CHANGELOG.md for 1.120.0

---

services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts

+ Use existing Enums where possible
- [-] I have added tests wherever relevant

fix: Improve logging of FSP-configuration errors AB#28408

---

e2e/pages/Payments/PaymentsPage.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/MakeSuccessfulPaymentOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/ReIssueCardOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/ShowMaximumTotalAmountOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/MakeSuccessfulPaymentPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ReIssueCardPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ShowMaximumTotalAmountPV.spec.ts
package-lock.json
package.json
services/121-service/test/helpers/registration.helper.ts
services/121-service/test/registrations/pagination/filter-registration.payment.test.ts
services/121-service/test/registrations/pagination/pagination-data.ts

1. Adds e2e test for checking the re issue visa card functionality and it's statuses.
2. Adds successful payment test
3. Adds Dry Run Test
4. Refactors API test

Test.re issue card

---

services/121-service/src/migration/1717513412071-add-new-intersolve-entities.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/entities/intersolve-visa-child-wallet.entity.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/entities/intersolve-visa-customer.entity.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/entities/intersolve-visa-parent-wallet.entity.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa-wallet.entity.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.module.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/registration/registration.entity.ts

Add new Visa entities

---

e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/tests/121-Portal/EditInfoPersonAffected/OpenPopUpViewAndEdit.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/MakeSuccessfulPaymentPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/PauseCardPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ReIssueCardPV.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenProfilePage.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ValidateFspInPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewPersonalInformationTable.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/WrongLanguagesInTemplatedMessagesBug.spec.ts
interfaces/Portal/src/app/services/programs-service-api.service.ts

Just a bug fix about default sort order

fix: fixed about default sort order AB#28422

---

services/121-service/src/notifications/message-incoming/message-incoming.service.ts
services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
services/121-service/src/shared/services/custom-http.service.ts
services/121-service/src/utils/mask-value.helper.spec.ts
services/121-service/src/utils/mask-value.helper.ts

See [AB#28559](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28559)

Redact specific data before logging it AB#28559

---

services/121-service/package.json

[AB#28630](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28630)
The VSCode debugger had stopped working. This fixes it.

fix: 121-service debugging

---

services/121-service/src/metrics/metrics.service.ts
services/121-service/src/program-attributes/program-attributes.service.ts
services/121-service/src/registration/enum/custom-data-attributes.ts
services/121-service/test/metrics/export-list.test.ts

Feat.filter current payment count

---

CHANGELOG.md

[AB#28601](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28601)

Release v1.122.0

---

e2e/package-lock.json
e2e/package.json
e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/ExportCardDataOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ExportCardDataPV.spec.ts

Tests xlsx download of debit card usage, parses data from xlsx file and validates expected column names

AB#28629 add e2e test for OCW & PV

---

e2e/test-registration-data/test-registrations-OCW-no-refereceId.csv
services/121-service/src/app.module.ts
services/121-service/src/migrate-visa/migrate-visa.controller.ts
services/121-service/src/migrate-visa/migrate-visa.module.ts
services/121-service/src/migrate-visa/migrate-visa.service.ts
services/121-service/src/migration/1718033261904-add-new-intersolve-entities.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/entities/intersolve-visa-child-wallet.entity.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/entities/intersolve-visa-parent-wallet.entity.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.controller.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts

Changed migration
Visa migration fixes after testing with integration API
[AB#28498](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28498)

Migrate visa wallet to child - parent

---

services/121-service/src/registration/services/registrations-import.service.ts
services/121-service/src/registration/validators/registrations-input-validator.ts
services/121-service/test/commercial-bank-ethiopia/export-validation-report.test.ts
services/121-service/test/registrations/__snapshots__/import-registration.test.ts.snap
services/121-service/test/registrations/import-registration.test.ts

AB#28652 Block empty dropdown value on import

---

e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/test-registration-data/test-registrations-westeros-20.csv
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateDateWithInvalidInput.spec.ts
interfaces/Portal/src/app/components/update-property-item/update-property-item.component.html

E2E test validating browser dialog window

AB#28674 add e2e test

---

e2e/package-lock.json
e2e/package.json
interfaces/Portal/package-lock.json
interfaces/Portal/package.json

[AB#28622](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28622)
Addresses https://github.com/global-121/121-platform/security/dependabot/431 and https://github.com/global-121/121-platform/security/dependabot/432
I changed the install location of `xlsx` according to documentation here: https://docs.sheetjs.com/docs/getting-started/installation/nodejs#legacy-endpoints

chore: address dependabot security vulnerability (SheetJS)

---

services/121-service/src/notifications/message.service.spec.ts
services/121-service/test/payment/__snapshots__/do-payment-fsp-voucher.test.ts.snap
services/121-service/test/payment/do-payment-fsp-voucher.test.ts

[AB#28732](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28732)

chore: unit test for wrong message sent

---

services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/test-registration-data/test-registrations-OCW.csv
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa-mock-response.dto.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.controller.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts

[AB#28281](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28281)
Mock new setup of intersolve with linktoken and transfer

AB#28281 Mock link token & transfer

---

CHANGELOG.md
interfaces/Portal/src/app/services/messages.service.ts
services/121-service/src/notifications/message-incoming/message-incoming.service.ts
services/121-service/src/notifications/message.service.spec.ts
services/121-service/src/notifications/message.service.ts
services/121-service/src/notifications/whatsapp/whatsapp.service.ts
services/121-service/test/payment/__snapshots__/do-payment-fsp-voucher.test.ts.snap
services/121-service/test/payment/do-payment-fsp-voucher.test.ts

[AB#28730](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28730)

Hotfix v1.122.1

---

e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateFinancialServiceProvider.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateHouseNumberInvalid.spec.ts

Fix test, update functions, separate DOM elements

---

e2e/pages/PersonalInformationPopUp/PersonalInformationPopUp.ts
e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/tests/121-Portal/EditInfoPersonAffected/OpenPopUpViewAndEdit.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateCustomAttributesSuccessfully.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateDateWithInvalidInput.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateHouseNumberInvalid.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdatePaymentMultiplierInvalid.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdatePaymentMultiplierSuccessfully.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdatePhoneNumberInvalid.spec.ts

Separates "RegistrationDetails" into "PersonalInformationPopUp" and "RegistrationDetails"

AB#28771 Update tests separate poms

---

e2e/pages/PersonalInformationPopUp/PersonalInformationPopUp.ts
e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateFinancialServiceProvider.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ValidateFspInPaPopUp.spec.ts

AB#28668 e2e test

---

.github/workflows/deploy_client-training_all.yml
.github/workflows/deploy_client-training_portal.yml
.github/workflows/deploy_client-training_service.yml

[AB#28813](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28813)

chore: add training environment

---

CHANGELOG.md
README.md
interfaces/Portal/README.md
interfaces/README.md

See: [AB#28786](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28786) / [AB#28676](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28676)

docs: Use CalVer-format for new releases (and hotfixes)

---

services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/repositories/intersolve-visa-customer.scoped.repository.ts

Finalize process transfer jobs

---

services/121-service/src/shared/services/custom-http.service.ts

Fixes what was introduced by: #5397
See [AB#28900](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28900)

fix: Prevent redacting(/breaking) payloads that are not objects (strings, etc.)

---

e2e/tests/121-Portal/EditInfoPersonAffected/OpenPopUpViewAndEdit.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateCustomAttributesSuccessfully.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateDateWithInvalidInput.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdatePaymentMultiplierInvalid.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/ExportCardDataOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/MakeSuccessfulPaymentOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ExportCardDataPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/MakeSuccessfulPaymentPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/PauseCardPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ReIssueCardPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/RetryPaymentPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ShowMaximumTotalAmountPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ViewVisaCardsPV.spec.ts
e2e/tests/121-Portal/QuickSearch/QuickFilterBulkActionsBug.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenEditPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenProfilePage.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/SuccessfullyAddNote.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/SuccessfullyViewNote.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/UnsuccessfullyAddNote.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ValidateFspInPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityFspOverview.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverview.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewMessageTab.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewPaymentsTab.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewPersonalInformationTable.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewVisaDebitCardsTable.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/WrongLanguagesInTemplatedMessagesBug.spec.ts
e2e/tests/UserManualScreenshots/userManualScreenshots.spec.ts

Add translations on top of the tests.

Add transaltions for new PR

---

.github/actions/build-service/action.yml

[AB#28879](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28879)

fix: Make "prune build"-step more flexible for reuse

---

CHANGELOG.md
README.md
package.json
services/.env.example
services/121-service/README.md
services/121-service/WORKFLOWS.md
services/121-service/nest-cli.json
services/121-service/package.json
services/docker-compose.development.yml
services/docker-compose.yml
services/mock-service/README.md
services/mock-service/nest-cli.json
services/mock-service/package.json
services/mock-service/src/app.module.ts
services/mock-service/src/config.ts
services/mock-service/src/instance.module.ts
services/mock-service/src/main.ts

[AB#28880](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28880)

chore: add instance/version endpoint to mock-service

---

services/121-service/src/payments/fsp-integration/safaricom/dto/safaricom-job.dto.ts
services/121-service/src/payments/fsp-integration/safaricom/dto/safaricom-transfer-payload.dto.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.controller.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.service.spec.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.ts
services/121-service/src/registration/services/registrations-bulk.service.ts
services/mock-service/src/fsp-integration/safaricom/safaricom.mock.service.ts

Test.safaricom user question

---

.github/dependabot.yml

Update Dependabot config to include Portalicious

---

CHANGELOG.md

See: [AB#28704](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28704)
See: [AB#28848](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28848)

Create release v24.6-0

---

.github/workflows/deploy_staging_all.yml

[AB#28849](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28849)

fix: Set correct permissions for deployments

---

CHANGELOG.md

fix: Create new (hotfix) release to enable auto-deploy to Staging

---

services/121-service/test/payment/do-payment-safaricom.test.ts

feat: create api test for safaricom AB#28905

---

services/121-service/src/registration/registration-view.entity.ts
services/121-service/src/registration/services/registrations-pagination.service.ts

AB#28969 Disable eager relations in registrationView

---

e2e/pages/Payments/PaymentsPage.ts
e2e/pages/PersonalInformationPopUp/PersonalInformationPopUp.ts
e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/ViewPaProfilePage/SuccessfullyAddNote.spec.ts

Update translations to only keep the imports and definitions on top of the file for easier maintenance.

AB#28773 e2e test

---

e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/QuickSearch/QuickFilterBulkActionsBug.spec.ts

Fixes QuickFilterBulkActionsBug by adding max: 3 page reloads if the expected result is still not displayed due to async function on BE.

AB#28775 Fix quickSearch test

---

e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/ExportCardDataOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ExportCardDataPV.spec.ts

Changes xlsx validation to also assert selected data from the export

AB#28772 Add extra validation for xlsx & use translations

---

e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewVisaDebitCardsTable.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/WrongLanguagesInTemplatedMessagesBug.spec.ts

Make test smarter by using language and order selection combination.

AB#28975 change order selection to combine order & language

---

e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/EditInfoPersonAffected/OpenPopUpViewAndEdit.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateCustomAttributesSuccessfully.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateFinancialServiceProvider.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdateHouseNumberInvalid.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdatePaymentMultiplierInvalid.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdatePaymentMultiplierSuccessfully.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdatePhoneNumberInvalid.spec.ts
e2e/tests/121-Portal/EditInfoPersonAffected/UpdatePreferredLanguageSuccessfully.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/MakeSuccessfulPaymentOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/PauseCardOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/ReIssueCardOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/ViewVisaCardsOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/MakeSuccessfulPaymentPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/PauseCardPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ReIssueCardPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ViewVisaCardsPV.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenEditPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/OpenProfilePage.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/SuccessfullyAddNote.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/SuccessfullyViewNote.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/UnsuccessfullyAddNote.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ValidateFspInPaPopUp.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityFspOverview.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverview.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewMessageTab.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewPaymentsTab.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewPersonalInformationTable.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewVisaDebitCardsTable.spec.ts
e2e/tests/UserManualScreenshots/userManualScreenshots.spec.ts

Removes selection of PA by order to selecting by FSP which guarantees in most cases immunity from order changes in UI and more randomised tests.

AB#28770 switch from order to fsp selection

---

interfaces/Portalicious/src/app/components/component-guidelines.md

[AB#28826](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28826)
Imported from https://github.com/global-121/component-library-demo/pull/9

chore: add component guidelines for Portalicious

---

CHANGELOG.md

AB#29001 changelog

---

interfaces/Portalicious/.prettierrc.yml
interfaces/Portalicious/angular.json
interfaces/Portalicious/eslint.config.js
interfaces/Portalicious/package-lock.json
interfaces/Portalicious/package.json
interfaces/Portalicious/src/app/app.component.html
interfaces/Portalicious/src/app/app.component.spec.ts
interfaces/Portalicious/src/app/app.component.ts
interfaces/Portalicious/src/app/app.config.ts
interfaces/Portalicious/src/main.ts
interfaces/Portalicious/tsconfig.json
package-lock.json
package.json

[AB#28823](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28823)

chore: add strict mode and strict linting to Portalicious AB#28823

---

.github/actions/build-interface/action.yml
.github/workflows/deploy_test_all.yml
.github/workflows/deploy_test_portalicious.yml
.github/workflows/test_e2e_portal.yml
.github/workflows/test_e2e_portalicious.yml
.github/workflows/test_interface_portalicious.yml
README.md
e2e/package.json
e2e/playwright.portalicious.config.ts
e2e/tests.portalicious/121-Portal/ViewHomepage/ViewHomepage.spec.ts
interfaces/Portal/package.json
interfaces/Portalicious/.gitignore
interfaces/Portalicious/README.md
interfaces/Portalicious/angular.json
interfaces/Portalicious/eslint.config.js
interfaces/Portalicious/package-lock.json
interfaces/Portalicious/package.json
interfaces/Portalicious/src/main.ts
interfaces/Portalicious/staticwebapp.config.json

[AB#28827](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28827)
Given that [SWA comments are disabled](https://github.com/global-121/121-platform/pull/5495/files#diff-46905a6e4d519c88934148cf7d70e40c7459796e5da8b766a8aef48b624bbc87R10-R12), it takes some digging to find the preview URL. If it doesn't change once it's been assigned to a PR, then it should be this: https://lively-river-04adce503-5495.westeurope.5.azurestaticapps.net/

chore: add CI jobs to Portalicious

---

services/121-service/src/cronjob/cronjob.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.controller.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/repositories/intersolve-visa-customer.scoped.repository.ts

Re-implement retrieve and update wallets and cards cron job

---

services/121-service/module-dependencies.md
services/121-service/src/payments/fsp-integration/intersolve-visa/dto/external/contact-information.dto.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/dto/external/personal-data.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/dto/intersolve-visa-do-transfer-or-issue-card.dto.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.controller.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.module.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/repositories/intersolve-visa-customer.scoped.repository.ts
services/121-service/src/registration/registrations.controller.ts
services/121-service/src/registration/registrations.service.ts

Re-implement send updated contact information

---

interfaces/Portal/src/app/components/physical-card-popup/physical-card-popup.component.ts
interfaces/Portal/src/app/services/programs-service-api.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/dto/intersolve-visa-do-transfer-or-issue-card.dto.ts
services/121-service/src/registration/registrations.controller.ts
services/121-service/src/registration/registrations.service.ts
services/121-service/src/registration/repositories/registration-scoped.repository.ts
services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts

Process feedback on re-issue card

---

interfaces/Portal/src/app/components/update-fsp/update-fsp.component.ts

[AB#29083](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29083)

AB#29083 Update fsp enable button

---

interfaces/Portal/src/app/program/program-payout/program-payout.component.html
interfaces/Portal/src/app/program/program-payout/program-payout.component.ts
services/121-service/src/events/events.controller.ts
services/121-service/src/metrics/metrics.service.ts
services/121-service/src/migration/1719931805175-add-new-permission-related-to-export.ts
services/121-service/src/user/enum/permission.enum.ts
services/121-service/test/metrics/export-list.test.ts

Implemented new permission related to export functionality so that each export functionality available based on user's permission.
Task: https://dev.azure.com/redcrossnl/121%20Platform/_workitems/edit/28920

Feat.implement permission based export 28920

---

services/121-service/src/payments/fsp-integration/intersolve-visa/dto/internal/transfer.dto.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/dto/intersolve-visa-do-transfer-or-issue-card.dto.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/programs/repositories/program.repository.ts
services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts

Send references to intersolve

---

services/121-service/src/registration/validators/registrations-input-validator.spec.ts
services/121-service/src/registration/validators/registrations-input-validator.ts

[AB#29057](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29057)

AB#29057 Bulk update bug on dropdown

---

.github/workflows/test_codeql-analysis.yml

ci: Let CodeQL run on every version + schedule

---

.github/workflows/deploy_test_portalicious.yml
interfaces/Portalicious/src/environments/environment.ts
interfaces/Portalicious/src/environments/environment.ts.template.js

See: [AB#29079](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29079)

fix: Use GitHub-environment Variables in Portalicious

---

services/121-service/src/scripts/scripts.controller.ts
services/121-service/src/scripts/scripts.module.ts
services/121-service/src/scripts/scripts.service.ts
services/121-service/src/scripts/seed-mock-helpers.ts
services/121-service/src/scripts/seed-multiple-nlrc-mock.ts
services/121-service/src/scripts/sql/mock-intersolve-voucher.sql
services/121-service/src/scripts/sql/mock-latest-transactions.sql
services/121-service/src/scripts/sql/mock-messages-one-per-registration.sql
services/121-service/src/scripts/sql/mock-messages.sql
services/121-service/src/scripts/sql/mock-payment-transactions.sql
services/121-service/src/scripts/sql/mock-transations-one-per-registrations.sql

Endpoint to duplicate registrations AB#29123

---

CHANGELOG.md

[AB#29118](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29118)

Release v24.7-1

---

services/121-service/src/registration/registrations.controller.ts

Fixed ApiTags for contact-information endpoint

---

interfaces/Portalicious/eslint.config.js
interfaces/Portalicious/package-lock.json
interfaces/Portalicious/package.json
interfaces/Portalicious/src/app/app.component.html
interfaces/Portalicious/src/app/app.component.spec.ts
interfaces/Portalicious/src/app/app.component.ts
interfaces/Portalicious/src/app/app.config.ts
interfaces/Portalicious/src/app/components/health-widget/health-widget.component.html
interfaces/Portalicious/src/app/components/health-widget/health-widget.component.ts
interfaces/Portalicious/src/app/models/health.model.ts
interfaces/Portalicious/src/app/models/user.model.ts
interfaces/Portalicious/src/app/services/api.service.ts
interfaces/Portalicious/src/app/services/http-wrapper.service.ts
interfaces/Portalicious/src/app/utils/dto-type.ts
interfaces/Portalicious/tsconfig.json
services/121-service/package.json
services/121-service/src/app.module.ts
services/121-service/src/config.ts
services/121-service/src/guards/authenticated-user.guard.ts
services/121-service/src/health/health.controller.ts
services/121-service/src/health/health.module.ts
services/121-service/src/registration/registration-data.entity.ts

[AB#28824](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28824)
A lot of the changes here are being carried over from #5486

portalicious: build proof of concept with angular-query-experimental for Portalicious

---

e2e/pages/Payments/PaymentsPage.ts
e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/SendPaymentInstructionsOCW.spec.ts
interfaces/Portal/src/app/program/program-payout/program-payout.component.html

Created the test scripts for the test case to tested the notification is successfully made after the payment is executed.
And other relevant changes happened accordingly.

AB#29045 e2e test #28300

---

e2e/pages/PersonalInformationPopUp/PersonalInformationPopUp.ts
e2e/pages/Table/TableModule.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/SendPaymentInstructionsOCW.spec.ts

Fixes couple of tests that were failing after removing Jumbo  fsp. (OCW test may have been unrelated) please verify that SendPaymentInstructionsOCW.spec.ts works correctly and is not flaky.

Fix failing tests

---

interfaces/Portal/src/app/models/bulk-actions.models.ts

fix: fixed the message template mapping for decline PAs
https://teams.microsoft.com/l/message/19:6cd9736953ee454ca3dbc409b69d8b1a@thread.skype/1719219480338?tenantId=d3ab9790-6ae2-4bd8-aa5e-02864483e7c7&groupId=55f2fa49-7d9b-4c63-b616-b986f3136c3a&parentMessageId=1719219480338&teamName=510%20-%20121%20Platform&channelName=121.Netherlands&createdTime=1719219480338

fix: fixed the message template mapping for decline PAs

---

e2e/tests/121-Portal/MakeNewPayment/OCW/SendPaymentInstructionsOCW.spec.ts

Cosmetic change on a test that was not reporting properly because of wrong id

Change test id

---

services/121-service/src/notifications/whatsapp/whatsapp.service.ts

Fix: parenthesis in Twilio statusCallback

---

e2e/pages/Payments/PaymentsPage.ts
e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/ChangeTransferValueOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/MakeSuccessfulPaymentOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/SendPaymentInstructionsOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/MakeSuccessfulPaymentPV.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityOverviewMessageTab.spec.ts

The messages on the the message history dialog sometimes are different when open it directly after payment, so add a step to refresh the page before open message history.
If the message still not show, open the message history again in the verification function.

try to fix the flaky test

---

services/.env.example
services/121-service/module-dependencies.md
services/121-service/src/financial-service-providers/enum/financial-service-provider-name.enum.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/mappers/intersolve-visa-status.mapper.ts
services/121-service/src/payments/payments.module.ts
services/121-service/src/payments/payments.service.ts
services/121-service/src/registration/registrations.controller.ts
services/121-service/src/registration/registrations.service.ts
services/121-service/src/seed-data/message-template/message-template-nlrc-ocw.json
services/121-service/src/seed-data/mock/visa-card.data.ts
services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
services/121-service/test/helpers/registration.helper.ts
services/121-service/test/payment/do-payment-fsp-visa-debit.test.ts
services/121-service/test/visa-card/block-visa-card.test.ts
services/121-service/test/visa-card/issue-new-card.test.ts
services/121-service/test/visa-card/load-visa-card-details.test.ts

Visa error handling

---

services/121-service/src/payments/payments.service.ts
services/121-service/test/payment/do-payment-fsp-visa-debit.test.ts

AB#29430 throw bad request on missing fsp config

---

e2e/tests/121-Portal/MakeNewPayment/OCW/ViewVisaCardsOCW.spec.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/enums/intersolve-visa-121-error-text.enum.ts
services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
services/121-service/test/helpers/registration.helper.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-error.test.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-retry.test.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-succes.test.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.controller.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts

Additional tests for intersolve do transfer AB#29176

---

services/121-service/src/migrate-visa/migrate-visa.service.ts

AB#29532 Adjust template types for pausing cards

---

services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts

AB#29475 calculate transferamount before storing failed transactions

---

services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/registration/registrations.controller.ts

AB#28897 Seperate permissions pause and unpause

---

interfaces/Portal/src/app/components/physical-card-popup/physical-card-popup.component.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/enums/intersolve-visa-121-error-text.enum.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/enums/wallet-status-121.enum.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa-api.error.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/mappers/intersolve-visa-status.mapper.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/mappers/visa-card-121-status-map.csv
services/121-service/test/visa-card/issue-new-card.test.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.controller.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts

AB#29531 Take into account uncreated debit card

---

services/121-service/src/payments/fsp-integration/intersolve-visa/interfaces/do-transfer-or-issue-card-params.interface.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/interfaces/do-transfer-or-issue-card-return-type.interface.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/payments/payments.service.ts
services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
services/121-service/src/transaction-queues/dto/intersolve-visa-transaction-job.dto.ts
services/121-service/src/transaction-queues/transaction-queues.service.spec.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts

Do transfer in cents AB#29547

---

services/.env.example
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-error.test.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.controller.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts

Api test duplicate operation reference AB#29524

---

k6/models/programs.js

Change request handling and add parseInt

---

interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html

Fixing a regression introduced here: https://github.com/global-121/121-platform/pull/5606/files/9a4cf9cd3e530aa1684c2acf90af60fffc1c0c58#r1705246913ould be in the task on DevOps.

chore: Portalicious: fix css regression

---

.github/workflows/test_k6_cronjob.yml
k6/run-all-tests.sh

[AB#29020](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29020)

chore: add k6 cronjob

---

.github/workflows/deploy_client-demo_portal.yml
.github/workflows/deploy_client-greece_portal.yml
.github/workflows/deploy_client-helpachild_portal.yml
.github/workflows/deploy_client-jrethiopia_portal.yml
.github/workflows/deploy_client-krcs_portal.yml
.github/workflows/deploy_client-nlrc_portal.yml
.github/workflows/deploy_client-southafrica_portal.yml
.github/workflows/deploy_client-training_portal.yml
.github/workflows/deploy_client-zambia_portal.yml
.github/workflows/deploy_client-zimbabwe_portal.yml
.github/workflows/deploy_staging_portal.yml
.github/workflows/deploy_test_portal.yml

See [AB#29539](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29539)

feat: Make enabled languages configurable from GitHub-Environments, instead of in-code

---

services/121-service/package-lock.json
services/121-service/package.json

No idea why this is necessary now tbh - probably due to some of the recent depenabot updates. It seems to fix the test env.

chore: fix issues on test env

---

e2e/test-registration-data/test-registrations-patch-OCW.csv
e2e/tests/121-Portal/MakeNewPayment/OCW/ExportCardDataOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/ReIssueCardOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/RetryPaymentOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/SendPaymentInstructionsOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/OCW/ViewVisaCardsOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/PauseCardPV.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/ReIssueCardPV.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewPersonalInformationTable.spec.ts
e2e/tests/121-Portal/ViewPaProfilePage/ViewVisaDebitCardsTable.spec.ts
services/121-service/test/metrics/export-list.test.ts
services/121-service/test/registrations/pagination/pagination-data.ts

Fixes broken e2e tests for visa intersolve reimplementation

Fix.broken e2e tests

---

interfaces/Portalicious/eslint.config.js
interfaces/Portalicious/src/app/components/form-error/form-error.component.html
interfaces/Portalicious/src/app/components/form-error/form-error.component.ts
interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.html
interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.ts
interfaces/Portalicious/src/app/components/form/components/form-base/form-base.component.ts
interfaces/Portalicious/src/app/components/form/form-default.component.html
interfaces/Portalicious/src/app/components/form/form-default.component.ts
interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
interfaces/Portalicious/src/app/components/form/form-sidebar.component.ts
interfaces/Portalicious/src/app/components/logo/logo.component.html
interfaces/Portalicious/src/app/components/page-layout/components/footer/footer.component.html
interfaces/Portalicious/src/app/pages/change-password/change-password.component.html
interfaces/Portalicious/src/app/pages/change-password/change-password.component.ts
interfaces/Portalicious/src/app/pages/login/login.component.html
interfaces/Portalicious/src/app/pages/login/login.component.ts
interfaces/Portalicious/src/app/pages/projects-overview/create-project-button/create-project-button.component.html
interfaces/Portalicious/src/app/pages/projects-overview/create-project-button/create-project-button.component.ts
interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.component.html
interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.component.ts
interfaces/Portalicious/src/app/services/api.service.ts
interfaces/Portalicious/src/app/services/auth.service.ts
interfaces/Portalicious/src/app/services/http-wrapper.service.ts
interfaces/Portalicious/src/app/utils/form-validation.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/src/styles.scss

This is an alternative approach to what I had tried in #5658
I prefer this approach better now that I've fleshed it out. I think it's the right balance between reducing duplication, and flexibility.
More details in the comments.

portalicious: another approach to forms

---

services/121-service/test/helpers/assert.helper.ts
services/121-service/test/helpers/utility.helper.ts
services/121-service/test/program/__snapshots__/create-fsp-configuration.test.ts.snap
services/121-service/test/program/__snapshots__/create-program.test.ts.snap
services/121-service/test/program/create-fsp-configuration.test.ts
services/121-service/test/program/create-program.test.ts
services/121-service/test/program/update-program.test.ts

Who knows that this might actually fix the flakiness of these tests once and for all. One can only hope.

chore: refactor create-program tests

---

interfaces/Portal/src/app/models/import-type.enum.ts
interfaces/Portal/src/app/program/import-fsp-reconciliation/import-fsp-reconciliation.component.ts
interfaces/Portal/src/app/services/programs-service-api.service.ts
interfaces/Portal/src/app/shared/file-picker-prompt/file-picker-prompt.component.html
interfaces/Portal/src/app/shared/file-picker-prompt/file-picker-prompt.component.ts
services/121-service/src/payments/payments.controller.ts
services/121-service/src/payments/payments.service.ts
services/121-service/test/helpers/registration.helper.ts
services/121-service/test/payment/__snapshots__/do-payment-fsp-excel.test.ts.snap
services/121-service/test/payment/do-payment-fsp-excel.test.ts

Feat.create template for reconciliation import with generic fsp

---

interfaces/Portalicious/src/app/components/logo/logo.component.ts
interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.ts
interfaces/Portalicious/src/app/components/page-layout/components/project-header/project-header.component.ts
interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
interfaces/Portalicious/src/app/components/page-layout/page-layout.component.ts
interfaces/Portalicious/src/app/pages/change-password/change-password.component.html
interfaces/Portalicious/src/app/pages/project/project-overview/project-overview.component.html
interfaces/Portalicious/src/app/pages/project/project-overview/project-overview.component.ts
interfaces/Portalicious/src/app/pages/project/project-payments/project-payments.component.html
interfaces/Portalicious/src/app/pages/project/project-payments/project-payments.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.component.html
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.component.ts
interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.html
interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.ts
interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.component.html
interfaces/Portalicious/src/app/pages/roles-and-permissions/roles-and-permissions.component.html
interfaces/Portalicious/src/app/pages/users/users.component.html
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#29740](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29740)
Pulled a small refactor out of #5693 in order to make that a bit easier to review. I'm doing this in order to make the layout more consistent, and to avoid the duplication of tailwind classes.

portalicious: consistent page title

---

e2e/tests/121-Portal/MakeNewPayment/OCW/RetryPaymentOCW.spec.ts
e2e/tests/121-Portal/MakeNewPayment/PV/RetryPaymentPV.spec.ts
services/121-service/src/registration/dto/registration-update-job.dto.ts
services/121-service/src/registration/processsors/registrations-update.processor.ts
services/121-service/src/registration/registrations.controller.ts
services/121-service/src/registration/registrations.service.ts
services/121-service/src/registration/services/registrations-import.service.ts
services/121-service/src/shared/file-upload-api-format.ts
services/121-service/test/helpers/registration.helper.ts
services/121-service/test/registrations/mass-update-registration.test.ts

feat: add reason to body when mass updating AB#29618

---

services/121-service/src/programs/programs.service.ts

Fix: use budget in Create Program endpoint

---

interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
interfaces/Portalicious/src/app/components/page-layout/page-layout.component.ts
interfaces/Portalicious/src/app/pages/change-password/change-password.component.html
interfaces/Portalicious/src/app/pages/project/project-overview/project-overview.component.html
interfaces/Portalicious/src/app/pages/project/project-payments/project-payments.component.html
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.component.html
interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.html
interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.component.html
interfaces/Portalicious/src/app/pages/roles-and-permissions/roles-and-permissions.component.html
interfaces/Portalicious/src/app/pages/users/users.component.html

[AB#29765](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29765)
note to self: do not use "title" as a component attribute that wraps the whole page

portalicious: fix: all page content has a tooltip

---

.github/workflows/test_e2e_portalicious.yml
e2e/portalicious/pages/BasePage.ts
e2e/portalicious/pages/CreateProjectPage.ts
e2e/portalicious/tests/CreateNewProject/CreateNewProjectSuccessfully.spec.ts
e2e/portalicious/tests/CreateNewProject/FillInInvalidToken.spec.ts
e2e/portalicious/tests/CreateNewProject/SaveEmptyForm.spec.ts
e2e/tsconfig.json
services/.env.example

Adds "create new Project" tests for Portalicious

Add create new Project e2e tests for Portalicious

---

interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.html
interfaces/Portalicious/src/app/components/form/form-default.component.html
interfaces/Portalicious/src/app/pages/change-password/change-password.component.html
interfaces/Portalicious/src/app/pages/change-password/change-password.component.ts

[AB#29768](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29768)
LPT: I recommend disabling whitespace while reviewing this one:

portalicious: align styling of change-password

---

services/121-service/module-dependencies.md
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.module.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/programs/programs.controller.ts
services/121-service/src/programs/programs.module.ts
services/121-service/src/programs/programs.service.ts

Add endpoint for funding wallet info

---

interfaces/Portalicious/src/app/components/form-error/form-error.component.html
interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
interfaces/Portalicious/src/app/components/form/form-sidebar.component.ts
interfaces/Portalicious/src/app/components/logo/logo.component.html
interfaces/Portalicious/src/app/components/page-layout/components/footer/footer.component.html
interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
interfaces/Portalicious/src/app/components/skeleton-inline/skeleton-inline.component.html
interfaces/Portalicious/src/app/components/skeleton-inline/skeleton-inline.component.ts
interfaces/Portalicious/src/app/pages/login/components/cookie-banner/cookie-banner.component.html
interfaces/Portalicious/src/app/pages/login/login.component.html
interfaces/Portalicious/src/app/pages/projects-overview/create-project-button/create-project-button.component.html
interfaces/Portalicious/src/app/pages/projects-overview/project-metric-container/project-metric-container.component.html
interfaces/Portalicious/src/app/pages/projects-overview/project-metric-container/project-metric-container.component.ts
interfaces/Portalicious/src/app/pages/projects-overview/project-summary-card/project-summary-card.component.html
interfaces/Portalicious/src/app/pages/projects-overview/project-summary-card/project-summary-card.component.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/src/styles.scss
interfaces/Portalicious/tailwind.config.ts

[AB#29808](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29808)

portalicious: add typography utilities

---

interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts

[AB#29766](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29766)

portalicious: context menu alignment fix

---

interfaces/Portalicious/src/app/models/project.model.ts
interfaces/Portalicious/src/app/pages/projects-overview/project-summary-card/project-summary-card.component.html
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#29870](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29870)
[AB#29871](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29871)

portalicious: update copy on project summary cards

---

interfaces/Portalicious/package-lock.json
interfaces/Portalicious/package.json
interfaces/Portalicious/src/app/components/health-widget/health-widget.component.ts
interfaces/Portalicious/src/app/components/logo/logo.component.ts
interfaces/Portalicious/src/app/models/project.model.ts
interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.ts
interfaces/Portalicious/src/app/pages/projects-overview/project-summary-card/project-summary-card.component.ts
interfaces/Portalicious/src/app/services/api.service.ts

[AB#29821](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29821)

portalicious: refactor query keys

---

services/121-service/src/user/user.entity.ts
services/121-service/src/user/user.interface.ts
services/121-service/src/user/user.service.ts

[AB#29966](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29966)

feat: add displayName and isOrganizationAdmin in get endpoints AB#29966

---

interfaces/Portalicious/eslint.config.js
interfaces/Portalicious/package-lock.json
interfaces/Portalicious/package.json
interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.html
interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
interfaces/Portalicious/src/app/components/form/form-sidebar.component.ts
interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
interfaces/Portalicious/src/app/domains/project/project.api.service.ts
interfaces/Portalicious/src/app/domains/project/project.model.ts
interfaces/Portalicious/src/app/domains/role/role.api.service.ts
interfaces/Portalicious/src/app/domains/role/role.model.ts
interfaces/Portalicious/src/app/domains/user/user.api.service.ts
interfaces/Portalicious/src/app/pages/login/login.component.html
interfaces/Portalicious/src/app/pages/project/project-team/add-user-button/add-user-button.component.html
interfaces/Portalicious/src/app/pages/project/project-team/add-user-button/add-user-button.component.ts
interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.html
interfaces/Portalicious/src/app/pages/projects-overview/create-project-button/create-project-button.component.html
interfaces/Portalicious/src/app/services/auth.service.ts
interfaces/Portalicious/src/app/services/http-wrapper.service.ts
interfaces/Portalicious/src/app/services/toast.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/src/styles.scss
interfaces/Portalicious/tailwind.config.ts

[AB#29678](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29678)

Portalicious: add new team member form AB#29678

---

README.md

[AB#30012](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30012)

chore: update release checklist

---

services/121-service/src/migration/1724754547895-modify-safaricom-requests-table.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom-request.entity.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom-transfer.entity.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.module.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.ts
services/121-service/src/registration/registrations.module.ts
services/121-service/src/registration/services/registrations-bulk.service.ts
services/121-service/src/scoped.repository.ts

[AB#29906](https://dev.azure.com/redcrossnl/121%20Platform/_workitems/edit/29906)
Added a new migration script to drop un-necessary columns from `safaricom_requests` database table and keep only the required columns with renamed column names according to [this miro board](https://miro.com/app/board/uXjVKzM7CFE=/)

feat: add the migration script to update safaricom_requests database table

---

.github/actions/build-interface/action.yml
interfaces/Portal/src/logout/index.html
interfaces/Portal/src/logout/logout.js
interfaces/Portal/staticwebapp.config.json

[AB#30019](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30019)

feat: Add logout escape-hatch for (SSO→login issues

---

services/121-service/src/migrate-visa/migrate-visa.controller.ts
services/121-service/src/migrate-visa/migrate-visa.service.ts

Improvements Visa migration endpoint

---

interfaces/Portal/src/app/pages/login/login.page.html
interfaces/Portal/src/app/pages/login/login.page.ts
interfaces/Portal/src/assets/i18n/en.json
interfaces/Portal/src/assets/i18n/nl.json
interfaces/Portal/src/logout/logout.js

[AB#30024](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30024)

feat: Add error-notice + manual trigger to force-logout from within iframe

---

.github/workflows/deploy_test_portal.yml
.github/workflows/deploy_test_portalicious.yml
.github/workflows/test_pull_request_formatting.yml

[AB#30070](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30070)

chore: make sure PRs have the right required checks

---

services/121-service/src/notifications/processors/message-status-callback.processor.ts
services/121-service/test/helpers/program.helper.ts
services/121-service/test/payment/do-payment-fsp-voucher.test.ts
services/121-service/test/registrations/pagination/send-message.test.ts
services/121-service/test/registrations/send-message-with-placeholder.test.ts
services/121-service/test/registrations/send-templated-message.test.ts
services/mock-service/src/twilio/twilio.controller.ts
services/mock-service/src/twilio/twilio.service.ts

[AB#30014](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30014)

chore: fix flaky send message test

---

services/121-service/test/payment/do-payment-filter.test.ts

[AB#30068](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30068)
Fix do-payment-filter API-test

fix: do-payment-filter api test AB#30068

---

e2e/README.md
e2e/portalicious/tests/LogOut/LogOut.spec.ts
interfaces/Portal/src/logout/logout.js
interfaces/Portalicious/src/logout/logout.js

+ tweak timeout to prevent logout not finishing fully
[AB#30069](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30069)
The test is now actually proving it works. (Before it was also passing when the code didn't run successfully...)

test: Focus testing on actual URLs only

---

interfaces/Portalicious/src/app/app.routes.ts
interfaces/Portalicious/src/app/domains/domain-api.service.ts
interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
interfaces/Portalicious/src/app/domains/payment/payment.model.ts
interfaces/Portalicious/src/app/domains/project/project.model.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.model.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.component.html
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.component.ts
interfaces/Portalicious/src/app/services/http-wrapper.service.ts
services/121-service/src/registration/dto/mapped-paginated-registration.dto.ts
services/121-service/src/registration/registrations.controller.ts
services/121-service/src/registration/registrations.service.ts
services/121-service/src/registration/services/registrations-pagination.service.ts

[AB#30126](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30126)

chore: add findOne endpoint to be used in portalicious

---

services/121-service/src/payments/fsp-integration/intersolve-visa/enums/intersolve-visa-121-error-text.enum.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
services/121-service/src/shared/services/custom-http.service.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-error.test.ts

[AB#30164](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30164)
This is an implementation based on this comment:
https://github.com/global-121/121-platform/pull/5347#discussion_r1736580581

refactor: intersolve visa api service

---

interfaces/Portalicious/package.json

[AB#30221](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30221)
Use a Windows-compatible command to create the empty file...

fix: Add cross-platform command to build-script

---

e2e/portalicious/tests/CreateNewProject/CreateNewProjectSuccessfully.spec.ts
e2e/portalicious/tests/CreateNewProject/FillInInvalidToken.spec.ts

[AB#30220](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30220)
(Temporarily?) Disable testing of third-party APIs.

fix: Stop testing Third-Party API in CI-tests

---

services/121-service/src/migration/1724754547895-modify-safaricom-requests-table.ts
services/121-service/src/payments/fsp-integration/safaricom/entities/safaricom-transfer.entity.ts
services/121-service/src/payments/fsp-integration/safaricom/interfaces/safaricom-transfer-response.interface.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom-api.error.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.api.service.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.ts
services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
services/mock-service/src/fsp-integration/safaricom/safaricom.mock.service.ts

[AB#30156](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30156)
[AB#30214](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30214)
Encapsulates all Safaricom's API into SafaricomApiService and some improvements based on PR review

fix: SafaricomApiService encapsulates all Safaricom's API and some improvements based on PR review

---

e2e/portalicious/pages/ProjectTeam.ts
e2e/portalicious/tests/ManageTeam/ScopeVisibleOnlyWhenSetToTrue.spec.ts

[AB#30159](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30159) 
Test is based on programs' configuration nlrc-multiple where one of the program's has scope set to true and the other to false.

E2E test Scope visible hidden

---

interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.html
interfaces/Portalicious/src/app/components/form/form-default.component.html
interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
interfaces/Portalicious/src/app/components/page-layout/components/registration-header/add-note-form/add-note-form.component.html
interfaces/Portalicious/src/app/components/page-layout/components/registration-header/add-note-form/add-note-form.component.ts
interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.html
interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.ts
interfaces/Portalicious/src/app/domains/project/project.api.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/src/styles.scss

[AB#29983](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29983)

portalicious: add note form

---

.github/workflows/test_e2e_portalicious.yml
e2e/portalicious/tests/CreateNewProject/CreateNewProjectSuccessfully.spec.ts
e2e/portalicious/tests/CreateNewProject/FillInInvalidToken.spec.ts
services/.env.example

[AB#30220](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30220)

ci: Make disabled tests more explicit AB#30220

---

.github/workflows/deploy_client-krcs-training_all.yml
.github/workflows/deploy_client-krcs-training_portal.yml
.github/workflows/deploy_client-krcs-training_service.yml

[AB#30273](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30273)

feat: Add new instance's deployment workflows

---

features/121-Portal/Make_new_payment.feature
services/121-service/src/payments/fsp-integration/safaricom/interfaces/safaricom-transfer-response.interface.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.api.service.ts
services/121-service/src/payments/payments.service.ts
services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts
services/121-service/src/transaction-queues/dto/safaricom-transaction-job.dto.ts
services/121-service/src/transaction-queues/transaction-queues.service.spec.ts
services/121-service/src/utils/formatDate.ts
services/mock-service/src/fsp-integration/safaricom/safaricom.dto.ts
services/mock-service/src/fsp-integration/safaricom/safaricom.mock.service.ts

[AB#30240](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30240)
fix: moved originatorConversationID to payment service and handler error response

fix: moved originatorConversationID to payment service and handler error response

---

features/121-Portal/Make_new_payment.feature
services/121-service/src/financial-service-provider-callback-job-processors/financial-service-provider-callback-job-processors.module.ts
services/121-service/src/financial-service-provider-callback-job-processors/financial-service-provider-callback-job-processors.service.ts
services/121-service/src/financial-service-provider-callback-job-processors/processors/safaricom-timeout-callback-job.processor.ts
services/121-service/src/payments/fsp-integration/safaricom/dtos/safaricom-transfer-timeout-callback-job.dto.ts
services/121-service/src/payments/fsp-integration/safaricom/dtos/safaricom-transfer-timeout-callback.dto.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.controller.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.module.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.spec.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.ts
services/121-service/src/shared/enum/financial-service-provider-callback-queue-names.enum.ts
services/121-service/src/shared/enum/payment-queue-names.enum.ts
services/mock-service/src/config.ts
services/mock-service/src/fsp-integration/safaricom/safaricom.mock.service.ts

[AB#30017](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30017)
[AB#30337](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30337)
- Implemented Safaricom timeout callback
- Added phone number 254000000002 in mock service for time out callback for safaricom payments

Feat.implement timeout callback

---

services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts

[AB#30339](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30339)

Do not await cache voucher AB#30339

---

services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
services/121-service/test/registrations/send-message-with-placeholder.test.ts

[AB#30339](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30339)

Fix test and cache vouchers

---

services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.spec.ts
services/121-service/test/payment/do-payment-safaricom.test.ts

[AB#30346](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30346)
Added API test case for handle timeout callback for safaricom payment and added few more unit test cases for safaricom service

fix: Added API test and few more unit tests

---

services/121-service/src/transaction-job-processors/transaction-job-processors.service.spec.ts

[AB#30341](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30341)
feat: added unit tests for processSafaricomTransactionJob to test safaricom idempotency case

feat: added unit tests for processSafaricomTransactionJob AB#30341

---

services/.env.example
services/docker-compose.development.yml

[AB#30396](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30396)
Replace window-user specific start-up command by generic via env-variable.

fix: windows specific startup cmd AB#30396

---

interfaces/Portal/src/app/services/programs-service-api.service.ts
services/121-service/src/registration/registrations.controller.ts
services/121-service/test/helpers/registration.helper.ts

[AB#30455](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30455)

Make endpoints more consistent

---

interfaces/Portalicious/src/app/pages/project/project-monitoring/metric-tile/metric-tile.component.html
interfaces/Portalicious/tailwind.config.ts

[AB#30476](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30476)

portalicious: rename typography utility

---

.github/workflows/test_interface_portalicious.yml
interfaces/Portalicious/tailwind.config.ts

[AB#30479](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30479)

portalicious: add typecheck in CI

---

services/121-service/src/payments/fsp-integration/safaricom/interfaces/do-transfer-return-type.interface.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.api.service.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.spec.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.ts

[AB#30516](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30516)
Resolves final PR comments about
- not passing through interfaces across multiple methods
- only returning relevant data, via return type interface

fix: do not pass through interface + return relevant object only

---

services/121-service/src/registration/services/registrations-pagination.service.ts
services/121-service/src/registration/validators/registrations-input-validator.ts

[AB#30520](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30520)

fix: filter on referenceId consisting of numbers

---

interfaces/Portalicious/src/app/components/form-error/form-error.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
interfaces/Portalicious/src/app/components/query-table/table-cell/table-cell-chip.component.ts
interfaces/Portalicious/src/app/components/query-table/table-cell/table-cell-date.component.ts
interfaces/Portalicious/src/app/components/query-table/table-cell/table-cell-text.component.ts
interfaces/Portalicious/src/app/components/query-table/table-cell/table-cell.component.ts
interfaces/Portalicious/src/app/domains/project/project.api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.model.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/activity-log-voucher-dialog/activity-log-voucher-dialog.component.html
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/activity-log-voucher-dialog/activity-log-voucher-dialog.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/table-cell-activity.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/table-cell-overview.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/project-registration-activity-log.page.html
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/project-registration-activity-log.page.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#30270](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30270)

portalicious: open AH voucher

---

e2e/portalicious/pages/ProjectMonitoringPage.ts
e2e/portalicious/tests/ProjectMonitoring/AllElementsOfProjectMonitoringPageDisplayCorrectData.spec.ts
interfaces/Portalicious/src/app/pages/project/project-monitoring/metric-tile/metric-tile.component.html
interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.page.html

[AB#30324](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30324) 
E2E tests that validates elements present on the "Monitoring" page as well as values displayed in cards for Registration and Inclusion
Out of scope:
Iframe cannot be tested for now since there are no elements with any text to be asserted. Same time isVisible() & isHidden() method always returns true on this page.

Add E2E tests for "Project monitoring page"

---

e2e/portalicious/pages/ProjectMonitoringPage.ts
e2e/portalicious/tests/ProjectMonitoring/AllElementsOfProjectMonitoringPageDisplayCorrectData.spec.ts
interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.page.html

[AB#30569](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30569)

portalicious: test iframe on monitoring page

---

interfaces/Portalicious/src/app/components/colored-chip/colored-chip.helper.ts
interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.html
interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
interfaces/Portalicious/src/app/components/data-list/data-list.component.html
interfaces/Portalicious/src/app/domains/domain-api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
interfaces/Portalicious/src/app/domains/registration/registration.model.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-debit-cards/project-registration-debit-cards.page.html
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-debit-cards/project-registration-debit-cards.page.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#29986](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29986)

Debit cards (page) in profile page (on main)

---

.github/release.yml
.github/workflows/test_pull_request_formatting.yml
docs/CONTRIBUTING.md

[AB#30592](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30592)

chore: add "other" label to PR release notes

---

services/121-service/src/metrics/metrics.module.ts
services/121-service/src/metrics/metrics.service.ts
services/121-service/src/shared/types/entity-class.type.ts
services/121-service/src/transaction-job-processors/processors/transaction-job-intersolve-visa.processor.ts

[AB#30531](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30531)
- Export mpesaTransactionId in payment report
- Set this up in a generic/reusable way by pulling back in the code that was recently removed [here](https://github.com/global-121/121-platform/pull/5856/files#diff-05de22ac6e0c490e21ad73e8d00c3819064e13652fb6648078abfe08064de8f4).

Feat.export mpesa transaction

---

services/121-service/src/migration/1669718138929-remove-RegistrationPersonalSEARCH.ts
services/121-service/src/migration/1681916727770-permission-read-aidworkers.ts
services/121-service/src/migration/1694821278357-add-paused-status.ts
services/121-service/src/migration/1707311790028-remove-select-for-validation.ts
services/121-service/src/migration/1719931805175-add-new-permission-related-to-export.ts
services/121-service/src/migration/1727853835967-role-description.ts
services/121-service/src/user/dto/create-user-role.dto.ts
services/121-service/src/user/dto/update-user-role.dto.ts
services/121-service/src/user/dto/user-role.dto.ts
services/121-service/src/user/dto/userrole-response.dto.ts
services/121-service/src/user/user-role.entity.ts
services/121-service/src/user/user.controller.ts
services/121-service/src/user/user.service.ts
services/121-service/test/helpers/utility.helper.ts
services/121-service/test/users/user-roles.test.ts

[AB#30596](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30596)

enhancement: add description to roles

---

.github/workflows/deploy_client-ethiopia_all.yml
.github/workflows/deploy_client-ethiopia_portal.yml
.github/workflows/deploy_client-ethiopia_service.yml

[AB#30619](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30619)
New instance!

feat: Add deployment workflow for new instance: Ethiopia

---

services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/registration/registrations.service.ts
services/121-service/src/transaction-queues/dto/intersolve-visa-transaction-job.dto.ts
services/121-service/test/visa-card/issue-new-card.test.ts

[AB#30297](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30297)
Small improvements.

Visa chores, comments and small refactors

---

interfaces/Portalicious/src/app/components/colored-chip/colored-chip.helper.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
interfaces/Portalicious/src/app/domains/registration/registration.model.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-debit-cards/project-registration-debit-cards.page.ts

[AB#30525](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30525)

portalicious: replace debit cards mock

---

e2e/tests/121-Portal/ViewPaProfilePage/ViewActivityFspOverview.spec.ts
interfaces/Portalicious/src/app/components/colored-chip/colored-chip.helper.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.model.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/table-cell-overview.component.ts
services/121-service/src/metrics/metrics.service.ts
services/121-service/src/notifications/message.service.spec.ts
services/121-service/src/notifications/message.service.ts
services/121-service/src/payments/dto/import-fsp-reconciliation.dto.ts
services/121-service/src/payments/dto/payment-transaction-result.dto.ts
services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
services/121-service/src/payments/fsp-integration/excel/excel.service.spec.ts
services/121-service/src/payments/fsp-integration/excel/excel.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.ts
services/121-service/src/payments/fsp-integration/vodacash/vodacash.service.ts
services/121-service/src/payments/payments.service.ts
services/121-service/src/payments/transactions/dto/get-transaction.dto.ts
services/121-service/src/payments/transactions/enums/transaction-status.enum.ts
services/121-service/src/payments/transactions/transactions.service.ts
services/121-service/src/registration/services/registrations-pagination.service.ts
services/121-service/test/helpers/program.helper.ts
services/121-service/test/payment/do-payment-fsp-excel.test.ts
services/121-service/test/payment/do-payment-fsp-visa-debit.test.ts
services/121-service/test/payment/do-payment-fsp-voucher.test.ts
services/121-service/test/payment/do-payment-safaricom.test.ts
services/121-service/test/payment/payment-count-completed.test.ts
services/121-service/test/registrations/pagination/filter-registration.payment.test.ts

[AB#30662](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30662)

chore: rename StatusEnum to TransactionStatusEnum

---

services/.env.example
services/121-service/src/cronjob/cronjob.service.ts

[AB#24803](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/24803)
Make cron-jobs configurable per instance (off by default)

feat: Make cron-jobs configurable per instance AB#24803

---

services/121-service/src/user/dto/update-user.dto.ts
services/121-service/src/user/user.controller.ts

[AB#30709](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30709)
add displayname to patch /api/users/(userId}

add displayname to patch /api/users/(userId}

---

services/121-service/src/activities/dtos/activities.dto.ts
services/121-service/src/events/events.service.spec.ts
services/121-service/src/scoped.repository.spec.ts
services/121-service/src/utils/unit-test.helpers.ts

[AB#30729](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30729)

activities: fix unit tests

---

interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts

[AB#30603](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30603)

portalicious: global filter redesign

---

interfaces/Portalicious/src/app/domains/user/user.api.service.ts
interfaces/Portalicious/src/app/pages/users/add-user-form/add-user-form.component.html
interfaces/Portalicious/src/app/pages/users/add-user-form/add-user-form.component.ts
interfaces/Portalicious/src/app/pages/users/users.page.html
interfaces/Portalicious/src/app/pages/users/users.page.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#30597](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30597) [AB#30598](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30598)

portalicious: add/edit user form AB#30597 AB#30598

---

services/121-service/src/registration/registrations.service.ts

[AB#30731](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30731)
Blocks updating of referenceId, which was previously partly possible (update succeeded, but later on failed with 500 error on recalculating inclusion score)

feat: block updating of refenceId AB#30731

---

services/121-service/src/notifications/message-incoming/message-incoming.service.ts

[AB#30754](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30754)
- Ensured the sending of vouchers as reply also uses the fallback language

Fix.voucher template fallback language

---

interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
interfaces/Portalicious/src/app/pages/login/login.page.html
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/project-registration-activity-log.page.html
interfaces/Portalicious/src/app/pages/project/project-team/project-team.page.html
interfaces/Portalicious/src/app/pages/user-roles/user-roles.page.html
interfaces/Portalicious/src/app/pages/user-roles/user-roles.page.ts
interfaces/Portalicious/src/app/pages/users/add-user-form/add-user-form.component.html
interfaces/Portalicious/src/app/pages/users/users.page.html
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/src/styles.scss
interfaces/Portalicious/tailwind.config.ts

[AB#30630](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30630)

portalicious: user & roles review

---

services/121-service/src/notifications/README.md
services/121-service/src/notifications/auth.middlewareTwilio.ts
services/121-service/src/notifications/sms/sms.service.ts
services/121-service/src/notifications/twilio.client.ts
services/121-service/src/notifications/twilio.entity.ts
services/121-service/src/notifications/whatsapp/whatsapp.service.ts
services/121-service/src/payments/fsp-integration/intersolve-voucher/README.md

[AB#30733](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30733)
I've refactored all of the code that is somehow involved with the Twilio client and did not take advantage of the typings we get from it out of the box.
The problem is that I don't know how to test any of this code, nor is any of it covered by integration tests. I would happily add integration tests where applicable, but I'm not sure where to start.

chore: refactor twilio code to not rely on "any"

---

interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
interfaces/Portalicious/src/app/domains/payment/payment.model.ts
interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.page.html
interfaces/Portalicious/src/app/pages/project/project-monitoring/project-monitoring.page.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#30715](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30715)

portalicious: add total amount in last payment to project monitoring

---

interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.page.html
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.page.ts
interfaces/Portalicious/src/app/services/paginate-query.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#30738](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30738)

portalicious: enable selection on table

---

interfaces/Portalicious/src/app/components/colored-chip/colored-chip.helper.ts
interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
interfaces/Portalicious/src/app/domains/message/message.helper.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
interfaces/Portalicious/src/app/domains/registration/registration.model.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/table-cell-activity.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/components/table-cell-overview.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/project-registration-activity-log.page.html
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-activity-log/project-registration-activity-log.page.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
services/121-service/src/activities/interfaces/message-activity.interface.ts

[AB#29984](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29984)
This is preliminary work. Doing this "properly" also requires us to have figured out what we're going to do with attributes and will be completed in [AB#30584](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30584)

portalicious: use activities endpoint

---

interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.page.html
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.page.ts
interfaces/Portalicious/src/app/services/auth.service.ts

[AB#30737](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30737)

Show "send message" action

---

interfaces/Portalicious/eslint.config.js
interfaces/Portalicious/src/app/domains/notification/notification.api.service.ts
interfaces/Portalicious/src/app/domains/notification/notification.helper.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/components/custom-message-control/custom-message-control.component.html
interfaces/Portalicious/src/app/pages/project/project-registrations/components/custom-message-control/custom-message-control.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/components/custom-message-preview/custom-message-preview.component.html
interfaces/Portalicious/src/app/pages/project/project-registrations/components/custom-message-preview/custom-message-preview.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/components/send-message-dialog/send-message-dialog.component.html
interfaces/Portalicious/src/app/pages/project/project-registrations/components/send-message-dialog/send-message-dialog.component.ts
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.page.html
interfaces/Portalicious/src/app/pages/project/project-registrations/project-registrations.page.ts
interfaces/Portalicious/src/app/services/paginate-query.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#30742](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30742)

portalicious: custom message popup

---

interfaces/Portalicious/src/app/pages/project-monitoring/project-monitoring.page.ts
services/121-service/src/payments/payments.service.ts

[AB#30842](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30842)

portalicious: fix last payment amount

---

interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#30836](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30836)

portalicious: show buttons for status changes

---

services/121-service/src/activities/activities.controller.ts
services/121-service/src/activities/dtos/activities.dto.ts

[AB#30441](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30441)

Add examples to swagger for Activities

---

interfaces/Portalicious/package-lock.json
interfaces/Portalicious/package.json
interfaces/Portalicious/src/app/app.config.ts
interfaces/Portalicious/src/app/components/form/form.component.ts
interfaces/Portalicious/src/app/components/page-layout/components/registration-header/add-note-form/add-note-form.component.ts
interfaces/Portalicious/src/app/domains/notification/notification.api.service.ts
interfaces/Portalicious/src/app/domains/notification/notification.model.ts
interfaces/Portalicious/src/app/domains/project/project.api.service.ts
interfaces/Portalicious/src/app/domains/project/project.helper.ts
interfaces/Portalicious/src/app/domains/project/project.model.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.model.ts
interfaces/Portalicious/src/app/pages/change-password/change-password.page.ts
interfaces/Portalicious/src/app/pages/login/login.page.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/custom-message-control/custom-message-control.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/custom-message-control/custom-message-control.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/custom-message-preview/custom-message-preview.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/custom-message-preview/custom-message-preview.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
interfaces/Portalicious/src/app/pages/projects-overview/components/create-project-form/create-project-form.component.ts
interfaces/Portalicious/src/app/services/messaging.service.ts
interfaces/Portalicious/src/app/services/translatable-string.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/src/styles.scss

[AB#30847](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30847)

portalicious: custom messaging components

---

e2e/package-lock.json
e2e/package.json
e2e/portalicious/pages/UsersPage.ts
e2e/portalicious/tests/Users/UsersLastLogin.spec.ts
e2e/portalicious/tests/Users/ViewUsersPage.spec.ts

[AB#30874](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30874) 
Adds test that asserts login time stamps in Users page

Add e2e test for User's last login

---

.github/dependabot.yml

[AB#30853](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30853)

chore: Group SSO-related packages together

---

services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
services/121-service/src/registration/registrations.service.ts
services/121-service/test/visa-card/issue-new-card.test.ts

[AB#30852](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30852)

Small fixes visa reissue card

---

.github/dependabot.yml
services/121-service/package-lock.json
services/121-service/package.json
services/121-service/src/app.module.ts
services/121-service/src/config.ts
services/121-service/src/user/user.controller.ts

[AB#30844](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30844)

chore: Upgrade @nestjs/throttler with new config-format

---

interfaces/Portalicious/src/app/pages/project-registrations/components/custom-message-preview/custom-message-preview.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
interfaces/Portalicious/src/app/services/messaging.service.ts
interfaces/Portalicious/src/app/services/paginate-query.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#30856](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30856)

portalicious: context menu on registrations page

---

interfaces/Portalicious/src/app/pages/project-payments/project-payments.page.html
interfaces/Portalicious/src/app/pages/project-payments/project-payments.page.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#30872](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30872)

portalicious: create payment button

---

e2e/portalicious/tests/Users/UsersLastLogin.spec.ts

[AB#31106](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31106)

portalicious: fix user last login E2E test

---

interfaces/Portalicious/src/app/components/button-menu/button-menu.component.html
interfaces/Portalicious/src/app/components/button-menu/button-menu.component.ts
interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.ts
services/121-service/package.json

[AB#31040](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31040)

portalicious: button menu component

---

interfaces/Portalicious/src/app/domains/payment/payment.helpers.ts
interfaces/Portalicious/src/app/domains/project/project.helper.ts
interfaces/Portalicious/src/app/pages/project-payments/components/export-payments/export-payments.component.html
interfaces/Portalicious/src/app/pages/project-payments/components/export-payments/export-payments.component.ts
interfaces/Portalicious/src/app/pages/project-payments/project-payments.page.html
interfaces/Portalicious/src/app/pages/project-payments/project-payments.page.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#30871](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30871)

portalicious: payment exports

---

services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
services/121-service/test/commercial-bank-ethiopia/export-validation-report.test.ts
services/121-service/test/payment/do-payment-commercial-bank-ethiopia.test.ts
services/121-service/test/registrations/pagination/pagination-data.ts

[AB#30433](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30433) 
- @jannisvisser Do you think this work should also include making a mock service for CBE?
- Potentially we could also do that work from main

Fix bug in cbe query & added api test

---

services/121-service/src/migrate-visa/migrate-visa.service.ts

[AB#31049](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31049) 
A few changes from things encountered during test with production data.

fix some intersolve visa migrate things

---

.github/workflows/deploy_client-drc_all.yml
.github/workflows/deploy_client-drc_portal.yml
.github/workflows/deploy_client-drc_service.yml
.github/workflows/deploy_client-slovakia_all.yml
.github/workflows/deploy_client-slovakia_portal.yml
.github/workflows/deploy_client-slovakia_service.yml
.github/workflows/deploy_client-southsudan_all.yml
.github/workflows/deploy_client-southsudan_portal.yml
.github/workflows/deploy_client-southsudan_service.yml

[AB#31116](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31116)
[AB#31117](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31117)
[AB#31118](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31118)

Add deployment workflows for new instances DRC, Slovakia, South Sudan

---

interfaces/Portal/src/app/program/make-payment/make-payment.component.ts
services/121-service/src/payments/payments.service.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-error.test.ts

[AB#30488](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30488)

Refactor the code validateRequiredFinancialServiceProviderConfiguration

---

services/121-service/src/migration/1729605362361-program-registration-attribute-refactor.ts
services/121-service/src/programs/programs.controller.ts
services/121-service/src/scripts/seed-init.ts
services/121-service/src/user/enum/permission.enum.ts
services/121-service/test/users/user-roles.test.ts

[AB#30491](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30491) 
- Removes program question/attribute update permission

Remove permissions for refactor registration data

---

interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.html
interfaces/Portalicious/src/app/pages/project-payments/components/export-payments/export-payments.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
interfaces/Portalicious/src/app/pages/projects-overview/components/project-summary-card/project-summary-card.component.html
interfaces/Portalicious/src/app/services/export.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#31056](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31056) [AB#31057](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31057) [AB#31059](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31059)

portalicious: registration exports review

---

.github/workflows/deploy_test_portalicious.yml
e2e/portalicious/pages/LoginPage.ts
e2e/portalicious/tests/CreateNewProject/CreateNewProjectSuccessfully.spec.ts
e2e/portalicious/tests/LogOut/LogOut.spec.ts
e2e/portalicious/tests/ManageTeam/ScopeVisibleOnlyWhenSetToTrue.spec.ts
e2e/portalicious/tests/Navigation/BasicNavigation.spec.ts
e2e/portalicious/tests/Navigation/ChangeLanguage.spec.ts
e2e/portalicious/tests/Users/UsersLastLogin.spec.ts
interfaces/Portalicious/.env.example
interfaces/Portalicious/angular.json
interfaces/Portalicious/src/app/app.component.ts
interfaces/Portalicious/src/app/pages/project-monitoring/project-monitoring.page.ts
interfaces/Portalicious/src/app/services/auth.service.ts
interfaces/Portalicious/src/app/services/translatable-string.service.ts
interfaces/Portalicious/src/app/utils/locale.spec.ts
interfaces/Portalicious/src/app/utils/locale.ts
interfaces/Portalicious/src/environments/environment.ts
interfaces/Portalicious/src/environments/environment.ts.template.js
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/src/logout/logout.js
interfaces/Portalicious/src/main.ts
interfaces/Portalicious/staticwebapp.config.json

[AB#31058](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31058)
[Teams thread](https://teams.microsoft.com/l/message/19:7124353330864787a3b045e327470bb9@thread.skype/1730895935273?tenantId=d3ab9790-6ae2-4bd8-aa5e-02864483e7c7&groupId=55f2fa49-7d9b-4c63-b616-b986f3136c3a&parentMessageId=1730883603068&teamName=510%20-%20CVA&channelName=121%20Portalicious&createdTime=1730895935273)

portalicious: fix locale

---

interfaces/Portal/src/app/components/registration-personal-information/registration-personal-information.component.ts
interfaces/Portal/src/app/program/program-people-affected/program-people-affected.component.ts
services/121-service/src/migration/1729605362361-program-registration-attribute-refactor.ts
services/121-service/src/registration/registrations.controller.ts
services/121-service/src/user/enum/permission.enum.ts
services/121-service/test-registration-data/test-registrations-patch-OCW-chosen-FSP.csv
services/121-service/test/helpers/assert.helper.ts
services/121-service/test/registrations/bulk-update-registration.test.ts
services/121-service/test/registrations/update-registration-program-financial-service-provider-configuration.test.ts

[AB#31140](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31140)
- apply permission check for update fsp on patch registration
- api-test on bulk update fsp

Fix.permission update fsp

---

interfaces/Portalicious/src/app/components/metric-container/metric-container.component.html
interfaces/Portalicious/src/app/domains/notification/notification.api.service.ts
interfaces/Portalicious/src/app/services/translatable-string.service.ts
interfaces/Portalicious/src/app/utils/locale.ts

[AB#31178](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31178)

portalicious: fix locale in templates

---

interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.model.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-templated-message/change-status-contents-with-templated-message.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-templated-message/change-status-contents-with-templated-message.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-without-message/change-status-contents-without-message.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-without-message/change-status-contents-without-message.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts

[AB#30987](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30987)

portalicious: dry run popups

---

services/121-service/module-dependencies.md
services/121-service/src/app.module.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.module.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.spec.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.ts
services/121-service/src/programs/programs.module.ts
services/121-service/src/shared/interceptors/program-existence.interceptor.ts
services/121-service/test/helpers/program-financial-service-provider-configuration.helper.ts
services/121-service/test/interceptors/program-exists.interceptor.test.ts
services/121-service/test/registrations/pagination/pagination-data.ts

[AB#31195](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31195)

Check from programId in interceptor

---

interfaces/Portal/src/app/components/registration-activity-overview/registration-activity-overview.component.ts

[AB#30372](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30372)

Get label from fsp configurations

---

services/121-service/src/metrics/metrics.service.ts
services/121-service/src/migration/1729605362361-program-registration-attribute-refactor.ts
services/121-service/src/payments/dto/pa-payment-data.dto.ts
services/121-service/src/payments/dto/reconciliation-feedback.dto.ts
services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
services/121-service/src/payments/fsp-integration/intersolve-voucher/services/intersolve-voucher-cron.service.ts
services/121-service/src/program-attributes/program-attributes.service.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.controller.ts
services/121-service/src/programs/dto/program-return.dto.ts
services/121-service/src/programs/mappers/program-registration-attribute.mapper.ts
services/121-service/src/programs/programs.controller.ts
services/121-service/src/programs/programs.service.ts
services/121-service/src/registration/registration.entity.ts
services/121-service/src/scripts/seed-helper.ts
services/121-service/test/payment/do-payment-fsp-excel.test.ts
services/121-service/test/program/create-program.test.ts

[AB#31244](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31244)

Refactor registration data resolve todo

---

services/121-service/src/guards/authenticated-user.decorator.ts

[AB#31270](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31270)

Show permission per endpoint in swagger

---

.github/workflows/test_e2e_portalicious.yml
interfaces/Portalicious/src/app/components/page-layout/components/registration-menu/registration-menu.component.ts
interfaces/Portalicious/src/app/domains/financial-service-provider/financial-service-provider.api.service.ts
interfaces/Portalicious/src/app/domains/financial-service-provider/financial-service-provider.model.ts
interfaces/Portalicious/src/app/domains/project/project.api.service.ts
interfaces/Portalicious/src/app/domains/project/project.helper.ts
interfaces/Portalicious/src/app/domains/project/project.model.ts
interfaces/Portalicious/src/app/pages/project-monitoring/project-monitoring.page.ts
interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
interfaces/Portalicious/src/app/services/export.service.ts
interfaces/Portalicious/src/app/services/messaging.service.ts
services/121-service/src/financial-service-providers/financial-service-provider.dto.ts
services/121-service/src/financial-service-providers/financial-service-providers.const.ts
services/121-service/src/seed-data/program/program-test-one-admin.json

[AB#30519](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30519) [AB#31086](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31086)

portalicious: fix attributes stuff based on refactor registration data

---

.github/workflows/deploy_client-demo_portal.yml
.github/workflows/deploy_client-drc_portal.yml
.github/workflows/deploy_client-ethiopia_portal.yml
.github/workflows/deploy_client-greece_portal.yml
.github/workflows/deploy_client-helpachild_portal.yml
.github/workflows/deploy_client-jrethiopia_portal.yml
.github/workflows/deploy_client-krcs-training_portal.yml
.github/workflows/deploy_client-krcs_portal.yml
.github/workflows/deploy_client-nlrc_portal.yml
.github/workflows/deploy_client-slovakia_portal.yml
.github/workflows/deploy_client-southafrica_portal.yml
.github/workflows/deploy_client-southsudan_portal.yml
.github/workflows/deploy_client-training_portal.yml
.github/workflows/deploy_client-zambia_portal.yml
.github/workflows/deploy_client-zimbabwe_portal.yml
.github/workflows/deploy_staging_portal.yml
.github/workflows/deploy_test_portal.yml
.github/workflows/deploy_test_portalicious.yml
interfaces/Portal/.env.example
interfaces/Portal/src/app/app.module.ts
interfaces/Portal/src/app/services/language.service.ts
interfaces/Portal/src/environments/environment.ts.template.js
interfaces/Portalicious/.env.example
interfaces/Portalicious/src/environments/environment.ts.template.js

[AB#31268](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31268)
Enable/Fix the use of the Default-Language set from an ENV-variable

feat: Make "default language" configurable from the ENV

---

interfaces/Portalicious/eslint.config.js
interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
interfaces/Portalicious/src/app/domains/registration/registration.model.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-voucher-dialog/activity-log-voucher-dialog.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-templated-message/change-status-contents-with-templated-message.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-templated-message/change-status-contents-with-templated-message.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-without-message/change-status-contents-without-message.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-without-message/change-status-contents-without-message.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-submit-buttons/change-status-submit-buttons.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-submit-buttons/change-status-submit-buttons.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
interfaces/Portalicious/src/app/services/messaging.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#30837](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30837)

portalicious: status change popup

---

interfaces/Portal/src/app/components/update-fsp/update-fsp.component.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview.component.ts
services/121-service/src/activities/activities.mapper.ts
services/121-service/src/activities/activities.service.ts
services/121-service/src/activities/interfaces/transaction-activity.interface.ts
services/121-service/src/payments/transactions/dto/get-audited-transaction.dto.ts
services/121-service/src/payments/transactions/transaction.repository.ts

[AB#31245](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31245)

Update activities endpoint with programFspConfigName

---

interfaces/Portalicious/src/app/components/colored-chip/colored-chip.component.ts
interfaces/Portalicious/src/app/components/colored-chip/colored-chip.helper.ts
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-without-message/change-status-contents-without-message.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
interfaces/Portalicious/src/app/services/messaging.service.ts
interfaces/Portalicious/src/app/services/paginate-query.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#30859](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30859) [AB#31286](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31286)

portalicious: change status review & effect refactor

---

services/121-service/src/migrate-visa/migrate-visa.service.ts

[AB#31224](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31224)

Visa migration unique funding token

---

.github/workflows/deploy_client-nlrc_portal.yml
.github/workflows/deploy_client-nlrc_service.yml

[AB#31435](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31435)

Disable NLRC deploy

---

.github/workflows/test_pull_request_formatting.yml

[AB#31427](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31427)

refactor: Prevent duplication of labels-list

---

services/121-service/README.md
services/121-service/package-lock.json
services/121-service/package.json

[AB#31280](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31280)

Forked typeorm

---

interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.html
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts

[AB#31329](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31329)

portalicious: restrict payment registrations to "status: included"

---

interfaces/Portalicious/src/app/components/page-layout/components/breadcrumbs-title/breadcrumbs-title.component.html
interfaces/Portalicious/src/app/components/page-layout/components/breadcrumbs-title/breadcrumbs-title.component.ts
interfaces/Portalicious/src/app/components/page-layout/components/page-layout-title-and-actions/page-layout-title-and-actions.component.html
interfaces/Portalicious/src/app/components/page-layout/components/page-layout-title-and-actions/page-layout-title-and-actions.component.ts
interfaces/Portalicious/src/app/components/page-layout/components/payment-header/payment-header.component.html
interfaces/Portalicious/src/app/components/page-layout/components/payment-header/payment-header.component.ts
interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.html
interfaces/Portalicious/src/app/components/page-layout/components/registration-header/registration-header.component.ts
interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
interfaces/Portalicious/src/app/components/page-layout/page-layout.component.ts
interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#31322](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31322)
Continues the work started in #6109

portalicious: payments breadcrumbs

---

.github/workflows/test_pull_request_formatting.yml
services/121-service/package-lock.json
services/121-service/package.json
services/121-service/src/main.ts
services/121-service/src/shared/middleware/azure-logger.middleware.ts
services/121-service/src/shared/services/azure-log.service.ts
services/121-service/src/shared/services/custom-http.service.ts

[AB#31413](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31413)
Attempt nr 2 at upgrading applicationinsights package.

Chore.upgrade applicationinsights v3

---

services/121-service/src/payments/fsp-integration/excel/excel.service.ts
services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.spec.ts
services/121-service/src/program-financial-service-provider-configurations/dtos/create-program-financial-service-provider-configuration.dto.ts
services/121-service/src/program-financial-service-provider-configurations/mappers/program-financial-service-provider-configuration.mapper.spec.ts
services/121-service/src/program-financial-service-provider-configurations/mappers/program-financial-service-provider-configuration.mapper.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.controller.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.repository.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.spec.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.ts
services/121-service/src/programs/programs.service.ts

[AB#30873](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30873)

Comments didirik refactor registration data second slice

---

interfaces/Portalicious/src/app/components/button-menu/button-menu.component.html
interfaces/Portalicious/src/app/components/data-list/data-list.component.html
interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
interfaces/Portalicious/src/app/components/form/form-sidebar.component.ts
interfaces/Portalicious/src/app/components/fullscreen-spinner/fullscreen-spinner.component.html
interfaces/Portalicious/src/app/components/fullscreen-spinner/fullscreen-spinner.component.ts
interfaces/Portalicious/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.html
interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
interfaces/Portalicious/src/app/domains/payment/payment.helpers.ts
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.html
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
interfaces/Portalicious/src/app/pages/projects-overview/components/project-summary-card/project-summary-card.component.ts
interfaces/Portalicious/src/app/services/toast.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/src/styles.scss
services/121-service/src/payments/payments.service.ts

[AB#31331](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31331)

portalicious: create payment (non-excel fsps)

---

interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts

[AB#31512](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31512)

portalicious: add FSP in registrations table

---

.github/workflows/deploy_test_portalicious.yml

[AB#31575](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31575)

Portalicious: fix Test deploy yml

---

interfaces/Portalicious/src/app/domains/financial-service-provider/financial-service-provider.api.service.ts
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
services/121-service/src/registration/dto/bulk-action-result.dto.ts

[AB#31511](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31511)
I'm also pre-emptively removing some FSP code that will become obsolete with the refactor registration data branch (and that is currently part of an unfinished page anyways), based on a convo with Ruben.

portalicious: add FSP display names in payment summary

---

interfaces/Portalicious/src/app/components/page-layout/components/payment-header/payment-header.component.html
interfaces/Portalicious/src/app/components/page-layout/components/payment-header/payment-header.component.ts
interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
interfaces/Portalicious/src/app/domains/project/project.helper.ts
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.html
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
interfaces/Portalicious/src/app/services/export.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#31330](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31330)

portalicious: excel payments

---

interfaces/Portalicious/src/app/services/auth/strategies/msal-auth/msal-auth.app-providers.ts
interfaces/Portalicious/src/app/services/auth/strategies/msal-auth/msal-auth.strategy.ts
interfaces/Portalicious/src/app/utils/url-helper.ts

[AB#31577](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31577)

Portalicious: fix origin URL

---

e2e/portalicious/components/TableComponent.ts
e2e/portalicious/pages/RegistrationsPage.ts
e2e/portalicious/tests/ViewAndManagePeopleAffected/ClearAllFilters.spec.ts

[AB#31233](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31233)
Builds upon #6144

portalicious: add E2E test for "clear all filters"

---

interfaces/Portal/src/app/models/bulk-actions.models.ts
interfaces/Portal/src/app/program/make-payment/make-payment.component.ts
interfaces/Portal/src/app/program/payment-status-popup/payment-status-popup.component.ts
interfaces/Portal/src/app/shared/payment-result.ts
interfaces/Portalicious/src/app/domains/financial-service-provider-configuration/financial-service-provider-configuration.api.service.ts
interfaces/Portalicious/src/app/domains/financial-service-provider-configuration/financial-service-provider-configuration.model.ts
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
services/121-service/src/payments/dto/pa-payment-retry-data.dto.ts
services/121-service/src/payments/payments.service.ts
services/121-service/src/registration/dto/bulk-action-result.dto.ts

and update payment overview accordingly
[AB#31594](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31594)

portalicious: add FinancialServiceProviderConfigurationApiService

---

interfaces/README.md

[AB#31438](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31438)

docs: Add code-snippets to test Twilio Flex integration AB#31438

---

interfaces/Portalicious/src/app/domains/financial-service-provider/financial-service-provider.helper.ts
interfaces/Portalicious/src/app/domains/project/project.helper.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.html
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts

[AB#31619](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31619)

portalicious: fix payment-related fsp usage

---

services/121-service/src/payments/payments.service.ts
services/121-service/src/scripts/seed-mock-helpers.ts

[AB#31615](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31615) 
@aberonni I created a bugfix for the popup about missing fsp config not showing in the Portal. I fixed it server side, as it was never handled at the side of the portal (at least thats what I thought looking at the code).

Check missing fsp configs only in dryrun=false do payment

---

services/121-service/README.md
services/121-service/src/main.ts
services/121-service/swagger.json

AB#[31624](https://dev.azure.com/redcrossnl/121%20Platform/_workitems/edit/31624)
[AB#31624](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31624)

Add swagger json automatically

---

services/121-service/package-lock.json
services/121-service/package.json
services/121-service/src/registration/registrations.service.ts
services/121-service/src/registration/repositories/registration-scoped-base.repository.ts
services/121-service/src/scoped.repository.ts
services/121-service/src/user/user.controller.ts
services/121-service/src/user/user.service.ts
services/121-service/src/utils/scope/createFindWhereOptions.helper.spec.ts
services/121-service/src/utils/scope/createFindWhereOptions.helper.ts

[AB#31450](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31450)

Stronger typed typeorm

---

interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts

[AB#31660](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31660)
Looks like this was the last one remaining

portalicious: fix remaining endpoints

---

e2e/package-lock.json
e2e/package.json
interfaces/Portal/package-lock.json
interfaces/Portal/package.json
interfaces/Portalicious/package-lock.json
interfaces/Portalicious/package.json
k6/package-lock.json
k6/package.json
package-lock.json
package.json
services/121-service/package-lock.json
services/121-service/package.json
services/121-service/src/registration/dto/bulk-import.dto.ts
services/121-service/src/registration/dto/bulk-update.dto.ts
services/mock-service/package-lock.json
services/mock-service/package.json

[AB#31617](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31617)

Prettier to 3.4.1

---

interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
interfaces/Portalicious/src/app/domains/domain-api.service.ts
interfaces/Portalicious/src/app/domains/metric/metric.api.service.ts
interfaces/Portalicious/src/app/domains/metric/metric.model.ts
interfaces/Portalicious/src/app/domains/transaction/transaction.helper.ts
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
interfaces/Portalicious/src/app/services/http-wrapper.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
services/121-service/src/metrics/metrics.service.ts

[AB#31326](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31326)

portalicious: add transactions table to payment page

---

interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts

[AB#31502](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31502)

portalicious: export payment list

---

e2e/portalicious/components/TableComponent.ts
e2e/portalicious/tests/Navigation/BasicNavigation.spec.ts
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts

[AB#31830](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31830)

portalicious: reload registrations page without page hanging

---

.github/workflows/deploy_staging_all.yml

[AB#31620](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31620)

ci: Include Portalicious in Deploy All

---

k6/tests/retryFailedJobsOnStartupDuringQueueProcessing.js
services/121-service/src/queue-registry/queue-registry.module.ts
services/121-service/src/queue-registry/queue-registry.service.ts
services/121-service/src/scripts/scripts.controller.ts

[AB#31640](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31640) 
- Log handling job startup errors to azure if it fails
- Do not show endpoint out of debug

Log queue error on startup, do not show crash endpoint out of debug

---

.github/dependabot.yml
services/.env.example
services/121-service/package-lock.json
services/121-service/package.json
services/121-service/src/main.ts
services/121-service/src/shared/middleware/azure-logger.middleware.ts
services/121-service/src/shared/services/azure-log.service.ts
services/121-service/src/shared/services/custom-http.service.ts
services/mock-service/src/main.ts

[AB#31909](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31909)
[AB#31931](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31931)
Re-vert: https://github.com/global-121/121-platform/pull/6142/files

Apply hotfix/v24.12-2

---

interfaces/Portalicious/src/app/components/page-layout/components/payment-header/payment-header.component.ts
interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
interfaces/Portalicious/src/app/domains/transaction/transaction.helper.ts
interfaces/Portalicious/src/app/pages/project-payment/components/project-payment-chart/project-payment-chart.component.html
interfaces/Portalicious/src/app/pages/project-payment/components/project-payment-chart/project-payment-chart.component.ts
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
interfaces/Portalicious/src/app/services/auth/strategies/msal-auth/msal-auth.strategy.ts
interfaces/Portalicious/src/app/utils/chart.ts
interfaces/Portalicious/src/app/utils/tailwind.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/tailwind.config.ts
services/121-service/src/payments/payments.controller.ts
services/121-service/src/payments/payments.service.ts
services/121-service/swagger.json

[AB#31325](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31325)

portalicious: payment chart

---

.github/dependabot.yml

ci: Adjust grouping of Dependabot PRs (+only ignore specific versions; not everything)

---

.github/actions/build-service/action.yml
.github/workflows/test_mock-service_code.yml
.github/workflows/test_service_api.yml
.github/workflows/test_service_code.yml
README.md

[AB#31940](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31940)

ci: Include typecheck-test before Build

---

interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.html
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/tailwind.config.ts

[AB#31170](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31170)

portalicious: do payment review

---

services/121-service/src/actions/utils/action.mapper.spec.ts
services/121-service/src/programs/programs.controller.ts
services/121-service/src/user/utils/user.mapper.spec.ts
services/121-service/test/helpers/program.helper.ts
services/121-service/test/program/delete-program.test.ts

[AB#32012](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32012)

Delete program api test

---

interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#31324](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31324)

portalicious: payment left metrics

---

services/121-service/src/actions/action.entity.ts
services/121-service/src/events/entities/event.entity.ts
services/121-service/src/migration/1733492799598-refactor-ondelete-cascade.ts
services/121-service/src/notes/note.entity.ts
services/121-service/src/notifications/latest-message.entity.ts
services/121-service/src/notifications/twilio.entity.ts
services/121-service/src/notifications/whatsapp/try-whatsapp.entity.ts
services/121-service/src/notifications/whatsapp/whatsapp-pending-message.entity.ts
services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia-account-enquiries.entity.ts
services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher-instructions.entity.ts
services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.entity.ts
services/121-service/src/payments/imagecode/image-code-export-vouchers.entity.ts
services/121-service/src/payments/transactions/latest-transaction.entity.ts
services/121-service/src/payments/transactions/transaction.entity.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.spec.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.ts
services/121-service/src/registration/registration.entity.ts

[AB#31938](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31938) [AB#32189](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32189)
Check all relationships carefully again.
See task descriptions for more details.

Refactor.cascade delete check all relations

---

services/121-service/src/migration/1733492799598-refactor-ondelete-cascade.ts

[AB#32189](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32189)

Refactor.cascade delete cleanup training demo

---

services/121-service/src/config.ts

[AB#32244](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32244)

add squagger

---

interfaces/Portal/src/app/models/payment.model.ts
interfaces/Portal/src/app/program/registration-activity-detail-accordion/registration-activity-detail-accordion.component.html
interfaces/Portal/src/app/program/registration-activity-detail-accordion/registration-activity-detail-accordion.component.ts
interfaces/Portal/src/app/shared/payment.utils.ts
interfaces/Portal/src/assets/i18n/ar.json
interfaces/Portal/src/assets/i18n/en.json
interfaces/Portal/src/assets/i18n/es.json
interfaces/Portal/src/assets/i18n/fr.json
interfaces/Portal/src/assets/i18n/nl.json
interfaces/Portal/src/assets/i18n/ru.json

[AB#32246](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32246)

Remove visa card id from transaction in portal

---

e2e/portalicious/pages/PaymentsPage.ts
e2e/portalicious/tests/DoPayment/DoSuccessfulPaymentWithExcelFsp.spec.ts
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.html
interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.html
interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
services/121-service/test/registrations/pagination/pagination-data.ts

[AB#32230](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32230) 
Adds e2e test for successful Payment with Portalicious.

Add e2e test for successful Payment with Portalicious

---

services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts

[AB#32271](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32271)

fix: only update at intersolve when value is present

---

interfaces/Portalicious/src/app/domains/project/project-attribute.helpers.ts
interfaces/Portalicious/src/app/domains/project/project.api.service.ts
interfaces/Portalicious/src/app/domains/project/project.helper.ts
interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
services/121-service/src/registration/enum/registration-attribute.enum.ts
services/121-service/src/shared/enum/language.enums.ts

[AB#30601](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30601)

AB#30601 Personal Info generic attributes refactor

---

.github/workflows/deploy_client-nlrc_portal.yml
.github/workflows/deploy_client-nlrc_service.yml

[AB#32326](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32326)

Enable NLRC deploy again

---

.github/dependabot.yml

ci: Reduce "destined to fail" dependency combinations

---

interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#32349](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32349)

payment card redesign

---

services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts

[AB#32362](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32362)
Merge hotfix which solves Intersolve voucher get balance.

fix: voucher get balance AB#32362

---

services/121-service/module-dependencies.md
services/121-service/src/program-financial-service-provider-configurations/entities/program-financial-service-provider-configuration.entity.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.module.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.spec.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.ts
services/121-service/swagger.json
services/121-service/test/program/__snapshots__/manage-program-financial-service-provider-configuration.test.ts.snap
services/121-service/test/program/manage-program-financial-service-provider-configuration.test.ts

[AB#32262](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32262)

Only remove fsp config of deleted registrations

---

interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.html
interfaces/Portalicious/src/app/components/data-list/data-list.component.html
interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.html
interfaces/Portalicious/src/app/components/form-field-wrapper/form-field-wrapper.component.ts
interfaces/Portalicious/src/app/components/registration-page-layout/components/registration-menu/registration-menu.component.ts
interfaces/Portalicious/src/app/domains/project/project-attribute.helpers.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/pages/project-monitoring/project-monitoring.page.ts
interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview.component.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.html
interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
interfaces/Portalicious/src/app/services/auth.service.ts
interfaces/Portalicious/src/app/services/registration-attribute.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#32415](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32415)

portalicious: edit personal information

---

e2e/portalicious/pages/PaymentsPage.ts
e2e/portalicious/tests/ViewPayment/PaymentInProgressChipVisible.spec.ts

[AB#32339](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32339) 
Adds test for Payment overview "Payment in progress" chip to be visible.

Add test for chip visible in payment overview

---

.github/workflows/deploy_test_portalicious.yml
docs/pull_request_template.md

[AB#32463](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32463)
This is the new thing ⬇️
https://lively-river-04adce503-6349.westeurope.5.azurestaticapps.net

portalicious: add preview URL to PR description

---

.github/workflows/deploy_test_portalicious.yml

[AB#32564](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32564)
https://lively-river-04adce503-6369.westeurope.5.azurestaticapps.net

ci: Prevent failing workflow runs of Dependabot-PRs

---

interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html

[AB#32572](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32572) 
https://lively-river-04adce503-6370.westeurope.5.azurestaticapps.net

allow nullable for non required dropdown fields

---

interfaces/Portalicious/package-lock.json
interfaces/Portalicious/package.json
interfaces/Portalicious/src/app/domains/domain-api.service.ts
interfaces/Portalicious/src/app/guards/found-resource.guard.ts
interfaces/Portalicious/src/app/pages/project-payment/components/import-reconciliation-data/import-reconciliation-data.component.ts
interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.ts
interfaces/Portalicious/src/app/services/auth/strategies/msal-auth/msal-auth.strategy.ts
interfaces/Portalicious/src/app/services/export.service.ts
interfaces/Portalicious/src/app/services/messaging.service.ts
interfaces/Portalicious/src/app/services/registration-attribute.service.ts

[AB#32202](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32202)
https://lively-river-04adce503-6372.westeurope.5.azurestaticapps.net

chore: tanstack + eslint upgrade AB#32202

---

e2e/portalicious/components/TableComponent.ts
e2e/portalicious/pages/BasePage.ts
e2e/portalicious/tests/ViewPayment/ValidateViewPaymentsTable.spec.ts

[AB#32458](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32458) 
Adds e2e test for payment table sorting and filtering

Add E2E test for "Table should be a filtered list"

---

services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.spec.ts
services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.ts
services/121-service/src/payments/fsp-integration/safaricom/services/safaricom.api.helper.service.spec.ts
services/121-service/src/payments/fsp-integration/safaricom/services/safaricom.api.service.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.spec.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.ts
services/121-service/src/registration/modules/registration-data/registration-data.service.ts
services/121-service/src/utils/token/token-validation.service.spec.ts

[AB#32305](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32305) 
Rounding off and cleaning up stuff so we can get the item to Done.

Unit testing isTokenValid clean-up

---

.github/workflows/deploy_client-demo_all.yml
.github/workflows/deploy_client-demo_portalicious.yml
.github/workflows/deploy_client-nlrc_all.yml
.github/workflows/deploy_client-nlrc_portalicious.yml
.github/workflows/deploy_client-training_all.yml
.github/workflows/deploy_client-training_portalicious.yml
.github/workflows/deploy_staging_portalicious.yml
.github/workflows/deploy_test_portalicious.yml

[AB#32672](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32672)

feat: Add deployment-workflows for new Portal(iciou)(s)'

---

.github/workflows/test_k6_cronjob.yml
k6/run-all-tests.sh

[AB#32739](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32739) 

Fix.k6 error message

---

interfaces/Portalicious/_build-deployment-configuration.mjs
interfaces/Portalicious/_test-deployment-configuration.mjs
interfaces/Portalicious/_verify-deployment-configuration.mjs

[AB#32737](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32737)
This change is more like a "proof of concept";
Because hopefully we won't need this configuration...
https://lively-river-04adce503-6394.westeurope.5.azurestaticapps.net

fix: Allow pop-ups more broadly

---

.github/workflows/deploy_client-demo_portalicious.yml
.github/workflows/deploy_client-drc_all.yml
.github/workflows/deploy_client-greece_all.yml
.github/workflows/deploy_client-helpachild_all.yml
.github/workflows/deploy_client-jrethiopia_all.yml
.github/workflows/deploy_client-krcs_all.yml
.github/workflows/deploy_client-nlrc_all.yml
.github/workflows/deploy_client-slovakia_all.yml
.github/workflows/deploy_client-southafrica_all.yml
.github/workflows/deploy_client-training_all.yml
.github/workflows/deploy_client-zambia_all.yml

[AB#32807](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32807)

ci: Add deployment-status update permissions to all "all"-workflows

---

interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
interfaces/Portalicious/src/app/domains/project/project.api.service.ts
interfaces/Portalicious/src/app/services/registrations-table-column.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
services/121-service/src/programs/dto/found-program.dto.ts

[AB#32539](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32539) [AB#32683](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32683) 
https://lively-river-04adce503-6381.westeurope.5.azurestaticapps.net

portalicious: filters from backend

---

interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts

[AB#32733](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32733) 
https://lively-river-04adce503-6406.westeurope.5.azurestaticapps.net

Portalicious fix: convert cents to euros

---

interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.ts
interfaces/Portalicious/src/app/services/registrations-table-column.service.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#32822](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32822) 
https://lively-river-04adce503-6407.westeurope.5.azurestaticapps.net

Portalicious chore: update 'status' translation

---

interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts

[AB#32824](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32824) 
https://lively-river-04adce503-6408.westeurope.5.azurestaticapps.net

chore: swap 'Time and date' & 'Done by' columns

---

interfaces/Portal/src/assets/i18n/es.json

[AB#32884](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32884) 
Improved Spanish translation for Portal

Improved translation export buttons for payments

---

interfaces/Portalicious/src/app/app.routes.ts
interfaces/Portalicious/src/app/components/page-layout/components/footer/footer.component.html
interfaces/Portalicious/src/app/components/page-layout/components/footer/footer.component.ts
interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.ts
interfaces/Portalicious/src/app/pages/login/login.page.html
interfaces/Portalicious/src/app/pages/login/login.page.ts
interfaces/Portalicious/src/app/pages/privacy/privacy.page.html
interfaces/Portalicious/src/app/pages/privacy/privacy.page.ts
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf

[AB#32799](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32799)
https://lively-river-04adce503-6409.westeurope.5.azurestaticapps.net

feat: Add Privacy-notice page + links

---

e2e/portalicious/tests/DoPayment/DoSuccessfulPayment.spec.ts
e2e/portalicious/tests/ViewPayment/GraphDisplaysAllCorrectPaymentStatuses.spec.ts
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts

[AB#32422](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32422)
https://lively-river-04adce503-6396.westeurope.5.azurestaticapps.net

portalicious: fix payment graph + test

---

interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
interfaces/Portalicious/src/app/services/registrations-table-column.service.ts

[AB#32869](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32869) [AB#32936](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32936)  
https://lively-river-04adce503-6417.westeurope.5.azurestaticapps.net

fix: column order registration table

---

services/121-service/module-dependencies.md
services/121-service/package.json
services/121-service/src/financial-service-providers/enum/financial-service-provider-name.enum.ts
services/121-service/src/financial-service-providers/financial-service-providers-settings.const.ts
services/121-service/src/migration/1734524945346-MakeProgramFspConfigNullableForeignKey.ts
services/121-service/src/payments/payments.service.ts
services/121-service/src/payments/transactions/transaction.entity.ts
services/121-service/src/program-financial-service-provider-configurations/entities/program-financial-service-provider-configuration.entity.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.module.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.spec.ts
services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.service.ts
services/121-service/src/registration/registration.entity.ts
services/121-service/swagger.json
services/121-service/test/program/__snapshots__/manage-program-financial-service-provider-configuration.test.ts.snap
services/121-service/test/program/manage-program-financial-service-provider-configuration.test.ts

[AB#32262](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32262)

fix: make make programFspConfigId nullable in relations AB#32262

---

interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview.component.ts

[AB#32823](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32823) 
https://lively-river-04adce503-6415.westeurope.5.azurestaticapps.net

Chore: transfer 'overview' change in activity log

---

services/121-service/src/scripts/enum/seed-script.enum.ts
services/121-service/src/scripts/scripts.service.ts
services/121-service/src/scripts/seed-configuration.const.ts
services/121-service/src/scripts/seed-configuration.dto.ts

[AB#32984](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32984) 

AB#32984 Seed admin only

---

interfaces/Portalicious/_build-deployment-configuration.mjs
interfaces/Portalicious/_test-deployment-configuration.mjs
interfaces/Portalicious/_verify-deployment-configuration.mjs
interfaces/Portalicious/src/app/services/auth/strategies/msal-auth/msal-auth.strategy.ts

[AB#33072](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33072) 
https://lively-river-04adce503-6431.westeurope.5.azurestaticapps.net

Portalicious SSO: add logging + fix COOP setting

---

.github/workflows/test_pull_request_formatting.yml

[AB#33088](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33088)
You don't have to re-test the "PR Linter"-workflow manually anymore.
You can just add/update the labels of the PR, or change the description.

ci: Automatically re-test a PR on updating labels

---

.github/workflows/deploy_client-ivorycoast_all.yml
.github/workflows/deploy_client-ivorycoast_portal.yml
.github/workflows/deploy_client-ivorycoast_service.yml

[AB#32490](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32490)

chore: create ivorycoast workflows

---

interfaces/Portal/staticwebapp.config.json
interfaces/Portalicious/staticwebapp.config.base.json
services/121-service/src/emails/templates/body.helper.ts
services/121-service/src/emails/templates/config.enum.ts
services/121-service/src/emails/templates/createNonSsoUserTemplate.ts
services/121-service/src/emails/templates/createSsoUserTemplate.ts
services/121-service/src/emails/templates/passwordResetTemplate.ts

[AB#31616](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31616)
https://lively-river-04adce503-6443.westeurope.5.azurestaticapps.net

feat: Add human-readable, generic URLs for change-password

---

interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
interfaces/Portalicious/src/app/components/query-table/components/query-table-global-search/query-table-global-search.component.html
interfaces/Portalicious/src/styles.scss

[AB#33097](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33097)
This one slipped through the cracks with the theming review
https://lively-river-04adce503-6433.westeurope.5.azurestaticapps.net

portalicious: icon buttons

---

interfaces/Portalicious/_build-deployment-configuration.mjs
interfaces/Portalicious/_test-deployment-configuration.mjs
interfaces/Portalicious/_verify-deployment-configuration.mjs

[AB#33150](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33150)
See: https://stackoverflow.com/a/50575768
https://lively-river-04adce503-6437.westeurope.5.azurestaticapps.net

refactor: Remove deprecated/unused CSP-directives + add tests

---

interfaces/Portalicious/src/app/domains/metric/metric.model.ts
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts

[AB#33035](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33035)
https://lively-river-04adce503-6463.westeurope.5.azurestaticapps.net

portalicious: add timestamp to payment page table

---

interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
interfaces/Portalicious/src/locale/messages.nl.xlf
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/src/styles.scss

[AB#32974](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32974)
https://lively-river-04adce503-6465.westeurope.5.azurestaticapps.net

portalicious: align empty table message to left

---

README.md

[AB#32038](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32038) 
Updates main documentation with links to e2e README and Wiki.

Add links for e2e and Azure Tests Plan documentation.

---

services/121-service/src/scripts/scripts.controller.ts
services/121-service/src/scripts/scripts.service.ts
services/121-service/src/scripts/seed-init.ts
services/121-service/test/helpers/registration.helper.ts
services/121-service/test/metrics/export-list.test.ts

[AB#33046](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33046) 
Fix the is API test boolean flag that was not passed along to the reset script

Fix tests reset API test

---

services/121-service/src/events/events.controller.ts
services/121-service/src/events/events.service.spec.ts
services/121-service/src/events/events.service.ts
services/121-service/src/events/interfaces/create-from-registration-views-options.interface.ts
services/121-service/src/payments/transactions/transactions.service.ts
services/121-service/src/registration/registrations.service.ts
services/121-service/src/registration/services/registrations-bulk.service.ts
services/121-service/src/registration/services/registrations-import.service.ts
services/121-service/src/transaction-job-processors/transaction-job-processors.service.ts

[AB#33268](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33268) 
While reviewing code I saw some things in the EventsService public interface that could be cleaner.

Events: small changes and refactor todo's

---

interfaces/Portalicious/src/app/components/import-file-dialog/import-file-dialog.component.html

[AB#33288](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33288)
https://lively-river-04adce503-6473.westeurope.5.azurestaticapps.net

portalicious: easier to read import errors

---

interfaces/Portalicious/src/app/utils/chart.ts

[AB#32552](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32552)
https://lively-river-04adce503-6468.westeurope.5.azurestaticapps.net

portalicious: fix datalabels in chart

---

services/121-service/src/user/dto/assign-aw-to-program.dto.ts
services/121-service/src/user/user.controller.ts
services/121-service/src/user/user.service.ts

[AB#33318](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33318) 

Fix delete teammember from team

---

interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.html
interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.html

[AB#32607](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32607)
https://lively-river-04adce503-6472.westeurope.5.azurestaticapps.net

portalicious: consistent cmd/ctrl+enter

---

.github/workflows/deploy_client-somalia_all.yml
.github/workflows/deploy_client-somalia_portal.yml
.github/workflows/deploy_client-somalia_service.yml

[AB#33366](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33366) 
I did not setup the old portal flow

Somalia github actions

---

services/121-service/src/metrics/metrics.service.ts

[AB#33478](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33478) 

fix permission to export dupes

---

.github/release.yml
.github/workflows/test_pull_request_formatting.yml

[AB#32804](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32804)

feat: Remove special treatment of "Portalicious"-label

---

services/121-service/test/commercial-bank-ethiopia/export-validation-report.test.ts
services/121-service/test/payment/do-payment-fsp-voucher.test.ts
services/121-service/test/visa-card/export-report.test.ts

[AB#33474](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33474) 

Also validate that dates are valid when matching snapshot

---

services/mock-service/package-lock.json
services/mock-service/package.json

[AB#33496](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33496)

chore: Remove unused + Update dependencies

---

e2e/portalicious/tests/ViewPayment/ErrorOnMissinCollumnMatchConfiguration.spec.ts
services/121-service/src/scripts/enum/seed-script.enum.ts
services/121-service/src/scripts/seed-configuration.const.ts
services/121-service/src/seed-data/program/program-nlrc-pv-excel-fail.json

[AB#33353](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33353) 
Adds a test and new mock configuration for a program with missing columnToMatch Configuration in Excel FSP.

Add E2E test for Error in missing columnToMatch Configuration

---

interfaces/Portalicious/src/app/components/query-table/components/query-table-global-search/query-table-global-search.component.html

[AB#29807](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29807)
Fixing a bug introduced here: https://github.com/global-121/121-platform/pull/6397/files#r1954071733
https://lively-river-04adce503-6514.westeurope.5.azurestaticapps.net

fix: regression from easter egg code

---

e2e/portalicious/components/TableComponent.ts
e2e/portalicious/pages/BasePage.ts
e2e/portalicious/pages/PaymentsPage.ts
e2e/portalicious/tests/ViewPayment/ErrorOnMissinCollumnMatchConfiguration.spec.ts
e2e/portalicious/tests/ViewPayment/RetryFailedTransfers.spec.ts
e2e/portalicious/tests/ViewPayment/RetryPaymentWithExcelFsp.spec.ts
e2e/portalicious/tests/ViewPayment/ValidateViewPaymentsTable.spec.ts
e2e/test-registration-data/test-reconciliation-Excel-pv.csv
services/121-service/test/registrations/pagination/pagination-data.ts

[AB#33355](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33355) 
Adds e2e test for retrying payment with excel fsp.

Retry payment with Excel FSP

---

.github/workflows/deploy_client-ethiopia_all.yml
.github/workflows/deploy_client-ethiopia_portal.yml
.github/workflows/deploy_client-krcs_all.yml
.github/workflows/deploy_client-krcs_portalicious.yml

[AB#33691](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33691)
[AB#33692](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33692)

Upgrade Ethiopia Portal + Add new Portal for Kenya

---

e2e/portalicious/pages/PaymentsPage.ts
interfaces/Portalicious/eslint.config.js
interfaces/Portalicious/src/app/pages/project-payment/components/retry-transfers-dialog/retry-transfers-dialog.component.html
interfaces/Portalicious/src/app/pages/project-payment/components/retry-transfers-dialog/retry-transfers-dialog.component.ts
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.html
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
interfaces/Portalicious/src/locale/messages.xlf
interfaces/Portalicious/src/styles.scss

[AB#32860](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32860)
Picking up the work done in #6474 
https://lively-river-04adce503-6515.westeurope.5.azurestaticapps.net

feat: retry transfer in activity log

---

interfaces/Portalicious/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.html

[AB#33736](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33736)
https://lively-river-04adce503-6533.westeurope.5.azurestaticapps.net

fix: Keep checkboxes in a column, align multi-line labels more prettiously

---

services/121-service/src/metrics/metrics.service.ts
services/121-service/src/payments/reconciliation/excel/excel-reconciliation.service.ts
services/121-service/test/payment/__snapshots__/do-payment-fsp-excel.test.ts.snap
services/121-service/test/payment/do-payment-fsp-excel.test.ts

[AB#33631](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33631) 

Fix duplicate columns in excel reconciliation service

---

interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.ts

[AB#33861](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33861) 
https://lively-river-04adce503-6536.westeurope.5.azurestaticapps.net

show voucher button for paper voucher

---

.github/workflows/deploy_client-sudan_all.yml
.github/workflows/deploy_client-sudan_portal.yml
.github/workflows/deploy_client-sudan_service.yml

[AB#33842](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33842) 

chore: add sudan workflows

---

interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts

[AB#33934](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33934) 
https://lively-river-04adce503-6543.westeurope.5.azurestaticapps.net

Don't round off the transfer values

---

.github/workflows/deploy_client-benin_all.yml
.github/workflows/deploy_client-benin_portal.yml
.github/workflows/deploy_client-benin_service.yml
.github/workflows/deploy_client-nigeria_all.yml
.github/workflows/deploy_client-nigeria_portal.yml
.github/workflows/deploy_client-nigeria_service.yml
.github/workflows/deploy_client-togo_all.yml
.github/workflows/deploy_client-togo_portal.yml
.github/workflows/deploy_client-togo_service.yml

[AB#33957](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33957) 

chore: add workflows for Togo + Benin + Nigeria

---

e2e/README.md
e2e/package-lock.json
e2e/portalicious/pages/BasePage.ts
e2e/portalicious/pages/RegistrationActivityLogPage.ts
e2e/portalicious/pages/RegistrationBasePage.ts
e2e/portalicious/pages/RegistrationPersonalInformationPage.ts
e2e/portalicious/pages/RegistrationsPage.ts
e2e/portalicious/tests/ViewAndManagePeopleAffected/ValidateDuplicateBadges.spec.ts
e2e/portalicious/tests/ViewAndManagePeopleAffected/ValidateDuplicateBanner.spec.ts
e2e/portalicious/tests/ViewAndManagePeopleAffected/ValidateDuplicateChanges.spec.ts
e2e/portalicious/tests/ViewAndManagePeopleAffected/ValidateDuplicateChangesFor3Registrations.spec.ts
interfaces/Portalicious/src/app/components/registration-page-layout/components/registration-duplicates-banner/registration-duplicates-banner.component.html
interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html

[AB#33538](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33538)
https://lively-river-04adce503-6552.westeurope.5.azurestaticapps.net

chore: add E2E tests for duplicate registrations

---

.github/workflows/deploy_client-jrethiopia_all.yml
.github/workflows/deploy_client-jrethiopia_portal.yml

[AB#34034](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34034)
- please don't merge. I'd like to deploy from the branch to test the workflow first

chore: update jrethiopia to deploy portalicious

---

interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts

[AB#34012](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34012)
https://lively-river-04adce503-6560.westeurope.5.azurestaticapps.net

feat: improve empty table message in "create payment" flow

---

interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
interfaces/Portalicious/src/locale/messages.xlf

[AB#34010](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34010)
https://lively-river-04adce503-6558.westeurope.5.azurestaticapps.net

fix: error message when attempting to re-include a registration

---

interfaces/Portalicious/src/app/pages/project-payment/components/retry-transfers-dialog/retry-transfers-dialog.component.ts
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.ts

[AB#34021](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34021)
IMHO this doesn't warrant a dedicated test but I'm willing to be persuaded otherwise.
https://lively-river-04adce503-6561.westeurope.5.azurestaticapps.net

fix: prevent retrying failed transfers whilst another payment is in progress

---

.github/workflows/deploy_client-drc_portal.yml

[AB#34141](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34141)
Allow the DRC-Portal to embed the PowerBI-dashboards in an iframe.

feat: Enable PowerBI-dashboards in DRC-Portal

---

interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
interfaces/Portalicious/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.html
interfaces/Portalicious/src/app/components/query-table/components/query-table-global-search/query-table-global-search.component.html
interfaces/Portalicious/src/app/services/rtl-helper.service.ts

[AB#34003](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34003)
https://lively-river-04adce503-6579.westeurope.5.azurestaticapps.net

chore: refactor rtlhelper

---

services/121-service/src/payments/imagecode/image-code.service.ts

[AB#34217](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34217) 

Throw 404 instead of 500 on failed voucher retrieval

---

interfaces/Portalicious/src/app/components/page-layout/page-layout.component.html
interfaces/Portalicious/src/app/components/page-layout/page-layout.component.ts
interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/services/rtl-helper.service.ts

[AB#34095](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34095)
https://lively-river-04adce503-6584.westeurope.5.azurestaticapps.net

chore: refactor rtl-friendly chevron icons

---

interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts

[AB#34299](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34299)
- There are no tests for this page yet - TBD in [AB#32181](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32181)
https://lively-river-04adce503-6599.westeurope.5.azurestaticapps.net

feat: show "Fail reason" in activity log when a transfer fails

---

interfaces/Portalicious/src/app/components/card-grid/card-grid.component.html
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.html
interfaces/Portalicious/src/styles.scss

[AB#33802](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33802) [AB#33939](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33939) [AB#33460](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33460)
I had a glimpse at the backlog and found these three 5-min fixes and decided to just take care of them and avoid the admin
https://lively-river-04adce503-6600.westeurope.5.azurestaticapps.net

chore: minor ui fixes on portalicious

---

interfaces/Portalicious/src/app/pages/project-payments/components/export-payments/export-payments.component.ts

[AB#34342](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34342) 
Fixed bug that caused the export payments to not export the payments. 
https://lively-river-04adce503-6605.westeurope.5.azurestaticapps.net

Fix export last payments

---

e2e/portalicious/components/DataListComponent.ts
e2e/portalicious/pages/RegistrationPersonalInformationPage.ts

[AB#34328](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34328)
Introduce data-list-component helper so there's one way for getting data from data list components in E2E tests.

e2e tests - Introduce data-list-component helper

---

interfaces/Portalicious/src/app/pages/login/login.page.html
interfaces/Portalicious/src/locale/messages.xlf

[AB#33409](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33409)
[AB#34236](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34236)
https://lively-river-04adce503-6594.westeurope.5.azurestaticapps.net

Add image credits for ZOA

---

services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.service.ts

[AB#34385](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34385) 
Use programFspConfigId to get config instead of programId

Use programFspConfigId to get config instead of programId

---

services/121-service/src/payments/fsp-integration/vodacash/vodacash.service.ts
services/121-service/src/utils/file-import/file-import.service.ts

[AB#34428](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34428) 

Hotfix upload Vodacash Reconciliation XML

---

e2e/portalicious/pages/BasePage.ts
e2e/portalicious/pages/RegistrationPersonalInformationPage.ts
e2e/portalicious/tests/ChangeRegistrationStatus/NonApplicableStatusChange.spec.ts

[AB#34305](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34305) 
Adds e2e scenario for testing error messages.

Add negative scenarios for status change

---

services/121-service/src/registration/registrations.service.ts

[AB#34388](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34388) 
Move registrations from status completed to declined

Fix move registration from completed to declined

---

.github/actions/build-service/action.yml
.github/workflows/deploy_client-benin_service.yml
.github/workflows/deploy_client-demo_service.yml
.github/workflows/deploy_client-drc_service.yml
.github/workflows/deploy_client-eswatini_service.yml
.github/workflows/deploy_client-ethiopia-staging_service.yml
.github/workflows/deploy_client-ethiopia_service.yml
.github/workflows/deploy_client-greece_service.yml
.github/workflows/deploy_client-helpachild_service.yml
.github/workflows/deploy_client-ivorycoast_service.yml
.github/workflows/deploy_client-jrethiopia_service.yml
.github/workflows/deploy_client-krcs_service.yml
.github/workflows/deploy_client-nigeria_service.yml
.github/workflows/deploy_client-nlrc_service.yml
.github/workflows/deploy_client-slovakia_service.yml
.github/workflows/deploy_client-somalia_service.yml
.github/workflows/deploy_client-southafrica_service.yml
.github/workflows/deploy_client-sudan_service.yml
.github/workflows/deploy_client-togo_service.yml
.github/workflows/deploy_client-training_service.yml
.github/workflows/deploy_client-zambia_service.yml
.github/workflows/deploy_staging_service.yml
.github/workflows/deploy_test_service.yml
services/.env.example
services/121-service/.gitignore
services/121-service/src/ormconfig.ts

[AB#34276](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34276)

fix: Read ALL CA-certificates from App Service containter for DB-connection

---

services/121-service/src/health/health.controller.ts

[AB#34468](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34468)
Increase the timeout to hopefully reduce the noise in the logs...

ops: Increase timeout of Health-check for DB

---

services/121-service/src/registration/registrations.service.ts

[AB#34580](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34580) 
Fix allow change from complete to decline, without a refactor. So we do not accidentally deploy a bug to prod

Fix correct status change

---

docs/pull_request_template.md

[AB#34613](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34613)

chore: add design review to PR description

---

.vscode/extensions.json
interfaces/Portal/.vscode/settings.json
interfaces/Portalicious/.vscode/settings.json
services/121-service/.vscode/settings.json
services/mock-service/.vscode/settings.json

[AB#34608](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34608)
https://lively-river-04adce503-6634.westeurope.5.azurestaticapps.net

[Boyscout] Align configs for sub-packages/tools (+Sort alphabetically for easier diffs)

---

e2e/portalicious/components/ConfirmationDialogComponent.ts
e2e/portalicious/pages/RegistrationDebitCardPage.ts
e2e/portalicious/tests/DebitCards/ManageDebitCards.spec.ts
interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.html

[AB#34329](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34329) 
https://lively-river-04adce503-6626.westeurope.5.azurestaticapps.net

Test.e2e view debit cards

---

.github/workflows/deploy_client-drc_all.yml
.github/workflows/deploy_client-greece_all.yml
.github/workflows/deploy_client-zambia_all.yml

[AB#34717](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34717)

fix: Include Portalicious build-steps in Deploy All workflows

---

.github/dependabot.yml
services/121-service/package-lock.json
services/121-service/package.json
services/mock-service/package-lock.json
services/mock-service/package.json

[AB#34723](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34723)
[AB#11693](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/11693)
More collateral cleanup!

chore: Remove unused dependencies of unused code

---

interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.html

[AB#34776](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34776)
Follow up from [AB#34789](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34789)
https://lively-river-04adce503-6659.westeurope.5.azurestaticapps.net

refactor: Stricter checks for "Currency" data-list-item data-model

---

e2e/portalicious/components/TableComponent.ts
e2e/portalicious/pages/BasePage.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusCompleted.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusDeclined.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusIncluded.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusPaused.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusRegistered.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusValidated.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromCompletedToDeclined.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromCompletedToIncluded.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromDeclinedToIncluded.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromIncludedToDeclined.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromIncludedToPaused.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromRegisteredToValidated.spec.ts
e2e/portalicious/tests/ProfilePageActivityLog/ExpandRowsOfActivityOverview.spec.ts
e2e/portalicious/tests/ProfilePageActivityLog/FilterActivityOverviewTable.spec.ts
e2e/portalicious/tests/RegistrationPage/InitiateActions.spec.ts
e2e/portalicious/tests/RegistrationPage/ViewAvailableActions.spec.ts
e2e/portalicious/tests/ViewPayment/ValidateViewPaymentsTable.spec.ts
interfaces/Portalicious/src/app/components/query-table/query-table.component.html

[AB#34327](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34327) 
Add E2E tests for validating activity log overview of a registration and add some maintenance work to automated test suite.
https://lively-river-04adce503-6637.westeurope.5.azurestaticapps.net

Map tests with test ids

---

k6/tests/findDuplicates100kRegistrations.js

[AB#34801](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34801)
Removed a single console.log that was probably missed in code review.

chore: cleanup console log

---

interfaces/Portalicious/_build-download-translations.mjs
interfaces/Portalicious/_translations.utils.mjs
interfaces/Portalicious/_verify-build.mjs
interfaces/Portalicious/package.json
interfaces/Portalicious/src/app/components/language-switcher/language-switcher.component.html
interfaces/Portalicious/src/locale/messages.xlf

[AB#34725](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34725)
Verify with some hard-coded translations that the actual translations are downloaded into the build. (And verify no mock-language is included)
https://lively-river-04adce503-6663.westeurope.5.azurestaticapps.net

test: Add (baseline) checks for downloaded translations in build

---

services/121-service/src/exchange-rates/exchange-rates.api.service.ts

[AB#34837](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34837) 
We do not see http exceptions in our nest js logs. So changed this error to new Error

Clearer error in our logs

---

.github/workflows/test_k6.yml
.github/workflows/test_k6_cronjob.yml

[AB#34840](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34840) 
Add some comments

chore: add comments

---

interfaces/Portalicious/_verify-build.mjs

[AB#34835](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34835) 
https://lively-river-04adce503-6669.westeurope.5.azurestaticapps.net

fix: change translation string

---

services/121-service/src/notifications/lookup/lookup.service.ts

[AB#34914](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34914) 
Be gone! Annoying log!

remove annoying log

---

services/121-service/src/cronjob/cronjob.controller.ts
services/121-service/src/cronjob/cronjob.service.ts

[AB#34958](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34958)
Tiny refactor in cronjob controller.

tiny refactor in cron job controller

---

services/121-service/src/events/events.service.ts

[AB#34957](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34957)

fix: Make sure the order of entity-IDs doesn't matter in equallity-check

---

e2e/portalicious/components/TableComponent.ts
e2e/portalicious/pages/BasePage.ts
e2e/portalicious/pages/RegistrationsPage.ts
e2e/portalicious/tests/ImportRegistrations/ImportRegistrationsSuccessfully.spec.ts
e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDate.spec.ts
e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDropdownSelection.spec.ts
e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByFsp.spec.ts
e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByNumberInput.spec.ts
e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByText.spec.ts
services/121-service/test/registrations/pagination/pagination-data.ts

[AB#34936](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34936) 
Adds e2e tests for validating table view, filtering and sorting.

Add E2E tests for view, filter and sort registrations in table

---

services/121-service/src/cronjob/cronjob.controller.ts
services/121-service/src/cronjob/cronjob.service.spec.ts
services/121-service/src/cronjob/cronjob.service.ts
services/121-service/src/utils/axios/axios-calls.service.spec.ts
services/121-service/src/utils/axios/axios-calls.service.ts
services/121-service/test/cronjob/cronjobs.test.ts
services/121-service/test/payment/do-payment-fsp-nedbank.test.ts

[AB#34950](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34950) 
Improve error for cronjob authentication failure.
I added some unit tests and an integration test around cronjobs. I had to restructure some code to allow for easier testing.
Also some refactoring mostly renaming.

Improve error for cronjob authentication failure

---

interfaces/Portalicious/README.md

[AB#34376](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34376)
https://lively-river-04adce503-6699.westeurope.5.azurestaticapps.net

docs: Improve README for working with translations

---

e2e/portalicious/components/TableComponent.ts
e2e/portalicious/pages/RegistrationsPage.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusCompleted.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusDeclined.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusIncluded.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusPaused.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusRegistered.spec.ts
e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusValidated.spec.ts
e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDate.spec.ts
e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDropdownSelection.spec.ts
e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByNumberInput.spec.ts
interfaces/Portalicious/package-lock.json
interfaces/Portalicious/package.json
interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
interfaces/Portalicious/src/app/domains/project/project-attribute.helpers.ts
interfaces/Portalicious/src/app/domains/project/project.api.service.ts
interfaces/Portalicious/src/app/services/paginate-query.service.spec.ts
interfaces/Portalicious/src/app/services/paginate-query.service.ts
interfaces/Portalicious/src/app/services/registration-attribute.service.ts
interfaces/Portalicious/src/app/services/registrations-table-column.service.ts
interfaces/Portalicious/src/app/utils/local-time-to-utc-time.ts
interfaces/Portalicious/src/locale/messages.xlf
services/121-service/src/registration/enum/registration-attribute.enum.ts
services/121-service/src/registration/services/registrations-pagination.service.ts

[AB#35058](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35058) 
https://lively-river-04adce503-6694.westeurope.5.azurestaticapps.net

Get registration by numeric of date range in portalicious

---

.vscode/launch.json
services/121-service/README.md
services/121-service/package.json
services/docker-compose.development.yml
services/mock-service/package.json

[AB#35132](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35132) 
Enable debugger for Mock Service and Integration Tests

Enable debugger for Mock Service and Integration Tests

---

e2e/portalicious/pages/BasePage.ts
e2e/portalicious/tests/ViewAndManagePeopleAffected/IgnoreDuplicates.spec.ts
interfaces/Portalicious/src/app/components/registration-page-layout/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts

[AB#34054](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34054)
https://lively-river-04adce503-6636.westeurope.5.azurestaticapps.net
Signed-off-by: Ruben <vandervalk@geoit.nl>

E2E test for ignore duplication

---

services/121-service/src/user/user.controller.ts
services/121-service/src/user/user.service.ts

[AB#35282](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35282)

fix: Align cookie security settings between login/out endpoints

---

interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
services/121-service/src/payments/payments.service.ts

[AB#35270](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35270) 
https://lively-river-04adce503-6715.westeurope.5.azurestaticapps.net

Total Payment Amounts: round, then sum

---

e2e/portalicious/components/TableComponent.ts
e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDate.spec.ts
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
interfaces/Portalicious/src/locale/messages.xlf

[AB#35061](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35061) 
https://lively-river-04adce503-6729.westeurope.5.azurestaticapps.net

changed ux on date filters

---

services/121-service/src/migration/1743597529999-created-ignore-duplication-permission.ts

[AB#35300](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35300) 

migrate for multiple roles

---

e2e/portalicious/pages/BasePage.ts
e2e/portalicious/tests/ViewAndManagePeopleAffected/IgnoreDuplicates.spec.ts
interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.html
interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
interfaces/Portalicious/src/app/components/registration-page-layout/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.html
interfaces/Portalicious/src/app/components/registration-page-layout/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.ts
interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.html
interfaces/Portalicious/src/app/components/registration-page-layout/registration-page-layout.component.ts
interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
interfaces/Portalicious/src/app/domains/registration/registration.model.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.ts
interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.html
interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-reason/change-status-reason.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-reason/change-status-reason.component.ts
interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.html
interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
interfaces/Portalicious/src/locale/messages.xlf
services/121-service/src/migration/1743597529999-created-ignore-duplication-permission.ts
services/121-service/src/registration/registrations.controller.ts
services/121-service/src/registration/repositories/registration-scoped.repository.ts
services/121-service/src/scripts/seed-init.ts
services/121-service/src/user/enum/permission.enum.ts

[AB#34750](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34750)
[AB#34380](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34380)
[AB#35300](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35300)
https://lively-river-04adce503-6656.westeurope.5.azurestaticapps.net

fix: ignore-duplicates frontend

---

.github/workflows/test_e2e_portal.yml
.github/workflows/test_e2e_portalicious.yml
.github/workflows/test_formatting.yml
.github/workflows/test_interface_portal.yml
.github/workflows/test_interface_portalicious.yml
.github/workflows/test_k6.yml
.github/workflows/test_mock-service_code.yml
.github/workflows/test_service_api.yml
.github/workflows/test_service_code.yml
.github/workflows/test_workflows.yml

[AB#35372](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35372)
These extra events that will trigger automated test-runs, will help us enforce/enable a central "merge queue".
So we have to do less manual rebasing/waiting/getting-distracted/etc...

Add config for a merge-queue to auto-rebase/merge PRs

---

interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.html
interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview/table-cell-overview.component.ts
interfaces/Portalicious/src/locale/messages.xlf

[AB#35400](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35400)
https://lively-river-04adce503-6739.westeurope.5.azurestaticapps.net

feat: add link to ignored activity log

---

e2e/portalicious/pages/PaymentsPage.ts
e2e/portalicious/tests/ViewPayments/ShowPaymentSummary.spec.ts

[AB#35229](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35229) 

Is payment empty e2e

---

services/121-service/package-lock.json
services/121-service/package.json

[AB#35165](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35165) 

chore: security alerts

---

e2e/portalicious/pages/ProjectTeam.ts
e2e/portalicious/tests/ManageTeam/UserCannotAssignRolesToSelf.spec.ts
interfaces/Portalicious/src/app/pages/project-team/components/add-project-team-user-form/add-project-team-user-form.component.html
interfaces/Portalicious/src/app/pages/project-team/components/add-project-team-user-form/add-project-team-user-form.component.ts
interfaces/Portalicious/src/locale/messages.xlf

[AB#35518](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35518) 
https://lively-river-04adce503-6759.westeurope.5.azurestaticapps.net

No self assign frontend and e2e test

---

services/121-service/src/user/helpers/throw-if-self-update.spec.ts
services/121-service/src/user/helpers/throw-if-self-update.ts
services/121-service/src/user/user.controller.ts
services/121-service/test/programs/users/__snapshots__/roles.test.ts.snap
services/121-service/test/programs/users/roles.test.ts

[AB#35510](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35510) 

No self update

---

interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts

[AB#35605](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35605) 
https://lively-river-04adce503-6772.westeurope.5.azurestaticapps.net

fix: don't send message if option unchecked

---

services/121-service/src/programs/kobo/kobo-api-service.ts

[AB#35584](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35584) 

get form definition from '/deployed' or handle error

---

.github/workflows/test_interface_portalicious.yml

[AB#35617](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35617)

ci: Include changes to the 121-service's code to trigger Portalicious' tests

---

.github/dependabot.yml
services/121-service/package-lock.json
services/121-service/package.json

[AB#35429](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35429)

ci: Help Dependabot test for updated dependencies (not local ones)

---

services/121-service/src/exchange-rates/exchange-rates.controller.ts
services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.controller.ts
services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.controller.ts
services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.controller.ts
services/121-service/src/reconciliation/nedbank-reconciliation/nedbank-reconciliation.controller.ts

[AB#35598](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35598)

chore: Align all cronjob-methods and responses

---

README.md
e2e/.vscode/settings.json
e2e/README.md
e2e/playwright.config.ts
package.json
services/121-service/README.md

[AB#35418](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35418)

docs: Improve README/config for readability/ease-of-use, consistent use of PA/Registration/FSP terms

---

e2e/portalicious/tests/Redline/ViewRegistrationPageInRedline.spec.ts

[AB#35417](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35417)

test: Add e2e-tests for Redline-features

---

services/121-service/eslint-plugin-custom-rules/package.json

[AB#35429](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35429)

ci: Add package.json to make local ESLint-plugin install in Dependabot

---

interfaces/Portalicious/src/app/utils/local-storage.ts

[AB#35799](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35799)
https://happy-rock-0411d2003-6820.westeurope.3.azurestaticapps.net

chore: an homage

---

.github/dependabot.yml
.nvmrc
interfaces/.nvmrc
package-lock.json
package.json
services/121-service/.nvmrc

[AB#35820](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35820)
- After this is merged, it is advised to run `npm ci` from the root-folder.

chore: Upgrade/specify dependencies for root-tasks/scripts

---

services/121-service/src/user/user.controller.ts

[AB#35833](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35833) 
View users as orgadmin instead of admin

View users as organization admin

---

services/121-service/src/strategies/azure-ad.strategy.ts

[AB#35835](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35835) 
Azure ad strategy looked at the payload, but it should look at the user data that came from the db. I don't think it's possible to add api tests for these azure ad things, so I did not do that one

Fix organisation admin for azure ad

---

services/121-service/src/payments/dto/transaction-response.dto.ts
services/121-service/src/payments/payments.service.spec.ts
services/121-service/src/payments/transactions/transaction.repository.ts
services/121-service/test/program/manage-program-financial-service-provider-configuration.test.ts
services/121-service/test/registrations/update-registration-program-financial-service-provider-configuration.test.ts
services/121-service/test/transactions/get-transactions.test.ts

Whilst working on the FE for this feature, I realised some inconsistencies with what we expect to receive from the BE
Me and Ruben already looked at this in a call
https://happy-rock-0411d2003-6810.westeurope.3.azurestaticapps.net

chore: add missing properties to new transactions endpoint

---

e2e/portalicious/components/TableComponent.ts
e2e/portalicious/tests/ViewFilterAndSortRegistrations/DeselectAfterChangingFilterChange.spec.ts
interfaces/Portalicious/src/app/components/query-table/query-table.component.html
interfaces/Portalicious/src/app/components/query-table/query-table.component.ts

[AB#35792](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35792) [AB#35793](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35793) 
Deselect table rows after applying filters
https://happy-rock-0411d2003-6831.westeurope.3.azurestaticapps.net

Clear selection after applying a filter

---

services/121-service/src/exchange-rates/exchange-rates.controller.ts
services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.controller.ts
services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.controller.ts

[AB#35901](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35901) 
An error in a cronjob results in a node server crash. So we need to catch it and not just .finaly

Catch errors so node does not crash

---

services/121-service/src/exchange-rates/exchange-rates.controller.ts
services/121-service/src/exchange-rates/exchange-rates.module.ts
services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.module.ts
services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.controller.ts
services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.module.ts
services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.controller.ts
services/121-service/src/payments/reconciliation/intersolve-visa-reconciliation/intersolve-visa-reconciliation.module.ts
services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.controller.ts

[AB#35902](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35902) 

Log errors in cronjobs to azure

---

k6/models/payments.js
services/121-service/src/metrics/dto/registrationstatus-stats.dto.ts
services/121-service/src/metrics/metrics.controller.ts
services/121-service/src/metrics/metrics.service.ts
services/121-service/swagger.json

[AB#35931](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35931) 
The endpoint was deleted in [8ec567b0809c640ac81fcb89748a9d533be2d0ca](https://github.com/global-121/121-platform/commit/8ec567b0809c640ac81fcb89748a9d533be2d0ca)

fix: re-add erroneously deleted endpoint to get k6 working again

---

interfaces/Portalicious/src/app/domains/metric/metric.api.service.ts
interfaces/Portalicious/src/app/domains/metric/metric.model.ts
interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
interfaces/Portalicious/src/app/domains/payment/payment.model.ts
interfaces/Portalicious/src/app/pages/project-monitoring/project-monitoring.page.ts
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
interfaces/Portalicious/src/locale/messages.xlf

[AB#35543](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35543)
https://happy-rock-0411d2003-6812.westeurope.3.azurestaticapps.net

chore: use new transactions endpoint in portalicious

---

services/121-service/src/registration/enum/registration-validation-input-type.enum.ts
services/121-service/src/registration/interfaces/validate-registration-config.interface.ts
services/121-service/src/registration/registrations.controller.ts
services/121-service/src/registration/registrations.service.ts
services/121-service/src/registration/services/registrations-import.service.ts
services/121-service/src/registration/validators/registrations-input-validator.spec.ts
services/121-service/src/registration/validators/registrations-input-validator.ts
services/121-service/test-registration-data/test-registrations-patch-OCW.csv
services/121-service/test/registrations/bulk-update-registration.test.ts

[AB#35859](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35859) 

Do not allow type tel (phonenumber) in mass update (back-end)

---

interfaces/portal/src/app/services/registration-attribute.service.ts
interfaces/portal/src/locale/messages.xlf

[AB#36010](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36010)
https://happy-rock-0411d2003-6823.westeurope.3.azurestaticapps.net

refactor: Use a named variable for the list, to ease translations' context

---

services/121-service/src/metrics/metrics.controller.ts
services/121-service/src/metrics/metrics.service.ts
services/121-service/src/registration/const/filter-operation.const.ts
services/121-service/test/metrics/__snapshots__/export-list.test.ts.snap
services/121-service/test/metrics/export-list.test.ts

[AB#35916](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35916)

feat: metrics/export-list endpoint supports "select" pagination query

---

tools/download-logs.mjs

[AB#36103](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36103)

chore: Skip download of unused log-files

---

interfaces/portal/src/app/pages/project-payment/project-payment.page.ts
services/121-service/src/payments/dto/get-transaction-response.dto.ts
services/121-service/src/payments/payments.service.spec.ts
services/121-service/src/payments/transactions/transaction.repository.ts
services/121-service/src/scoped.repository.spec.ts
services/121-service/test/helpers/intersolve-voucher.helper.ts
services/121-service/test/helpers/program.helper.ts
services/121-service/test/mocks/seed-mock.test.ts
services/121-service/test/payment/do-payment-filter.test.ts
services/121-service/test/payment/do-payment-fsp-commercial-bank-ethiopia.test.ts
services/121-service/test/payment/do-payment-fsp-excel.test.ts
services/121-service/test/payment/do-payment-fsp-nedbank.test.ts
services/121-service/test/payment/do-payment-fsp-safaricom.test.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-error.test.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-retry.test.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit.success.test.ts
services/121-service/test/payment/do-payment.scope.test.ts
services/121-service/test/payment/payment-count-completed.test.ts
services/121-service/test/program/manage-program-financial-service-provider-configuration.test.ts
services/121-service/test/programs/registrations/scoped.test.ts
services/121-service/test/registrations/update-registration-program-financial-service-provider-configuration.test.ts
services/121-service/test/transactions/get-transactions.test.ts

[AB#35962](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35962)
- This _will_ change the public API output, so who needs to be informed pro-actively about it?
https://happy-rock-0411d2003-6868.westeurope.3.azurestaticapps.net

refactor: Rename referenceId to be less ambiguous to what it refers

---

.github/actions/build-interface/action.yml
.github/actions/build-service/action.yml
.github/workflows/test_e2e_portal.yml
.github/workflows/test_interface_portal.yml
.github/workflows/test_k6.yml
.github/workflows/test_k6_cronjob.yml
.github/workflows/test_mock-service_code.yml
.github/workflows/test_service_code.yml
.npmrc
e2e/.npmrc
interfaces/portal/.npmrc
k6/.npmrc
package.json
services/121-service/.npmrc
services/121-service/package.json
services/mock-service/.npmrc
services/mock-service/package.json

[AB#36141](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36141)
This way, we can never forget to provide the 2 flags for `npm i`;
This could, potentially, speed _some_ things up...
https://happy-rock-0411d2003-6889.westeurope.3.azurestaticapps.net

refactor: Replace manual flags with central npm-config

---

interfaces/portal/_build-download-translations.mjs

[AB#36180](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36180)
- ⚠️ I do need any deviation from our PR guidelines
- Re-run the "Deploy to test"-workflow tomorrow, to _not_ use the translations-download-cache.
https://happy-rock-0411d2003-6892.westeurope.3.azurestaticapps.net

refactor: Catch any errors from Lokalise API (to see if we run into new limits and have to go async)

---

interfaces/portal/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
interfaces/portal/src/app/services/registration-attribute.service.ts

[AB#36168](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36168)
Refactored this whilst working on #6845 to allow to share this information with the "mass update" flow. I figured I could pull it out and let it be its own refactor.
https://happy-rock-0411d2003-6891.westeurope.3.azurestaticapps.net

chore: centralise "editable attributes" information

---

e2e/portal/tests/ViewPayments/ExportPayments.spec.ts

[AB#35232](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35232)

test: add e2e permissions checks on payments page

---

e2e/README.md

[AB#36193](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36193) 

chore: update E2E docs with performance best practice

---

e2e/portal/pages/BasePage.ts
e2e/portal/tests/DoPayment/DoFailedPaymentWithCbe.spec.ts
e2e/portal/tests/DoPayment/DoFailedPaymentWithSafaricom.spec.ts
e2e/portal/tests/DoPayment/DoSuccessfulPaymentWithCbe.spec.ts
e2e/portal/tests/ViewAndManagePeopleAffected/OpenRegistrationInNewTab.spec.ts
e2e/portal/tests/ViewAndManagePeopleAffected/ValidateDuplicateBanner.spec.ts

[AB#35958](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35958) 
Adds failed payment tests for some FSPs:
1. Safaricom
2. Nedbank

Add MakeFailedPayment tests

---

interfaces/portal/tailwind.config.ts

[AB#36305](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36305) 
https://happy-rock-0411d2003-6897.westeurope.3.azurestaticapps.net

fix: update purple 50

---

services/121-service/src/strategies/azure-ad.strategy.ts

[AB#36471](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36471)

fix: Add check on requirements of Azure AD payload

---

services/121-service/module-dependencies.md
services/121-service/src/app.module.ts
services/121-service/src/payments/fsp-integration/onafriq/repositories/onafriq-transaction.scoped.repository.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/dtos/onafriq-transaction-callback-job.dto.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/dtos/onafriq-transaction-callback.dto.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.controller.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.module.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.service.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/processors/onafriq-transaction-callback-job.processor.ts
services/121-service/src/payments/reconciliation/safaricom-reconciliation/processors/safaricom-timeout-callback-job.processor.ts
services/121-service/src/queues-registry/enum/payment-callback-queue-names.enum.ts
services/121-service/src/queues-registry/enum/safaricom-callback-queue-names.enum.ts
services/121-service/src/queues-registry/queues-registry.module.ts
services/121-service/src/queues-registry/queues-registry.service.ts
services/121-service/swagger.json
services/mock-service/src/config.ts
services/mock-service/src/fsp-integration/onafriq/onafriq.dto.ts
services/mock-service/src/fsp-integration/onafriq/onafriq.mock.service.ts

[AB#36581](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36581)
Set up Onafriq callback. Functionally tested both with mock-service and sandbox. See task for more details.

feat: onafriq callback AB#36581

---

services/121-service/module-dependencies.md
services/121-service/src/app.module.ts
services/121-service/src/payments/fsp-integration/onafriq/repositories/onafriq-transaction.scoped.repository.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/dtos/onafriq-transaction-callback-job.dto.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/dtos/onafriq-transaction-callback.dto.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.controller.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.module.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.service.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/processors/onafriq-transaction-callback-job.processor.ts
services/121-service/src/payments/reconciliation/safaricom-reconciliation/processors/safaricom-timeout-callback-job.processor.ts
services/121-service/src/queues-registry/enum/payment-callback-queue-names.enum.ts
services/121-service/src/queues-registry/enum/safaricom-callback-queue-names.enum.ts
services/121-service/src/queues-registry/queues-registry.module.ts
services/121-service/src/queues-registry/queues-registry.service.ts
services/121-service/swagger.json
services/mock-service/src/app.module.ts
services/mock-service/src/config.ts
services/mock-service/src/fsp-integration/onafriq/onafriq.dto.ts
services/mock-service/src/fsp-integration/onafriq/onafriq.mock.controller.ts
services/mock-service/src/fsp-integration/onafriq/onafriq.mock.module.ts
services/mock-service/src/fsp-integration/onafriq/onafriq.mock.service.ts

[AB#36582](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36582)
Onafriq initial payment request with success response via mock-service.

feat: onafriq mock initial payment success AB#36582

---

services/121-service/src/payments/fsp-integration/onafriq/dtos/onafriq-api/webhook-subscribe-response-onafriq-api.dto.ts
services/121-service/src/payments/fsp-integration/onafriq/onafriq.controller.ts
services/121-service/src/payments/fsp-integration/onafriq/onafriq.module.ts
services/121-service/src/payments/fsp-integration/onafriq/onafriq.service.ts
services/121-service/src/payments/fsp-integration/onafriq/services/onafriq.api.service.ts
services/121-service/swagger.json

[AB#36590](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36590)
Endpoint to subscribe webhook with Onafriq (to pass callbackUrl to them, for one-time use).

Feat.onafriq webhook subscribe

---

e2e/portal/tests/ViewPayment/ValidateViewPaymentsTable.spec.ts
interfaces/portal/src/app/pages/project-payment/project-payment.page.ts
interfaces/portal/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
interfaces/portal/src/locale/messages.xlf

[AB#36719](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36719) 
Activity overview & payment page on pending/waiting state show message of transactions
https://happy-rock-0411d2003-6947.westeurope.3.azurestaticapps.net

Activity overview & payment page on pending/waiting state show message

---

services/121-service/test/helpers/registration.helper.ts
services/121-service/test/registrations/bulk-update-registration.test.ts

[AB#36660](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36660) 

Improve test flakiness: wait for registration changes to be complete

---

interfaces/portal/src/app/pages/project-registrations/components/import-registrations-menu/import-registrations-menu.component.html
interfaces/portal/src/app/pages/project-registrations/components/import-registrations-menu/import-registrations-menu.component.ts
interfaces/portal/src/app/pages/project-registrations/components/update-registrations/update-registrations.component.ts
interfaces/portal/src/app/pages/project-registrations/project-registrations.page.html

[AB#36714](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36714) 
https://happy-rock-0411d2003-6957.westeurope.3.azurestaticapps.net

fix: reset table selection and form fields on bulk update

---

.github/workflows/test_formatting.yml

[AB#36804](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36804)
Use the defined version of Prettier, not "just the latest"

ci: Make use of defined Prettier version

---

services/121-service/src/fsps/fsp-settings.const.ts
services/121-service/src/fsps/fsp-settings.helpers.ts
services/121-service/src/fsps/fsp.controller.ts
services/121-service/src/fsps/fsp.service.ts
services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
services/121-service/src/payments/fsp-integration/excel/excel.module.ts
services/121-service/src/payments/payments.controller.ts
services/121-service/src/payments/reconciliation/excel/excel-reconciliation.controller.ts
services/121-service/src/program-fsp-configurations/dtos/program-fsp-configuration-response.dto.ts
services/121-service/src/program-fsp-configurations/program-fsp-configurations.controller.ts
services/121-service/src/program-fsp-configurations/program-fsp-configurations.service.spec.ts
services/121-service/src/program-fsp-configurations/program-fsp-configurations.service.ts
services/121-service/src/programs/programs.service.ts
services/121-service/src/registration/registrations.controller.ts
services/121-service/src/registration/registrations.service.ts
services/121-service/test/program/__snapshots__/manage-program-fsp-configuration.test.ts.snap
services/121-service/test/program/manage-program-fsp-configuration.test.ts

[AB#36793](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36793) 

Rename FinancialServiceProvider to fsp in comments and string in the BE

---

README.md

[AB#36858](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36858) 
Readme update about sequence in migrations

Readme use setval

---

e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusNew.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusRegistered.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/MovePasFromNewToValidated.spec.ts
e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDropdownSelection.spec.ts
e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsDataChanges.spec.ts/exported-xlsx.csv
interfaces/portal/src/app/components/colored-chip/colored-chip.helper.ts
interfaces/portal/src/app/domains/message/message.helper.ts
interfaces/portal/src/app/domains/registration/registration.helper.ts
interfaces/portal/src/app/domains/registration/registration.model.ts
interfaces/portal/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
interfaces/portal/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.ts
interfaces/portal/src/locale/messages.xlf
services/121-service/src/events/events.service.spec.ts
services/121-service/src/metrics/metrics.service.ts
services/121-service/src/migration/1750762936357-rename-registered-to-new.ts
services/121-service/src/notifications/enum/message-type.enum.ts
services/121-service/src/notifications/enum/program-notification.enum.ts
services/121-service/src/registration/enum/registration-status.enum.ts
services/121-service/src/registration/helpers/status-change.helper.spec.ts
services/121-service/src/registration/helpers/status-change.helper.ts
services/121-service/src/registration/registrations.controller.ts
services/121-service/src/registration/registrations.service.ts
services/121-service/src/registration/services/registrations-bulk.service.spec.ts
services/121-service/src/registration/services/registrations-import.service.ts
services/121-service/src/seed-data/message-template/message-template-generic.const.ts
services/121-service/src/seed-data/message-template/message-template-nlrc-pv.const.ts
services/121-service/test/metrics/export-list.test.ts
services/121-service/test/program/message-template.test.ts
services/121-service/test/registrations/delete-registration.test.ts
services/121-service/test/registrations/pagination/update-registration-status.test.ts

[AB#35914](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35914)
Rename 'registered' status to 'new'
https://happy-rock-0411d2003-6963.westeurope.3.azurestaticapps.net

rename registered to new

---

services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.spec.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-intersolve-visa.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.spec.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-safaricom.service.ts
services/121-service/test/payment/payment-count-completed.test.ts

[AB#36937](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36937) 
- bugfix: registration status change to complete now (correctly) reflected in activity log
- add tests
- make calls to `createTransactionAndUpdateRegistration` simpler

refactor and bugfix

---

services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.spec.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-intersolve-visa.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.spec.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-onafriq.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-safaricom.service.ts
services/121-service/src/transaction-queues/dto/intersolve-visa-transaction-job.dto.ts
services/121-service/src/transaction-queues/dto/nedbank-transaction-job.dto.ts
services/121-service/src/transaction-queues/dto/onafriq-transaction-job.dto.ts
services/121-service/src/transaction-queues/dto/safaricom-transaction-job.dto.ts
services/121-service/src/transaction-queues/dto/shared-transaction-job.dto.ts

[AB#36959](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36959) 
- refactor - simplify calling createTransactionAndUpdateRegistration
- refactor - extend the DTO interfaces for transaction jobs

More refactor of transaction job processor

---

README.md

[AB#37111](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37111)

remove help a child exception from releases checklist

---

services/121-service/test/visa-card/block-visa-card.test.ts

[AB#36863](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36863)
...

test: Replace arbitrary waitFor with actual message-counting

---

services/121-service/test/visa-card/block-visa-card.test.ts

[AB#36863](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36863)

chore: try to fix annoying flaky block visa card test

---

interfaces/portal/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
interfaces/portal/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.ts
interfaces/portal/src/app/pages/project-payments/components/export-payments/export-payments.component.ts
interfaces/portal/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
interfaces/portal/src/app/services/tracking.service.ts

[AB#36178](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36178)
[AB#36179](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36179)
https://happy-rock-0411d2003-6980.westeurope.3.azurestaticapps.net

feat: set up event tracking

---

.github/workflows/test_e2e_portal.yml
e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusCompleted.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusDeclined.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusIncluded.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusNew.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusPaused.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusValidated.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/MovePasFromCompletedToDeclined.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/MovePasFromCompletedToIncluded.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/MovePasFromDeclinedToIncluded.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/MovePasFromIncludedToCompleted.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/MovePasFromIncludedToDeclined.spec.ts
e2e/portal/tests/ChangeRegistrationStatus/MovePasFromIncludedToPaused.spec.ts
e2e/portal/tests/EditRegistration/EditRegistration.spec.ts
e2e/portal/tests/EditRegistration/EditRegistrationFsp.spec.ts
e2e/portal/tests/ViewFilterAndSortRegistrations/DeselectAfterChangingFilterChange.spec.ts
e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDate.spec.ts
e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDropdownSelection.spec.ts
e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByFsp.spec.ts
e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByNumberInput.spec.ts
e2e/portal/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByText.spec.ts

[AB#37196](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37196)

chore: try sharding E2E tests

---

services/.env.example

[AB#37219](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37219)

docs: Be more explicit about uuid-versions in explanations/examples

---

interfaces/portal/karma.conf.js
services/121-service/jest.integration.config.js
services/121-service/jest.unit.config.js

[AB#37297](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37297)
https://happy-rock-0411d2003-7069.westeurope.3.azurestaticapps.net

chore: report coverage on all files

---

e2e/portal/tests/UpdateRegistrations/BulkUpdateVisibleInActivityLog.spec.ts

[AB#37355](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37355) 

test: add deletion to bulk update test

---

e2e/portal/tests/ExportRegistrations/ExportRegistrationsList.spec.ts
e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-registrations-xlsx.csv
e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-registrations.csv
e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-selected-columns-xlsx.csv
e2e/portal/tests/__screenshots__/ExportRegistrations/ExportRegistrationsList.spec.ts/exported-selected-columns.csv
interfaces/portal/src/app/components/query-table/query-table.component.ts
interfaces/portal/src/app/services/registrations-table-column.service.ts

[AB#37311](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37311) [AB#37314](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37314)
https://happy-rock-0411d2003-7074.westeurope.3.azurestaticapps.net

feat: add scope column to registrations table

---

interfaces/portal/src/app/app.theme.ts

[AB#37443](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37443)
Before:
After:
https://happy-rock-0411d2003-7077.westeurope.3.azurestaticapps.net

fix: layout issue on file uploads

---

services/121-service/src/programs/dto/update-program.dto.ts

[AB#37359](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37359) 
Since we now have this setting in our validation pipeline `whitelist: true,` attributes that are not in the in the dto's will be stripped of a request body. Which is why the update was broken. I also add the other missing properties. 
I put the PR on draft as it still needs some tests. However I will be on leave soon so hoping someone else can pick those up

Fix update program

---

e2e/portal/pages/PaymentPage.ts
e2e/portal/pages/PaymentsPage.ts
e2e/portal/tests/DoPayment/DoFailedPaymentWithCbe.spec.ts
e2e/portal/tests/DoPayment/DoFailedPaymentWithSafaricom.spec.ts
e2e/portal/tests/DoPayment/DoSuccessfulPaymentWithCbe.spec.ts
e2e/portal/tests/DoPayment/DoSuccessfulPaymentWithExcelFsp.spec.ts
e2e/portal/tests/DoPayment/DoSuccessfulPaymentWithNedbank.spec.ts
e2e/portal/tests/DoPayment/DoSuccessfulPaymentWithSafaricom.spec.ts
e2e/portal/tests/DoPayment/DoSuccessfulPaymentWithVisa.spec.ts
e2e/portal/tests/DoPayment/DoSuccessfulPaymentWithVoucher.spec.ts
e2e/portal/tests/ViewPayment/ExportPaymentReport.spec.ts
e2e/portal/tests/ViewPayment/GraphDisplaysAllCorrectPaymentStatuses.spec.ts
e2e/portal/tests/ViewPayment/GraphDisplaysCorrectPaymentAmount.spec.ts
e2e/portal/tests/ViewPayment/ImportReconciliationDataForExcelFsp.spec.ts
e2e/portal/tests/ViewPayment/RetryFailedTransfers.spec.ts
e2e/portal/tests/ViewPayment/RetryPaymentWithExcelFsp.spec.ts
e2e/portal/tests/ViewPayment/ValidateViewPaymentsTable.spec.ts
e2e/portal/tests/__screenshots__/ViewPayment/ExportPaymentReport.spec.ts/exported-xlsx.csv

[AB#37532](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37532)
Besides adding the test, I've also split `PaymentsPage` into `PaymentsPage` and `PaymentPage`, because a lot of the things in `PaymentsPage` were actually the payment details page, not the payments overview page.

chore: add e2e test for single payment export

---

services/121-service/src/notifications/enum/twilio-error-codes.enum.ts
services/121-service/src/notifications/message-incoming/message-incoming.service.ts
services/121-service/src/notifications/sms/sms.service.ts
services/121-service/src/notifications/whatsapp/whatsapp.service.ts
services/121-service/test/registrations/pagination/send-message.test.ts
services/mock-service/src/twilio/twilio.service.ts

[AB#37538](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37538) 
Specifically do not throw on error code 21211

Do not throw an error on twilio error code 21211 'to number does not exist'

---

services/121-service/src/metrics/metrics.controller.ts
services/121-service/test/metrics/export-list.test.ts

[AB#37597](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37597) 
Validate export type, to prevent a bug where we try to check for permissions for an export type that does not exist

Validate export type in export list endpoint

---

services/121-service/src/kobo-connect/kobo-connect.api.service.ts
services/121-service/src/kobo-connect/kobo-connect.service.ts
services/121-service/src/programs/programs.service.ts

[AB#37724](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37724) 
400 instead of 500 so we do not get an email

Do not create unneeded internal server error when the issue is in kobo-connect

---

services/121-service/test/payment/__snapshots__/do-payment-fsp-voucher.test.ts.snap
services/121-service/test/payment/do-payment-fsp-voucher.test.ts

[AB#37722](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37722) 

Add api tests for intersolve voucher

---

services/121-service/src/migration/1754399322187-payment-entity.ts

[AB#37767](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37767)

Fix a migration with faulty fk creation

---

services/121-service/src/payments/fsp-integration/airtel/services/__snapshots__/airtel.api.service.spec.ts.snap
services/121-service/src/payments/fsp-integration/airtel/services/airtel.api.service.spec.ts
services/121-service/src/payments/fsp-integration/airtel/services/airtel.api.service.ts

[AB#37875](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37875) 
We missed a header for Airtel. This wasn't necessary in acceptance testing, but the docs said it was required so let's add it. 

fix: add accept headers to disburse call

---

e2e/portal/pages/RegistrationsPage.ts
interfaces/portal/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.html
interfaces/portal/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.ts

[AB#37868](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37868)
https://happy-rock-0411d2003-7197.westeurope.3.azurestaticapps.net

chore: refactor table management to use p-drawer directly

---

interfaces/portal/src/app/domains/metric/metric.api.service.ts
services/121-service/src/metrics/metrics.controller.ts
services/121-service/src/payments/payments.controller.ts
services/121-service/src/payments/transactions/dto/get-transaction-query.dto.ts
services/121-service/src/registration-events/dto/get-registration-event-query.dto.ts
services/121-service/src/registration-events/dto/registration-event-search-options.dto.ts
services/121-service/src/registration-events/registration-events.controller.ts
services/121-service/swagger.json
services/121-service/test/helpers/program.helper.ts
services/121-service/test/registration-event/filter-registration-events.test.ts
services/121-service/test/transactions/export-transactions.test.ts

[AB#37695](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37695) 
This PR adds validation for date parameters (fromDate and toDate) in export endpoints by implementing proper DTO validation using class-validator decorators.
-     Introduces new DTO classes with @IsISO8601() validation for date parameters
-     Adds test coverage for invalid date parameter scenarios
-     Rename some event files to registration-events
https://happy-rock-0411d2003-7160.westeurope.3.azurestaticapps.net

Extra validation on from and to date for payment export

---

tools/check-versions.mjs
tools/download-logs.mjs

[AB#38073](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38073)

fix: Use new "instance-121"-elements from Status-page

---

services/.env.example
services/121-service/src/payments/fsp-integration/intersolve-visa/dtos/intersolve-api/customer-individual-intersolve-api.dto.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/dtos/intersolve-api/get-customer-individual-intersolve-api.dto.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/enums/intersolve-visa-121-error-text.enum.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/interfaces/send-updated-contact-information-params.interface.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/services/intersolve-visa.api.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/services/intersolve-visa.service.ts
services/121-service/src/registration/services/registrations.service.ts
services/121-service/test/visa-card/visa-customer-information-update.test.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.controller.ts
services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts

[AB#37779](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37779) 
Update the customer name on registration update.
See the attached task for test results
It's very hard to properly create automated tests for this functionality as the end result is an API request to intersolve. In an API test we simulate our the Intersolve API with the mock service. We have no way to easily validate if the mock service is properly called. So this functionally is only tested with the existing API test  

Intersolve update customer name on registration update

---

interfaces/portal/src/app/pages/project-team/components/add-project-team-user-dialog/add-project-team-user-dialog.component.html
interfaces/portal/src/app/pages/project-team/components/add-project-team-user-dialog/add-project-team-user-dialog.component.ts
interfaces/portal/src/locale/messages.xlf

[AB#38081](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38081)
https://happy-rock-0411d2003-7258.westeurope.3.azurestaticapps.net

feat: edit copy in "edit project team user" dialogs

---

services/121-service/src/migration/1757420276256-CbeTransferEntity.ts

[AB#38110](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38110)
Fix migration script that prevents deployment to CBE instances.

fix: CBE transfer migration

---

e2e/portal/pages/RegistrationsPage.ts

[AB#38157](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38157)
This is a follow up from #7264
In the linked PR, changes were made to reduce the amount of steps performed in the test, and to get a better understanding of where the test is failing.
Now it is still failing non-deterministically with a [failure like this](https://github.com/global-121/121-platform/actions/runs/17854321506/job/50769770113#step:11:170):
```bash
Error: expect(received).toEqual(expected) // deep equality
- Expected  - 2
+ Received  + 7
Array [
"Reg. #",
+   "Name",
+   "Registration Status",
+   "Duplicates",
+   "Phone Number",
+   "Number of payments",
+   "Max payments",
+   "Registration created",
"FSP",
"Address street",
-   "Phone Number",
"Scope",
-   "Name",
]
at …
```

chore: second attempt to fix ExportRegistrationList

---

services/121-service/src/payments/fsp-integration/intersolve-visa/services/intersolve-visa.api.service.ts
services/121-service/src/payments/fsp-integration/intersolve-visa/services/intersolve-visa.service.ts

[AB#38162](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38162) 
- Explicitly set firstName to empty string
- Also set estimatedAnnualPaymentVolumeMajorUnit to hardcorded value

Hardcode estimatedAnnualPaymentVolumeMajorUnit for intersolve individual

---

interfaces/portal/.knip.json
interfaces/portal/_matomo.utils.mjs
interfaces/portal/_matomo.utils.spec.ts
interfaces/portal/_test-deployment-configuration.mjs
interfaces/portal/_verify-deployment-configuration.mjs

[AB#38196](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38196)
https://happy-rock-0411d2003-7283.westeurope.3.azurestaticapps.net

fix: Prevent any stray spaces to break the Matomo-integration

---

services/121-service/module-dependencies.md
services/121-service/src/payments/fsp-integration/nedbank/entities/nedbank-voucher.entity.ts
services/121-service/src/payments/fsp-integration/nedbank/repositories/nedbank-voucher.scoped.repository.ts
services/121-service/src/payments/reconciliation/nedbank-reconciliation/nedbank-reconciliation.module.ts
services/121-service/src/payments/reconciliation/nedbank-reconciliation/nedbank-reconciliation.service.ts
services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.service.ts
services/121-service/src/payments/reconciliation/safaricom-reconciliation/safaricom-reconciliation.service.ts
services/121-service/src/payments/transactions/transaction-events/enum/transaction-event-description.enum.ts
services/121-service/src/payments/transactions/transaction-events/interfaces/transaction-event-creation-context.interfac.ts
services/121-service/src/payments/transactions/transaction-events/transaction-events.module.ts
services/121-service/src/payments/transactions/transaction-events/transaction-events.scoped.repository.ts
services/121-service/src/payments/transactions/transaction-events/transaction-events.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-intersolve-visa.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-onafriq.service.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-safaricom.service.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-error.test.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-retry.test.ts
services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit.success.test.ts

[AB#38093](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38093) 
- Refactoring storing of events a bit
- Refactored visa to use the new flow
- All visa api tests are passing

visa transfer events

---

services/121-service/src/payments/transactions/transaction-events/enum/transaction-event-description.enum.ts
services/121-service/src/program-fsp-configurations/entities/program-fsp-configuration.entity.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-airtel.service.spec.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-airtel.service.ts

[AB#38221](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38221) 
Airtel events new flow, airtel unit an api tests pass

Airtel transaction events

---

services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.scoped.repository.ts
services/121-service/src/payments/transactions/transaction-events/enum/transaction-event-description.enum.ts
services/121-service/src/transaction-jobs/services/transaction-jobs-commercial-bank-ethiopia.service.ts

[AB#38222](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38222) 

transation events cbe

---

e2e/portal/tests/DebitCards/ManageDebitCards.spec.ts
e2e/portal/tests/ProjectSettings/ProjectInformation/EditProjectInformation.spec.ts

[AB#38261](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38261)

chore: fix date formatting issue in E2E tests

---

services/mock-service/src/fsp-integration/airtel/airtel.mock.controller.ts

[AB#38184](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38184)

fix: Remove warnings around path-handling in Mock-Service

---

e2e/portal/tests/ProfilePageActivityLog/ExpandRowsOfActivityOverview.spec.ts
services/121-service/test/payment/__snapshots__/do-payment-fsp-voucher.test.ts.snap
services/121-service/test/payment/do-payment-fsp-voucher.test.ts

AB#XXXX 
Does this pass in CI?

attempt to fix tests

---

services/121-service/src/metrics/metrics.service.ts
services/121-service/src/utils/dateSort.ts
services/121-service/src/utils/to-type.helper.ts

[AB#38268](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38268) 
Fix a few remaining comments from PR #7142 

native dashboard - post merge cleanup

---

services/121-service/src/notifications/services/message.service.ts

[AB#38286](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38286) 

Delete pending message entity before sending it

---

README.md

[AB#38348](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38348) 

DB errors during deployment

---

.vscode/settings.json
e2e/.vscode/settings.json
interfaces/portal/.vscode/settings.json
services/121-service/.vscode/settings.json
services/mock-service/.vscode/settings.json

[AB#11693](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/11693)
This will not throw huge blocks of red code in your face; When these reported issues will be auto-fixable anyway.

feat: Make syntax-issues less 'loud' in editor (when auto-fixable)
