global-121/121-platform

- interfaces/HO-Portal/azure-pipelines.yml
- services/programs-service/azure-pipelines.yml
By using `npm ci` and removing the `build` step (for now)
Building+deploying will require a new pipeline
> Speed up CI-test pipeline

- services/tykn-ssi-services/indy-pool.dockerfile
@faisal00813  During a reinstalation of the tykn-ssi services i ran into this error:
`Depends: python3-pyzmq (= 17.0.0) but 18.1.0 is to be installed`. So i created this fix for it based on on this pull request i found from philips https://github.com/hyperledger/indy-sdk/pull/1909/commits/f9b19ea60a4ec807fe87f3d85efd3d9fb0e361d1.
> Made a change in the indy pool to fix pyzmq dependency

- interfaces/PA-App/package-lock.json
- interfaces/PA-App/package.json
@elwinschmitz I removed this - now unused (right?) - plugin, because it gave trouble in the 'npm ci' step in the webhook on the server. If I shouldn't have taken this out, or should have done so differently, we can always change it back.
> removed cordova global-121-indy plugin

- interfaces/HO-Portal/src/app/auth/auth.guard.ts
- interfaces/HO-Portal/src/app/auth/auth.service.ts
- interfaces/HO-Portal/src/app/login/login.page.html
- interfaces/HO-Portal/src/app/login/login.page.spec.ts
- interfaces/HO-Portal/src/app/login/login.page.ts
- interfaces/HO-Portal/src/app/services/jwt.service.ts
- simplify JWT Service
- move all User-related logic into Auth.Service
- make isLoggedIn()-check REALLY check for a valid token
- check logged-in state on page-(re)load
- remove "ENTER to submit"-workaround
- fix bug where after log-out, credentials could be reused immediately
> Fix issues with HO login

- interfaces/HO-Portal/README.md
- interfaces/PA-App/README.md
- interfaces/README.md
@jannisvisser @RubenGeo :
I've added some links to documentation-sites that I use frequently, so maybe there are also useful links you can add for back-end dependencies/tools.
To get as much knowledge out of our heads and into something potential new developers can pick up and run with.
> Add documentation of third-party dependencies + links

- interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.html
- interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
See: https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/
> Use text input-type, to prevent input-quirks in some browsers

- tools/webhook.js
As it is fired multiple times per release/edit/publish and the production-VM isn't the fastest...
> Respond less often to Release-webhook events

- interfaces/AW-App/package.json
- interfaces/HO-Portal/package.json
- interfaces/PA-App/package.json
This will add a small delay of approx. 10 seconds to every time you run `npm start`, but it prevents build-failures of missing dependencies (and you don't have to check/decide manually if you need to update your environment).
(Only enabled for the interfaces now, but might be equally useful for the services.)
CC: @jannisvisser
> Install dependencies before starting, to have the latest code/state

- interfaces/AW-App/src/app/services/translatable-string.service.ts
- interfaces/HO-Portal/src/app/services/translatable-string.service.ts
- interfaces/PA-App/src/app/services/translatable-string.service.ts
> AB#3480 Handle empty-string as a valid value for a translatable string

- interfaces/AW-App/src/app/models/program.model.ts
- interfaces/AW-App/src/app/models/q-and-a.models.ts
- interfaces/AW-App/src/app/shared/phone-number-input/phone-number-input.component.html
- interfaces/AW-App/src/app/shared/phone-number-input/phone-number-input.component.ts
- interfaces/AW-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
- interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.html
- interfaces/AW-App/src/app/validation-components/validate-program/validate-program.component.ts
- interfaces/PA-App/src/app/mocks/api.program.mock.ts
- interfaces/PA-App/src/app/models/program.model.ts
- interfaces/PA-App/src/app/personal-components/enroll-in-program/enroll-in-program.component.html
- interfaces/PA-App/src/app/personal-components/set-notification-number/set-notification-number.component.ts
- interfaces/PA-App/src/app/shared/q-and-a-set/q-and-a-set.component.html
- services/121-service/seed-data/fsp/fsp-mixed-attributes.json
- services/121-service/seed-data/fsp/fsp-mobile-money.json
- services/121-service/seed-data/fsp/fsp-mpesa.json
- services/121-service/seed-data/program/program-anonymous1.json
- services/121-service/seed-data/program/program-anonymous2.json
- services/121-service/seed-data/program/program-demo.json
- services/121-service/seed-data/program/program-pilot-ken.json
- services/121-service/seed-data/program/program-pilot-nl.json
- services/121-service/src/programs/fsp/africas-talking.service.ts
- services/121-service/src/programs/program/dto/create-program.dto.ts
- services/121-service/src/programs/program/program.controller.spec.ts
- services/121-service/src/programs/program/program.entity.ts
- services/121-service/src/programs/program/program.service.ts
@elwinschmitz the problem was that the {{phoneNumberExample}} in set-notification-number was retrieved by looping over program-questions only. But if the program has no program phone number question, then the result was empty. I assessed (and discussed with Diderik) that given the theoretical possibility of phone number not being a program nor an FSP-question, it was logical to make it a program-attribute. Which is what I did.
Additionally I made the copy + (bold) styling of the phone number question label (more) aligned across the 3 different places it can occur now (program/fsp/notification). Where I took (your) 'set-notification-number' copy/styling as leading.
> AB#1518 review phonenumber validation

- interfaces/HO-Portal/src/app/program/program-people-affected/program-people-affected.component.html
- interfaces/HO-Portal/src/app/program/program-people-affected/program-people-affected.component.ts
@elwinschmitz see this unmerged PR which solves this
- I realize it's super-ugly (filtering on whether the 1st PA has a vnumber)
- but will work in practice (in kenya no-one has a vnumber, in nld it's a mandatory field)
- I tried cleaner solutions, by putting loadData before loadColumns, and then being able to loadColumns based on data, but this didn't seem possible.
- another downside is that we have less control of in what position the columns comes exactly
- anyway: if you think it's not full-proof and/or too ugly, feel free to not merge (and either improve or decide it's not worth it)
> AB#4378 don't show vnumber in kenya

- services/121-service/src/notifications/imagecode/image-code.service.ts
This changes: "8:5" into "08:05" for timestamps before 12-noon/before-10-minutes-past
> AB#6829 Fix time-format on generated voucher-image

- interfaces/PA-App/_check-icons-in-use.js
- interfaces/PA-App/angular.json
- interfaces/PA-App/src/app/services/update.service.ts
Related [AB#13731](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/13731)
> Fix: Use icon-name that exists in Ionicons v5+

- interfaces/HO-Portal/src/app/program/payment-history-accordion/payment-history-accordion.component.html
- interfaces/HO-Portal/src/app/program/payment-history-accordion/payment-history-accordion.component.scss
remove accordion functionality for 'not yet sent' payments.
remove old 'Payment overview' in the PA profile page.
remove 'not yet sent' clickable behavior.
> Changes after PR review

- services/121-service/src/notifications/twilio.dto.ts
- services/twilio-mock-service/src/twilio/twilio.dto.ts
fix: Add fallback to phone-number value to make the ENV-variables' existence non-blocking/breaking
> fix: Add fallback to phone-number in ENV-variable

- services/121-service/.eslintignore
fix: added `tmp` & `documentation` directory for lint ignore
> fix: added `tmp` & `documentation` for lint ignore

- services/121-service/README.md
- services/121-service/src/registration/registrations.controller.ts
- services/121-service/test/helpers/registration.helper.ts
- services/121-service/test/registrations/__snapshots__/import-registration.test.ts.snap
- services/121-service/test/registrations/import-registration.test.ts
This endpoint was accidentally removed in a previous commit. Adding it back.
> Add back missing endpoint for getting a CSV template from the portal

- .github/workflows/deploy_test_portal.yml
These comments have been polluting the PRs without (IMHO) adding much value, given that the deployment status information is already visible elsewhere on the GitHub UI.
Sadly, the Azure team is aware of this issue but isn't prioritising a fix for it: https://github.com/Azure/static-web-apps/issues/1135
The proposed solution seems hacky, but, if it works, it works.
> Disable spam comments from Azure on PRs

- docs/CONTRIBUTING.md
I feel like I've seen this happen a few times, and it's a sensible adjustment to make. I just hadn't foreseen it as a possible useful addition at the time of drafting the guidelines.
> Add exception to single-author-per-PR rule

- .github/workflows/test_e2e.yml
Based on @RubenGeo's suggestion I am extending the list of exclusions for the E2E tests job in CI to avoid running on changes to unit tests.
> Add exclusions to when E2E tests run

- interfaces/Portal/src/app/mocks/api.programs.mock.ts
- services/121-service/seed-data/program/program-demo.json
- services/121-service/seed-data/program/program-drc.json
- services/121-service/seed-data/program/program-eth-joint-response.json
- services/121-service/seed-data/program/program-joint-response-ANE.json
- services/121-service/seed-data/program/program-joint-response-EKHCDC.json
- services/121-service/seed-data/program/program-joint-response-dorcas.json
- services/121-service/seed-data/program/program-krcs-baringo.json
- services/121-service/seed-data/program/program-krcs-turkana.json
- services/121-service/seed-data/program/program-krcs-westpokot.json
- services/121-service/seed-data/program/program-nlrc-ocw.json
- services/121-service/seed-data/program/program-nlrc-pv.json
- services/121-service/seed-data/program/program-pilot-dorcas-eth.json
- services/121-service/seed-data/program/program-pilot-lbn.json
- services/121-service/seed-data/program/program-pilot-ukr.json
- services/121-service/seed-data/program/program-pilot-zoa-eth.json
- services/121-service/seed-data/program/program-validation.json
- services/121-service/src/registration/registrations.service.ts
- services/121-service/test/helpers/program.helper.ts
- services/121-service/test/registrations/import-registration.test.ts
fix: registrations not allowed without csv import if program is not published yet [AB#27479](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27479)
Task: https://dev.azure.com/redcrossnl/121%20Platform/_workitems/edit/27479
> fix: registrations not allowed without csv import if program is not published yet AB#27479

- services/121-service/test/registrations/send-templated-message.test.ts
This test keeps failing the whole API integration test job in CI. And then it works fine on a re-run. I don't have enough context to actually fix the test, but this at least should avoid this routine annoyance and waste of time :)
> Add retry to flaky API test

- .github/workflows/test_service_api.yml
[AB#27849](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27849)
This adds a check to our CI job, ensuring all entity changes are reflected in our migrations. The check adds ~12s to our API test job, which I consider an acceptable tradeoff.
I first rebased this on main to create an [example of a failing job](https://github.com/global-121/121-platform/actions/runs/8982798899/job/24671183512?pr=5258). The same job should pass fine when rebased on #5247.
> chore: add migrations check to CI

- interfaces/Portal/src/app/shared/message-editor/message-editor.component.ts
- services/121-service/src/notifications/message-job.dto.ts
- services/121-service/src/notifications/message.service.spec.ts
- services/121-service/src/notifications/message.service.ts
- services/121-service/src/notifications/processors/message.processor.spec.ts
- services/121-service/src/notifications/queue-message/queue-message.service.spec.ts
- services/121-service/src/notifications/queue-message/queue-message.service.ts
[AB#27909](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27909)
The fix itself is the change in `message-editor.component.ts`.
AFAIU, this has never worked. I tried checking out the commit that introduced that code (and apparently, the functionality) (764b065aed863458c3db545554f45d07f7d0dca8) and I could recreate the same exact bug.
While making these changes, I also refactored a few things:
- renamed `key` to `messageTemplateKey` wherever applicable
- Replaced if/else in `queue-message.service` with object lookup. This is always preferable for [speed and ease of readability](https://dev.to/b3ns44d/alternative-to-if-else-and-switch-object-literals-in-javascript-3nde)
~I'm not sure whether I should add a test for this, and how it would best be done.~ …
> fix: only English used in templated message

- interfaces/Portal/src/app/program/program-people-affected/program-people-affected.component.ts
The column for inclusionScore is now correctly displayed again and also appears in the filter then applicable to the program
> Fix: inclusionScore column & filter AB#27992

- .gitignore
- services/121-service/.npmrc
- services/121-service/Dockerfile
- services/121-service/package-lock.json
- services/121-service/package.json
- services/121-service/src/metrics/metrics.controller.ts
- services/121-service/src/notifications/queue-message/queue-message.service.ts
- services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.service.ts
- services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/processors/commercial-bank-ethiopia.processor.ts
- services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.service.ts
- services/121-service/src/payments/fsp-integration/intersolve-visa/processors/intersolve-visa.processor.ts
- services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
- services/121-service/src/payments/fsp-integration/intersolve-voucher/processors/intersolve-voucher.processor.ts
- services/121-service/src/payments/fsp-integration/safaricom/processors/safaricom.processor.ts
- services/121-service/src/payments/fsp-integration/safaricom/safaricom.service.ts
- services/121-service/src/payments/payments.controller.ts
- services/121-service/src/registration/const/filter-operation.const.ts
- services/121-service/src/registration/registrations.controller.ts
- services/121-service/src/registration/repositories/registration-scoped-base.repository.ts
- services/121-service/src/registration/services/registrations-pagination.service.ts
- services/121-service/src/scoped.repository.ts
- services/121-service/src/scripts/seed-eth-joint-response.ts
[AB#27996](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27996)
Updating TS to v5
> chore: update TypeScript to v5

- services/121-service/package-lock.json
- services/121-service/package.json
Merging the PR #5271 seems to have broken the service: https://121-test.scm.azurewebsites.net/api/vfs/LogFiles/2024_05_14_ln0mdlwk00005A_default_docker.log
Error along the lines of (while starting the service):
```
2024-05-14T14:09:10.174478723Z npm start
2024-05-14T14:09:10.174478723Z npm info using npm@9.6.4
2024-05-14T14:09:10.174721026Z npm info using node@v18.19.1
2024-05-14T14:09:10.202707456Z
2024-05-14T14:09:10.202758857Z > start
2024-05-14T14:09:10.202765857Z > GLOBAL_121_VERSION=$(test -f "VERSION.txt" && cat VERSION.txt || echo $GLOBAL_121_VERSION)  node index.js
2024-05-14T14:09:10.202770557Z
2024-05-14T14:09:10.344822639Z node:internal/modules/cjs/loader:1137
2024-05-14T14:09:10.344871540Z   throw err;
2024-05-14T14:09:10.344877840Z   ^
2024-05-14T14:09:10.344882140Z …
```
> Move Typescript to production dependencies for 121-service

- .github/actions/build-service/action.yml
- .github/workflows/test_workflows.yml
[AB#28086](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28086)
Looks like actionlint started ignoring the empty string and it didn't like it. This should make it stop complaining.
> fix: broken workflow check

- .github/workflows/test_e2e.yml
[AB#28271](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28271)
This should enable us to debug better what is happening if and when the portal server isn't starting in CI
> chore: adding portal server logs to CI job

- services/121-service/src/base-audited.entity.ts
- services/121-service/src/events/entities/event-attribute.entity.ts
- services/121-service/src/exchange-rate/exchange-rate.entity.ts
- services/121-service/src/financial-service-providers/fsp-question.entity.ts
- services/121-service/src/notifications/twilio.entity.ts
- services/121-service/src/notifications/whatsapp/whatsapp-pending-message.entity.ts
- services/121-service/src/notifications/whatsapp/whatsapp-template-test.entity.ts
- services/121-service/src/payments/fsp-integration/africas-talking/africas-talking-notification.entity.ts
- services/121-service/src/payments/fsp-integration/belcash/belcash-request.entity.ts
- services/121-service/src/payments/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia-account-enquiries.entity.ts
- services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa-customer.entity.ts
- services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa-wallet.entity.ts
- services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-issue-voucher-request.entity.ts
- services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.entity.ts
- services/121-service/src/payments/transactions/transaction.entity.ts
- services/121-service/src/programs/program-question.entity.ts
- services/121-service/src/programs/program.entity.ts
- services/121-service/src/registration/registration-data.entity.ts
- services/121-service/src/registration/registration.entity.ts
- services/121-service/src/user/user-role.entity.ts
- services/121-service/src/user/user.entity.ts
[AB#28379](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28379)
When enabling `strict: true`, typeorm is not able to coincile nullable properties on entities that don't explicitly have a type: https://github.com/typeorm/typeorm/issues/2567#issuecomment-408599335
It sucks that we have to do this, but I couldn't find a way around it.
> chore: add explicit type information to nullable properties

- services/121-service/src/registration/services/registrations-import.service.ts
- services/121-service/test-registration-data/test-registrations-patch-OCW-without-phoneNumber-column.csv
- services/121-service/test/registrations/mass-update-registration.test.ts
[AB#28262](https://dev.azure.com/redcrossnl/121%20Platform/_workitems/edit/28262)
During the mass update, if program is configured as not allowing empty phone number and the uploaded CSV file doesn't contain phoneNumber column, the it shouldn't complain about phone number not exists since we can consider, the already registered PAs have the phone number in database. if column exists and has some value for phoneNumber in uploaded CSV file then it should do the normal validation as it is.
> fix: fixed the bug related to phoneNumber validation AB#28262

- e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
In a separate branch, this test was failing, but I couldn't tell why.
Then I realised that the test was proceeding, even though an error occurred. That is because it pressed "ok" twice even if there was an error, without checking the label of what it was clicking "ok" on.
This should improve the messaging when it actually fails.
> chore: improve changePreferredLanguage test

- interfaces/Portal/src/app/components/status-table-filter/status-table-filter.component.ts
- interfaces/Portal/src/app/services/programs-service-api.service.ts
bug fix: Displaying "completed" status PAs on people affected page with others as default and adding a default sort as `registrationCreated` for pulled PAs data.
> fix: show completed status on people affected page and default sort as registrationCreated for PAs AB#28422

- e2e/pages/PhysicalCardOverview/PhysicalCardOverview.ts
- e2e/pages/RegistrationDetails/RegistrationDetailsPage.ts
- e2e/pages/Table/TableModule.ts
- e2e/tests/121-Portal/EditInfoPersonAffected/UpdatePaymentMultiplierInvalid.spec.ts
- e2e/tests/121-Portal/MakeNewPayment/OCW/MakeSuccessfulPaymentOCW.spec.ts
- e2e/tests/121-Portal/MakeNewPayment/OCW/PauseCardOCW.spec.ts
- e2e/tests/121-Portal/MakeNewPayment/OCW/ReIssueCardOCW.spec.ts
- e2e/tests/121-Portal/MakeNewPayment/OCW/ShowMaximumTotalAmountOCW.spec.ts
- e2e/tests/121-Portal/MakeNewPayment/PV/MakeSuccessfulPaymentPV.spec.ts
- e2e/tests/121-Portal/MakeNewPayment/PV/PauseCardPV.spec.ts
- e2e/tests/121-Portal/MakeNewPayment/PV/ReIssueCardPV.spec.ts
- e2e/tests/121-Portal/MakeNewPayment/PV/ShowMaximumTotalAmountPV.spec.ts
- e2e/tests/121-Portal/ViewPaProfilePage/ViewVisaDebitCardsTable.spec.ts
Adds Pause Visa Debit Card e2e test for both OCW and PV programme & edits the names of Payment related tests.
> AB#28415 add pause visa card test

- e2e/pages/PhysicalCardOverview/PhysicalCardOverview.ts
- interfaces/Portal/src/app/components/physical-card-popup/physical-card-popup.component.html
- interfaces/Portal/src/app/components/physical-card-popup/physical-card-popup.component.scss
- interfaces/Portal/src/app/components/registration-physical-card-overview/registration-physical-card-overview.component.html
- interfaces/Portal/src/app/components/registration-physical-card-overview/registration-physical-card-overview.component.scss
- interfaces/Portal/src/global.scss
- interfaces/Portal/src/styles/components/badge.css
[AB#28503](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28503)
fixes:
- replaced ion-chip with badge
- updated colors used in card status
- applied wrap to card name to prevent status badge clipping in smaller screens
> fix: physical card status color AB#28503

- services/121-service/package-lock.json
- services/121-service/package.json
- services/121-service/src/payments/imagecode/image-code.service.ts
[AB#28284](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28284)
- [Alert 291](https://github.com/global-121/121-platform/security/dependabot/291) solved by jimp update
- [Alert 424](https://github.com/global-121/121-platform/security/dependabot/424) solved by compodoc update
- [Alert 425](https://github.com/global-121/121-platform/security/dependabot/425) can't be fixed at the moment, the package needs to be patched properly
> chore: process dependabot security alerts AB#28284

- docs/CONTRIBUTING.md
> docs: Expand commit-message guidelines/examples

- interfaces/Portal/src/app/app.component.ts
- interfaces/Portal/src/app/auth/auth.service.ts
- services/.env.example
- services/121-service/src/user/user.controller.ts
- services/121-service/src/user/user.interface.ts
- services/121-service/src/user/user.service.ts
> feat: Add check for expired user-token to every initial page-load

- services/121-service/src/registration/dto/validate-registration-config.dto.ts
- services/121-service/src/registration/services/registrations-import.service.ts
- services/121-service/src/registration/validators/registrations-input-validator.ts
- services/121-service/test/registrations/__snapshots__/import-registration.test.ts.snap
- services/121-service/test/registrations/import-registration.test.ts
[AB#28574](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28574)
> fix: import 500 errors on null on dynamic attributes

- services/121-service/nest-cli.json
[AB#28624](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28624)
If you remove a typescript files the compiled js file remains in the dist folder. This can be annoying when creating and deleting migrations files. Now the way to fix this is: 1) delete dist folder 2) restart 121-service. With this commit you do not have to do 1 as it is done on startup
> Clean dist on start dev

- .github/workflows/test_e2e.yml
- Fail as early as possible with the 'lightest' tests (linting)
- Add some caching-steps to reuse effort of previous test-runs
> Improve speed of E2E-test runs

- services/121-service/package-lock.json
- services/121-service/package.json
- services/121-service/tsconfig.json
[AB#28807](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28807) 
During the strict branch efforts, we updated typescript to a beta version to get the latest features.
Now the stable version has been released, and we can stop using the beta.
> chore: update 121-service to Typescript@5.5.2

- .github/dependabot.yml
As we're working on "_the new Portal_", we can turn down the 'churn' of updates to the existing Portal.
> ci: Turn down frequency for Portal dependabot-updates

- services/121-service/test/helpers/assert.helper.ts
Lots of tests are failing like such:
https://github.com/global-121/121-platform/actions/runs/9713211869/job/26809966484
Apparently sometimes we are comparing strings, when we assume that we are always comparing objects. This can cause the order of the arrays to sometimes change, which I believe to be the source of the flakiness (for this particular test).
> chore: address (one of the) flaky test(s)

- interfaces/Portal/src/app/services/bulk-actions.service.ts
- interfaces/Portal/src/app/services/programs-service-api.service.ts
Enable the functionality to decline PAs with message. Also the message should should visible at PAs activity overview.
Task:  [29108](https://dev.azure.com/redcrossnl/121%20Platform/_workitems/edit/28988)
> feat: enable send message option during decline PAs AB#29108

- services/121-service/src/registration/registration.entity.ts
- services/121-service/src/user/user.service.ts
- services/121-service/test/users/__snapshots__/user-roles.test.ts.snap
- services/121-service/test/users/user-roles.test.ts
[AB#29126](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29126)
Adding some small improvements:
- better error handling when failing to create user roles - throw a 400 instead of 500
- add EventEntity to registration cascadeDelete to hopefully make it easier to delete programs
> chore: follow up from KRCS support

- .github/workflows/test_mock-service_code.yml
- .github/workflows/test_service_code.yml
- services/121-service/package.json
- services/mock-service/package.json
[AB#29095](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29095)
So, SWC [does not support type checking](https://swc.rs/docs/migrating-from-tsc#notes):
> SWC only transpiles the code and doesn't perform type checking. Therefore, it's recommended that you continue to use tsc for detecting any type errors.
NestJS does have a [type check flag](https://docs.nestjs.com/recipes/swc#type-checking). However, this isn't very useful because
- it checks types only when the server starts, and then never again on subsequent reloads
- the errors are hidden at the top of the logs
<details>
<summary>Expand me to see an example of the logs with a TS error and a reload</summary>
```console
➜ docker logs -f 121-service
> prestart:dev
> npm install --no-fund --no-audit …
```
> chore: add type checking to 121-service and mock-service scripts

- interfaces/Portal/src/app/shared/message-editor/message-editor.component.ts
See: [AB#29519](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29519)
The `??` is not doing what was expected, I think.
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing#using_the_nullish_coalescing_operator
> fix: Use explicit steps to get to a readable label for placeholders

- services/121-service/src/notifications/sms/sms.service.ts
[AB#29583](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29583) 
- Explicitly store that phonenumber is not available when attempting to send a message to people without phonenumber
- Another solution is to make the to column nullable... I though this was more explicit as it cannot be empty for whatsapp
> Fix store failure of empty phonenumber

- interfaces/Portalicious/.prettierrc.yml
- interfaces/Portalicious/.vscode/settings.json
- interfaces/Portalicious/src/app/pages/change-password/change-password.component.html
- interfaces/Portalicious/src/app/pages/login/login.component.html
- package-lock.json
- package.json
- Tailwind CSS extension in VSCode now has autocomplete on `styleClass` attributes (but, sadly, only when opening the `Portalicious` directory directly)
- Prettier also auto-sorts the `styleClass` attribute
> portalicious: add support for tailwind on primeng styleClass

- interfaces/Portalicious/src/app/pages/projects-overview/project-metric-container/project-metric-container.component.html
- interfaces/Portalicious/src/app/pages/projects-overview/project-summary-card/project-summary-card.component.html
Moving the text-styling to the "container of the data/skeleton", so the font-size can be reused/inherited by the skeleton
See [AB#29814](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29814)
I don't think this is "the best way forward", but I'd just didn't want to 'waste' my fiddling with the pixels. ;)
---
> fix: Reduce "layout shifting"/jumpiness of skeletons

- .github/release.yml
- .github/workflows/test_pull_request_formatting.yml
- docs/pull_request_template.md
[AB#29882](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29882)
This adds a CI job to all PRs on main that checks two things:
1. The PR should have a valid DevOps ID in the description
1. The PR should have one of the valid labels we use for auto-generating release notes.
If a PR is missing either (or both) of these things, it fails, with an error message such as this:
https://github.com/global-121/121-platform/actions/runs/10525330926?pr=5725
> chore: add PR metadata checker

- e2e/portalicious/pages/BasePage.ts
- e2e/portalicious/pages/ProjectTeam.ts
- e2e/portalicious/tests/ManageTeam/AllUsersAssignedShouldBeVisible.spec.ts
[AB#29863](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29863)
Wrapping up the work in #5714 so this can be merged as-is without waiting for the other tests.
> portalicious: add e2e to validate users in project team table

- interfaces/Portal/src/app/pages/login/login.page.html
[AB#30040](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30040)
- `-`  I have added tests wherever relevant
- `-` I have made sure that all automated checks pass before requesting a review
- `!` I do need some deviation from our PR guidelines  
The warning-text+link needs to be hard-coded, so users don't run into an issue with outdated/out-of-sync, cached translations-files.
> fix: Hard-code text+link to prevent translations-loading issue

- interfaces/Portalicious/src/app/components/query-table/query-table.component.html
- interfaces/Portalicious/src/app/domains/project/project.api.service.ts
- interfaces/Portalicious/src/app/pages/project/project-team/add-user-form/add-user-form.component.html
- interfaces/Portalicious/src/app/pages/project/project-team/add-user-form/add-user-form.component.ts
- interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.html
- interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.ts
- interfaces/Portalicious/src/app/pages/projects-overview/create-project-form/create-project-form.component.html
- interfaces/Portalicious/src/app/pages/projects-overview/create-project-form/create-project-form.component.ts
- interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.component.html
- interfaces/Portalicious/src/app/pages/projects-overview/projects-overview.component.ts
- interfaces/Portalicious/src/locale/messages.nl.xlf
- interfaces/Portalicious/src/locale/messages.xlf
- interfaces/Portalicious/src/styles.scss
[AB#29744](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29744)
When discussing with Elwin, we had settled on a different approach: The idea was to get rid of the separate component for managing the form and moving everything into the page.
When I started doing this, though, I realised that maybe there wasn't a need for it, and instead the only logic that needed to be moved to the page was whether to show the form or not.
So, I've also edited the "create-project-button" component accordingly so that they both follow the same pattern.
Still not sure if this is the wisest approach but it works.
EDIT: I also sneaked a couple of design fixes in there too.
> portalicious: edit user on teams page

- services/121-service/test/payment/do-payment-fsp-visa-debit/do-payment-fsp-visa-debit-error.test.ts
[AB#30109](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30109)
Fix flaky idempotency test, by resetting the registration to use before each test. Otherwise changes to the registration were carried over to the next test.
> fix: reset registration before each test AB#30109

- e2e/portalicious/tests/ChangePassword/ChangePasswordRedirect.spec.ts
- interfaces/Portalicious/staticwebapp.config.json
Original task: [AB#29275](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29275)
[AB#30179](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30179)
Password-managers can use this URL to help users to change their password (to a more secure one) when the password-manager detects a re-used or easily-guessed password, or it was found in a data-leak, etc.)
> feat: Add change-password redirect to help Password-managers

- e2e/playwright.config.ts
- e2e/portalicious/pages/ProjectTeam.ts
- e2e/portalicious/tests/ManageTeam/AllSystemUsersCanBeAddedToProjectTeam.spec.ts
- e2e/portalicious/tests/ManageTeam/AssignSuccessfullyRolesToUser.spec.ts
- e2e/portalicious/tests/ManageTeam/RemoveUserFromTeam.spec.ts
- services/121-service/src/scripts/scripts.controller.ts
- services/121-service/src/scripts/scripts.module.ts
- services/121-service/src/scripts/seed-helper.ts
- services/121-service/src/scripts/seed-program-test-one-admin.ts
- services/121-service/src/scripts/seed-script.enum.ts
- services/121-service/src/seed-data/organization/organization-one-admin.json
- services/121-service/src/seed-data/program/program-test-one-admin.json
[AB#30158](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30158) 
Tests against removing user from team
> Remove user from team

- interfaces/Portalicious/src/app/auth.guard.ts
- interfaces/Portalicious/src/app/components/page-layout/components/project-header/project-header.component.ts
- interfaces/Portalicious/src/app/pages/project/project-team/project-team.component.ts
- interfaces/Portalicious/src/app/services/auth.service.ts
[AB#30228](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30228)
- hasPermission now uses an object param
- added hasAllPermissions (will be used in activity log)
> portalicious: refactor hasPermission

- interfaces/Portal/src/app/services/programs-service-api.service.ts
- interfaces/Portalicious/src/app/domains/project/project.api.service.ts
- services/121-service/src/notes/dto/note.dto.ts
- services/121-service/src/notes/notes.controller.ts
- services/121-service/test/helpers/program.helper.ts
[AB#27711](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/27711) 
refactor notes endpoint(s)
> refactor note endpoint(s)

- interfaces/Portal/src/app/services/programs-service-api.service.ts
- interfaces/Portalicious/src/app/domains/project/project.api.service.ts
- services/121-service/src/notes/notes.controller.ts
- services/121-service/src/notes/notes.module.ts
- services/121-service/src/notes/notes.service.ts
- services/121-service/test/helpers/program.helper.ts
[AB#30463](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30463) 
After the refactor moving the /notes endpoint, a few additional "cleanliness" refactors while we are at it.
> Notes endpoints small refactors and refactor comments

- interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.html
- interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.ts
- interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
- interfaces/Portalicious/src/app/domains/project/project.api.service.ts
- interfaces/Portalicious/src/app/pages/project/project-team/project-team.page.html
- interfaces/Portalicious/src/app/pages/project/project-team/project-team.page.ts
- interfaces/Portalicious/src/locale/messages.nl.xlf
- interfaces/Portalicious/src/locale/messages.xlf
[AB#30503](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30503)
This refactor makes the assumption that confirmation dialogs will always be used with mutations, which I think is a fair assumption.
If we find a scenario where this isn't true, we can refactor / create an abstraction later.
> portalicious: handle mutation errors in confirmation dialog

- .github/workflows/test_pull_request_formatting.yml
- interfaces/Portalicious/src/app/domains/project/project.helper.ts
- interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
- interfaces/Portalicious/src/app/pages/project/project-registrations/project-registration-personal-information/project-registration-personal-information.page.ts
- services/121-service/src/registration/enum/custom-data-attributes.ts
[AB#30490](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30490)
> chore: fail PRs with XXX comments

- interfaces/Portalicious/src/locale/messages.nl.xlf
- interfaces/Portalicious/src/locale/messages.xlf
[AB#30165](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30165)
[AB#30395](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30395)
I combined these two tasks because I found one relying on the other, and figured that they wouldn't be a large set of changes even when combined.
The design of the "registration not found" deviates from what is in Figma based on a convo with Tal.
I also took the liberty of adding a "project not found" error.
> portalicious: add registrations breadcrumb and handle not found

- services/121-service/src/registration/services/registrations-pagination.service.ts
[AB#30719](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30719)
Regression introduced in nestjs-paginate:
https://github.com/ppetzold/nestjs-paginate/commit/25739bda711c98f7de673a049da1cdf55c8a96f6#diff-87404c91a22dbabcc334f9a5288341281cb2b6625533e1207efcac16dc1e2ffdR279
This is a temporary fix to solve the regression introduced above. TBD whether we need to adjust this code, adjust our code further, or submit a PR to nestjs-paginate.
> fix: referenceId mistakenly cast to number

- services/121-service/test/registrations/pagination/filter-registration.test.ts
[AB#30721](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30721)
API-test that would have caught the bug this item is based on.
> test: api test for referenceId as number

- interfaces/Portalicious/src/app/pages/users/add-user-form/add-user-form.component.ts
AB#30957
Must've slipped through the cracks with the renaming of the fields
> portalicious: fix users form

- services/121-service/module-dependencies.md
- services/121-service/src/activities/activities.controller.ts
- services/121-service/src/activities/activities.mapper.ts
- services/121-service/src/activities/activities.module.ts
- services/121-service/src/activities/activities.service.ts
- services/121-service/src/activities/dtos/activities.dto.ts
- services/121-service/src/activities/enum/activity-type.enum.ts
- services/121-service/src/activities/interfaces/base-activity.interface.ts
- services/121-service/src/activities/interfaces/data-change-activity.interface.ts
- services/121-service/src/activities/interfaces/financial-service-provider.interface.ts
- services/121-service/src/activities/interfaces/message-activity.interface.ts
- services/121-service/src/activities/interfaces/note-activity.interface.ts
- services/121-service/src/activities/interfaces/status-change-activity.interface.ts
- services/121-service/src/activities/interfaces/transaction-activity.interface.ts
- services/121-service/src/activities/types/activity.type.ts
- services/121-service/src/events/utils/events.mapper.ts
- services/121-service/src/payments/transactions/dto/get-audited-transaction.dto.ts
[AB#30664](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30664)
> feat.activities: dto mapping to endpoint

- interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.html
- interfaces/Portalicious/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
- interfaces/Portalicious/src/app/services/export.service.ts
- interfaces/Portalicious/src/locale/messages.nl.xlf
- interfaces/Portalicious/src/locale/messages.xlf
[AB#31005](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31005)
> portalicious: export duplicates

- interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.ts
[AB#31008](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31008)
> portalicious: add onDestroy -> unsubscribe to avoid memory leak

- services/121-service/src/migration/1708330965061-migrate-data-changes-to-event.ts
- services/121-service/src/migration/1708330966062-migrate-status-changes-to-event.ts
- services/121-service/src/migration/1713363871246-remove-startedRegistration-state.ts
- services/121-service/src/migration/1714467563401-remove-deleted-state-from-registration.ts
- services/121-service/src/migration/1729848646578-missing-program-fsp-confg-properties-seq.ts
- services/121-service/src/scripts/seed-mock-helpers.ts
- services/121-service/src/scripts/sql/mock-intersolve-voucher-attributes.sql
- services/121-service/src/scripts/sql/mock-make-phone-unique.sql
- services/121-service/src/scripts/sql/mock-payment-transactions.sql
- services/121-service/src/scripts/sql/mock-registration-data.sql
- services/121-service/src/scripts/sql/mock-registrations.sql
- services/121-service/src/scripts/sql/mock-transations-one-per-registrations.sql
- services/121-service/src/scripts/sql/mock-visa-customers.sql
- services/121-service/src/seed-data/mock/registration-pv.data.ts
[AB#31016](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31016)
make seed mock script work again
> fix: make seed mock script work again

- services/121-service/src/financial-service-providers/financial-service-provider.controller.ts
- services/121-service/src/guards/authenticated-user.decorator.ts
- services/121-service/src/notes/notes.controller.ts
- services/121-service/src/programs/fsp-configuration/fsp-configuration.controller.ts
- services/121-service/src/programs/programs.controller.ts
- services/121-service/src/registration/registrations.controller.ts
- services/121-service/src/user/user.controller.ts
[AB#30959](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30959) 
Add forbidden and unauth http codes to all swagger endpoints
> Add forbidden and unautherized to all endpoint swagger docs

- interfaces/Portalicious/src/app/domains/domain-api.service.ts
- interfaces/Portalicious/src/app/domains/metric/metric.api.service.ts
- interfaces/Portalicious/src/app/domains/metric/metric.model.ts
- interfaces/Portalicious/src/app/domains/project/project.api.service.ts
- interfaces/Portalicious/src/app/domains/project/project.model.ts
- interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
- interfaces/Portalicious/src/app/pages/project-monitoring/project-monitoring.page.ts
- interfaces/Portalicious/src/app/pages/project-registrations/components/custom-message-preview/custom-message-preview.component.ts
- interfaces/Portalicious/src/app/pages/projects-overview/components/project-summary-card/project-summary-card.component.ts
- interfaces/Portalicious/src/app/services/http-wrapper.service.ts
- interfaces/Portalicious/src/app/services/paginate-query.service.spec.ts
- interfaces/Portalicious/src/app/services/paginate-query.service.ts
[AB#31036](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31036)
On some requests in the export functionality, the same request + http parameters were being sent to the backend, even when the http parameters being used to make the request in the service were different.
I started by changing the `generateQueryOptions` function to have an exhaustive list of query keys, thinking that the lack of `requestOptions` in this array was the culprit.
It was not.
So then I refactored the `HttpWrapper.performRequest` to only accept HttpParam _objects_ instead of HttpParam _class instances_. My thinking here was that tanstack-query was struggling to serialize class instances as opposed to objects.
This was partially true, but did not solve the problem entirely.
I …
> portalicious: fix request caching

- services/121-service/test/registrations/__snapshots__/update-chosen-fsp.test.ts.snap
- services/121-service/test/registrations/update-chosen-fsp.test.ts
[AB#31025](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31025)
3 API-tests on switching chosen FSP
> test: api-tests on update chosen fsp AB#31025

- interfaces/Portalicious/src/app/domains/financial-service-provider/financial-service-provider.model.ts
- interfaces/Portalicious/src/app/domains/health/health.model.ts
- interfaces/Portalicious/src/app/domains/metric/metric.model.ts
- interfaces/Portalicious/src/app/domains/notification/notification.model.ts
- interfaces/Portalicious/src/app/domains/payment/payment.model.ts
- interfaces/Portalicious/src/app/domains/project/project.model.ts
- interfaces/Portalicious/src/app/domains/registration/registration.model.ts
- interfaces/Portalicious/src/app/domains/role/role.model.ts
- interfaces/Portalicious/src/app/domains/user/user.model.ts
- interfaces/Portalicious/src/app/services/paginate-query.service.ts
- interfaces/Portalicious/src/app/utils/dto-type.ts
- services/121-service/src/health/dto/get-version.dto.ts
- services/121-service/src/health/health.controller.ts
- services/121-service/src/payments/dto/get-payments.dto.ts
- services/121-service/src/payments/payments.controller.ts
- services/121-service/src/payments/payments.service.ts
[AB#31183](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31183)
The issues we are having on feature branches are related to the use of Dto121Service, where we import directly from the controllers, and end up (for reasons unbeknownst to me) in a situation where TS can't resolve these kinds of imports:
```bash
~/git/121-platform/interfaces/Portalicious ➜ npm run typecheck
> typecheck
> npx tsc --noEmit
../../services/121-service/src/registration/repositories/registration-scoped.repository.ts:14:45 - error TS2307: Cannot find module 'typeorm/query-builder/QueryPartialEntity' or its corresponding type declarations.
14 import { type QueryDeepPartialEntity } from 'typeorm/query-builder/QueryPartialEntity';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
> portalicious: remove Dto121Service

- e2e/portalicious/pages/RegistrationActivityLogPage.ts
- e2e/portalicious/pages/RegistrationsPage.ts
- e2e/portalicious/pages/TableComponent.ts
- e2e/portalicious/tests/SendMessage/SendCustomMessage.spec.ts
- e2e/portalicious/tests/SendMessage/SendTemplatedMessage.spec.ts
- interfaces/Portalicious/src/app/components/query-table/query-table.component.html
- interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
- interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.html
- services/121-service/test/registrations/pagination/pagination-data.ts
[AB#31175](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31175) 
Adds e2e tests for portalicious send message functionality
> Add send messages e2e test

- interfaces/Portalicious/src/app/domains/domain-api.service.ts
- interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
- interfaces/Portalicious/src/app/pages/login/components/cookie-banner/cookie-banner.component.html
- interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
- interfaces/Portalicious/src/app/services/auth/strategies/basic-auth/basic-auth.login.component.html
[AB#31193](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31193)
- Fix issue that "clear filters" does not work (fixed in domain-api.service)
- Fix issue that selecting registrations after right-clicking on a registration adds an extra selection by mistake to the count (fixed in project-registrations page)
- Fixed wrong email address in login page (because why not it was low hanging fruit)
This is a reminder that re-using objects & arrays rather than re-creating them can lead to werid behaviour :sweat_smile:
> portalicious: table fixes

- .vscode/settings.json
- e2e/portalicious/pages/RegistrationsPage.ts
- e2e/portalicious/tests/SendMessage/CorrectSelectionCountForMultiplePas.spec.ts
- e2e/portalicious/tests/SendMessage/CorrectSelectionCountForSinglePa.spec.ts
- interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.html
[AB#31181](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31181) 
Adds E2E tests of the count of selected PAs for the bulk action.
> Add test cases for selection behaviour

- interfaces/Portalicious/src/app/components/card-summary-metrics-container/card-summary-metrics-container.component.html
- interfaces/Portalicious/src/app/components/card-summary-metrics-container/card-summary-metrics-container.component.ts
- interfaces/Portalicious/src/app/components/metric-container/metric-container.component.html
- interfaces/Portalicious/src/app/components/metric-container/metric-container.component.ts
- interfaces/Portalicious/src/app/domains/metric/metric.model.ts
- interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.html
- interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
- interfaces/Portalicious/src/app/pages/projects-overview/components/project-summary-card/project-summary-card.component.html
- interfaces/Portalicious/src/app/pages/projects-overview/components/project-summary-card/project-summary-card.component.ts
- interfaces/Portalicious/src/locale/messages.nl.xlf
- interfaces/Portalicious/src/locale/messages.xlf
[AB#30918](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30918)
> Portalicious: refactor aggregates card AB#30918

- interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
- interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
- interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
- interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
- interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
- interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
[AB#31335](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31335)
Moving the registrations table into a separate component so that it can easily be re-used by the "do payment" flow
> portalicious: registrations table component

- services/121-service/src/strategies/azure-ad.strategy.ts
- services/121-service/src/strategies/cookie-jwt.strategy.ts
- services/121-service/src/user/user.service.ts
[AB#31311](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31311) 
This query is called every time a user validate (so basically every request), but it is getting unneeded data. So I changed it.
> Do not get unneeded data on every request

- .github/dependabot.yml
[AB#31229](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31229) / [AB#31508](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31508)
As to reduce the noise in the PRs-list and to reduce the load on the automated-tests-queue, we can reduce the interval of Dependabot checking our dependencies a bit.
This will result in some PRs to check at least every-other-sprint; Instead of 2-times-per-sprint.
We can still trigger checks manually by reopening a Dependabot-PR, or by just running `npm outdated` in some of our sub-folders etc.
> feat: Reduce churn of Dependabot PRs

- interfaces/Portal/src/app/program/program-people-affected/program-people-affected.component.ts
[AB#31513](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31513) 
Sanne reported that the inclusion score column is always visible. Not sure where/when the bug originated from. This fix ignores the empty scoring objects.
> fix: ignore empty scoring objects

- services/mock-service/src/twilio/twilio.service.ts
[AB#31500](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31500)
Let's mock send message fail when no phonenumber again.
> fix: mock message should fail without phonenumber

- interfaces/Portalicious/src/app/components/confirmation-dialog/confirmation-dialog.component.html
- interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-voucher-dialog/activity-log-voucher-dialog.component.html
- interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
- interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.html
- interfaces/Portalicious/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.html
[AB#31449](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31449)
Given that sometimes we don't want `esc` to close dialogs, this makes it consistent for all.
I couldn't find a way to set this "globally" for all components - without wrapping the primeng component but IMHO that is overkill for a single attribute.
It would've been nice to enforce this via eslint, but it depnds on this proposal: https://github.com/angular-eslint/angular-eslint/discussions/1800
I tried doing it with the html eslint plugin, but I don't think that can co-exist with the angular-eslint plugin.
For now we'll have to track this manually I suppose.
> portalicious: consistent "esc" behaviour on dialogs

- interfaces/Portal/src/app/program/export-fsp-instructions/export-fsp-instructions.component.ts
- services/121-service/src/payments/dto/fsp-instructions.dto.ts
- services/121-service/src/payments/payments.controller.ts
- services/121-service/src/payments/payments.service.ts
[AB#31608](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31608) [AB#31609](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31609)
While working on Portalicious, I realised there was logic in the Portal and the backend that isn't being used anywhere.
- removes unused ExportFileType
- removes unnecessary CsvInstructions
- updates the Portal and service code accordingly
Also adding a new endpoint that makes polling for this specific information easier
- adds programs/:programId/payments/:payment/status
I combined the above into a single PR because they are both small changes, and they are already sharded off of #6154, but I can split into two separate PRs if necessary / useful.
> feat: refactor FSPInstructions and add payment status endpoint

- services/121-service/src/strategies/azure-ad.strategy.ts
[AB#31489](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31489) 
I've checked the Portal code if it depends on this specific string. It doesn't, so I'm assuming this is fine to change.
> fix: dont return user in 401 azure-ad.strategy

- services/121-service/src/user/user.service.ts
[AB#31950](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31950)
> Better error on creating users

- services/121-service/src/registration/modules/registration-data/registration-data.module.ts
- services/121-service/src/registration/modules/registration-data/repositories/registration-data.scoped.repository.ts
[AB#32000](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32000) 
Fixed the attached bug. It happens because registrationData was made scoped twice
> Fix double scoped repo

- interfaces/Portalicious/src/app/components/form/form-default.component.html
- interfaces/Portalicious/src/app/pages/auth-callback/auth-callback.page.html
- interfaces/Portalicious/src/locale/messages.nl.xlf
- interfaces/Portalicious/src/locale/messages.xlf
[AB#31976](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31976) [AB#31977](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31977)
> Chore: process feedback Portalicious SSO

- interfaces/Portalicious/src/app/components/query-table/query-table.component.ts
- interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
- interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
- interfaces/Portalicious/src/app/domains/metric/metric.api.service.ts
- interfaces/Portalicious/src/app/domains/metric/metric.model.ts
- interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
- interfaces/Portalicious/src/app/pages/project-payment/components/retry-transfers-dialog/retry-transfers-dialog.component.html
- interfaces/Portalicious/src/app/pages/project-payment/components/retry-transfers-dialog/retry-transfers-dialog.component.ts
- interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
- interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
- interfaces/Portalicious/src/app/services/paginate-query.service.ts
- interfaces/Portalicious/src/locale/messages.nl.xlf
- interfaces/Portalicious/src/locale/messages.xlf
[AB#31728](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31728)
To implement the retry transfers feature, I had to do a few other things: 
- Remove the deleted registrations from the payment details table. TBD whether this will be permanent.
- Refactor query-table to include "getActionData" (which was previously only used on the registrations table)
> portalicious: retry transfers

- interfaces/Portalicious/eslint.config.js
- interfaces/Portalicious/src/app/components/file-upload-control/file-upload-control.component.html
- interfaces/Portalicious/src/app/components/import-file-dialog/import-file-dialog.component.html
- interfaces/Portalicious/src/app/components/import-file-dialog/import-file-dialog.component.ts
- interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.ts
- interfaces/Portalicious/src/app/domains/metric/metric.api.service.ts
- interfaces/Portalicious/src/app/domains/payment/payment.api.service.ts
- interfaces/Portalicious/src/app/pages/project-payment/components/import-reconciliation-data/import-reconciliation-data.component.html
- interfaces/Portalicious/src/app/pages/project-payment/components/import-reconciliation-data/import-reconciliation-data.component.ts
- interfaces/Portalicious/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.ts
- interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
- interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
- interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.html
- interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.ts
- interfaces/Portalicious/src/app/services/download.service.ts
- interfaces/Portalicious/src/locale/messages.nl.xlf
- interfaces/Portalicious/src/locale/messages.xlf
[AB#32154](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32154) [AB#32158](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32158)
> portalicious: import reconciliation data

- interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
[AB#32308](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32308)
After creating a new payment, the user should be redirected to the payment page. This was not working.
This does not address the originally reported bug in the linked bug item, but that is because the bug is _actually_ expected behaviour.
PS I also disabled the very annoying HTTP request logs
> portalicious: fix navigation post create-payment

- e2e/portalicious/pages/PaymentsPage.ts
- e2e/portalicious/pages/RegistrationsPage.ts
- e2e/portalicious/tests/DoPayment/DoSuccessfulPayment.spec.ts
- e2e/portalicious/tests/DoPayment/DoSuccessfulPaymentWithExcelFsp.spec.ts
- e2e/portalicious/tests/DoPayment/ShowPaymentSummary.spec.ts
- e2e/portalicious/tests/ExportPeopleAffectedList/ExportDuplicateRegistrations.spec.ts
- e2e/portalicious/tests/ExportPeopleAffectedList/ExportHighVolumeOfRegistrations.spec.ts
- e2e/portalicious/tests/ExportPeopleAffectedList/ExportRegistrationsDataChanges.spec.ts
- e2e/portalicious/tests/ExportPeopleAffectedList/ExportRegistrationsList.spec.ts
- e2e/portalicious/tests/ExportPeopleAffectedList/NoPermissionsForExport.spec.ts
- interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
- interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.html
- interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.html
- interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
- services/121-service/test/registrations/pagination/pagination-data.ts
[AB#31974](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/31974) 
Adds 2 tests:
- Successful payment
- Payment Summary
- Payment for Excel FSP
When I started writing those tests the details from Figma and deliverables were a bit different and did not include this screen:
Should this also be validated in the payment flow or is this a case for different test?
> Add e2e tests for do payment in portalicious

- services/121-service/src/payments/fsp-integration/intersolve-visa/mappers/visa-card-121-status-map.csv
- services/121-service/test/visa-card/issue-new-card.test.ts
[AB#32379](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32379) 
We did not take Substituted + blocked into account. In reality users usually block a card first and than reissue. Which results in this combi of statusses
> Substituded + blocked combi

- services/121-service/test/visa-card/contact-information-visa-card.test.ts
- services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.controller.ts
- services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts
[AB#32342](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32342)
> Api tests for update contact info

- .github/workflows/deploy_test_portalicious.yml
[AB#32463](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32463)
After merging #6349 I got an error that the job failed on main. I had misconfigured the extra step to _also_ run on pushes on main.
https://lively-river-04adce503-6350.westeurope.5.azurestaticapps.net
https://lively-river-04adce503-6350.westeurope.5.azurestaticapps.net
> portalicious: fix PR description job

- services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
[AB#32465](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32465)
balanceUsed was not updated on getVoucherBalance (from portal). Plus minor refactoring.
> fix: update balanceUsed on getVoucherBalance AB#32465

- services/121-service/package.json
- services/121-service/src/financial-service-providers/enum/financial-service-provider-name.enum.ts
- services/121-service/src/financial-service-providers/financial-service-providers-settings.const.ts
- services/121-service/src/migration/1734524945346-MakeProgramFspConfigNullableForeignKey.ts
- services/121-service/src/payments/payments.service.ts
[AB#32373](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32373)
Correct jumbo quick fix
> fix: revert jumbo quick fix + update fspconfigs FKs to NULL AB#32373

- services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts
[AB#32398](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32398) 
First merge in #6335 
- We had an error on main where tried to post this transfer amount to intersolve 1626.0000000000002
- This was caused by a [floating point error](https://ellenaua.medium.com/floating-point-errors-in-javascript-node-js-21aadd897bf8)
- To fix this I added a math.round() to ensure that we always post an integer
- I want to prevent that we reintroduce this error again in the future
- So I added to our mock service that it throws an error if you call it using a non-integer
-  Since floating point errors do not appear in a consistent way it's not straight forward to create an automated test for this
- But I think if we re-introduce this error again it will appear in our …
> Chore.throw error in mock

- services/121-service/test/registrations/pagination/filter-registration.test.ts
[AB#32508](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32508) 
> Generic attributes api test filtering all of them

- services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
- services/121-service/src/program-financial-service-provider-configurations/program-financial-service-provider-configurations.repository.ts
- services/121-service/test/helpers/intersolve-voucher.helper.ts
- services/121-service/test/payment/do-payment-fsp-voucher.test.ts
- services/121-service/test/voucher/get-balance.test.ts
[AB#32518](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32518)
3 commits build on each other
1. first got fspConfigId via registration (also in both bulk methods)
2. then optimized by not repeating queries in bulk methods unnecessarily
3. then realized, getting fspConfigId via registration may be incorrect if FSP changed along the way, so instead got via transaction.
> refactor: get balance via fspconfigid of registration AB#32518

- k6/models/initalize-payment.js
- k6/models/payments.js
- k6/tests/payment100kRegistrationOCW.js
- k6/tests/payment100kRegistrationSafaricom.js
- k6/tests/performanceDuringPayment.js
- k6/tests/retryFailedJobsOnStartupDuringQueueProcessing.js
- k6/tests/statusChangePaymentInLargeProgram.js
- services/121-service/src/queues-registry/queues-registry.service.ts
[AB#32515](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32515) 
Only merge if this [run](https://github.com/global-121/121-platform/actions/runs/12649769500) is succesful
> K6 floating point test visa

- services/121-service/src/registration/interfaces/validate-registration-error-object.interface.ts
- services/121-service/src/registration/validators/registrations-input-validator.spec.ts
- services/121-service/src/registration/validators/registrations-input-validator.ts
[AB#32503](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32503) 
> Max payments fix

- services/121-service/src/user/user.service.ts
[AB#32655](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32655) 
> return no access on non nummeric programIds

- interfaces/Portalicious/src/app/components/page-layout/components/registration-lookup-menu/registration-lookup-menu.component.html
- interfaces/Portalicious/src/app/components/page-layout/components/registration-lookup-menu/registration-lookup-menu.component.ts
- interfaces/Portalicious/src/app/pages/registration-lookup/registration-lookup.page.html
- interfaces/Portalicious/src/locale/messages.nl.xlf
- interfaces/Portalicious/src/locale/messages.xlf
[AB#32587](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32587)
https://lively-river-04adce503-6385.westeurope.5.azurestaticapps.net
> feat: Always show "no results" as fallback-content in Lookup-page

- interfaces/Portalicious/_build-deployment-configuration.mjs
- interfaces/Portalicious/_test-deployment-configuration.mjs
- interfaces/Portalicious/_verify-deployment-configuration.mjs
[AB#32724](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32724)
https://lively-river-04adce503-6388.westeurope.5.azurestaticapps.net
> feat: Allow control of pop-ups from iframes in Twilio Flex in config-builder

- services/.env.example
- services/121-service/module-dependencies.md
- services/121-service/src/app.module.ts
- services/121-service/src/cronjob/cronjob.module.ts
- services/121-service/src/cronjob/cronjob.service.ts
- services/121-service/src/exchange-rates/exchange-rates.api.service.ts
- services/121-service/src/exchange-rates/exchange-rates.controller.ts
- services/121-service/src/exchange-rates/exchange-rates.service.spec.ts
- services/121-service/src/exchange-rates/exchange-rates.service.ts
- services/121-service/swagger.json
- services/121-service/test/exchange-rates/exchange-rates.test.ts
- services/121-service/test/helpers/organization.helper.ts
- services/mock-service/src/app.module.ts
- services/mock-service/src/exchange-rates/exchange-rates-mock.controller.ts
- services/mock-service/src/exchange-rates/exchange-rates-mock.module.ts
- services/mock-service/src/exchange-rates/exchange-rates-mock.service.ts
[AB#32744](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32744) 
- Call exchange rate cronjob via endpoint
- Exchange rate mock -service 
- Exchange rate api service
> Chore.exhange rates api test

- interfaces/Portalicious/src/app/pages/snake/game/snake.component.html
- interfaces/Portalicious/src/app/pages/snake/game/snake.component.ts
- interfaces/Portalicious/src/locale/messages.nl.xlf
- interfaces/Portalicious/src/locale/messages.xlf
[AB#29807](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/29807)
https://lively-river-04adce503-6401.westeurope.5.azurestaticapps.net
> chore snake facts

- e2e/portalicious/pages/RegistrationsPage.ts
- e2e/portalicious/tests/ViewAndManagePeopleAffected/OpenRegistrationInNewTab.spec.ts
- interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
- interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
[AB#32871](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32871)
This is broken on test/production:
https://lively-river-04adce503-6411.westeurope.5.azurestaticapps.net
> portalicious: open registration in new tab

- services/121-service/src/payments/fsp-integration/nedbank/README.md
[AB#32896](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32896) 
The main feat.nedbank branch has not yet been merged but I think that in the spirit of small PRs it's fine to review and merge this seperately
> Nedbank cert readme.md

- .github/workflows/deploy_client-eswatini_all.yml
- .github/workflows/deploy_client-eswatini_portal.yml
- .github/workflows/deploy_client-eswatini_service.yml
[AB#32649](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32649)
> chore: create eswatini instance

- e2e/portalicious/pages/PaymentsPage.ts
- e2e/portalicious/tests/DoPayment/DoSuccessfulPayment.spec.ts
- e2e/portalicious/tests/ViewPayment/GraphDisplaysAllCorrectPaymentStatuses.spec.ts
- interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
- services/121-service/test/registrations/pagination/pagination-data.ts
[AB#32422](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32422) 
Adds test for checking correct display of payment statuses in the "Transfers data" graph.
https://lively-river-04adce503-6374.westeurope.5.azurestaticapps.net
> Add cherry picked test and dependencies

- services/121-service/src/registration/validators/registrations-input-validator.spec.ts
- services/121-service/src/registration/validators/registrations-input-validator.ts
- services/121-service/test/helpers/assert.helper.ts
- services/121-service/test/registrations/bulk-update-registration.test.ts
[AB#33084](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33084) [AB#33082](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33082) 
See github comments in the code 
> Fix allow empty string values for nonRequired dropdows

- services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.controller.ts
- services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.module.ts
- services/121-service/src/payments/reconciliation/intersolve-voucher-reconciliation/intersolve-voucher-reconciliation.service.ts
- services/121-service/swagger.json
[AB#33157](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33157) 
2 fixes in this PR:
- The cron endpoint url was changed in the cronjob service but no in at the actual endpoint
- The unused voucher cronjob tries to access the [0] element always (also if it's an empty array)
> 121-service fix: rename endpoint & check for array

- e2e/portalicious/components/TableComponent.ts
- e2e/portalicious/pages/RegistrationsPage.ts
- interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.html
[AB#33151](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33151)
https://lively-river-04adce503-6438.westeurope.5.azurestaticapps.net
> portalicious: registrations are not deselected after performing an action

- interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.html
- interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-submit-buttons/change-status-submit-buttons.component.html
[AB#33160](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33160)
I checked out the original commit where these modals were added: 49d028e4a4e38c008c2d9c6ca82fd48939fca6ff
And it seems this was always broken. I remember that, when we built this originally, me and Peter went through several refactors. I suppose this slipped through the cracks at the time.
The fix is mainly the `(cancelClick)="cancelClick()"` change. The other change is a design fix related to the same buttons.
https://lively-river-04adce503-6448.westeurope.5.azurestaticapps.net
> portalicious: fix change status "cancel" button

- interfaces/Portalicious/src/app/services/auth/strategies/basic-auth/basic-auth.change-password.component.html
[AB#30007](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/30007)
I had a look at a lot of forms, and I think with the theming efforts the consistency around validation is there now.
This was the only scenario that was a bit funky, but it's also the only page where we're using ValidatorFn (because of multi-field validation) so it needs this extra nudge.
https://lively-river-04adce503-6449.westeurope.5.azurestaticapps.net
> portalicious: fix validation on change password page

- interfaces/Portalicious/src/app/components/data-list/data-list.component.ts
- interfaces/Portalicious/src/app/pages/project-payment/components/project-payment-chart/project-payment-chart.component.ts
- interfaces/Portalicious/src/app/services/registration-attribute.service.ts
- interfaces/Portalicious/src/app/services/translatable-string.service.ts
[AB#32521](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32521)
https://lively-river-04adce503-6450.westeurope.5.azurestaticapps.net
> portalicious: rtl friendly comma separated lists

- interfaces/Portalicious/src/app/services/registrations-table-column.service.ts
[AB#33036](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33036)
https://lively-river-04adce503-6451.westeurope.5.azurestaticapps.net
> portalicious: default numeric attributes to zero in registrations table

- interfaces/Portalicious/src/app/domains/project/project.helper.ts
- interfaces/Portalicious/src/app/pages/project-payment/components/single-payment-export/single-payment-export.component.ts
- interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.html
[AB#32740](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/32740) 
https://lively-river-04adce503-6466.westeurope.5.azurestaticapps.net
> Fix Portalicious: show export payment report button

- .github/workflows/deploy_client-southafrica_all.yml
- .github/workflows/deploy_client-southafrica_portalicious.yml
[AB#33358](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33358) 
> chore: add South Africa portalicious workflow

- interfaces/Portalicious/src/app/domains/project/project.api.service.ts
- interfaces/Portalicious/src/app/domains/user/user.api.service.ts
- interfaces/Portalicious/src/app/pages/project-team/components/add-project-team-user-form/add-project-team-user-form.component.ts
- interfaces/Portalicious/src/app/pages/project-team/project-team.page.ts
- interfaces/Portalicious/src/app/pages/users/components/add-user-form/add-user-form.component.ts
- services/121-service/src/user/user.controller.ts
[AB#33439](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33439)
https://lively-river-04adce503-6505.westeurope.5.azurestaticapps.net
> fix: Replace AllUsers-endpoint with Users-Search endpoint on Team-page

- .github/workflows/test_interface_portalicious.yml
[AB#33602](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33602)
In [this PR](https://github.com/global-121/121-platform/pull/6397/files#diff-6bdb3cad870fa068cdf8a3f152c8bb8f3170e8c8921b35e481ca6e42a6bb7a86R1369-R1370) we were able to merge a broken xlf file. This means that then the locale extractor script is broken (and potentially also the download translations flow?).
This shouldn't happen.
I think this broke in this PR https://github.com/global-121/121-platform/pull/6482 and more specifically, [this change](https://github.com/global-121/121-platform/pull/6482/files#diff-e13b3ee3c88f64c4a2ef68d917f7f97731b3f425ebed0cfbf8d08b037bf3ee3dL35-R47).
(Meanwhile the broken xlf file was fixed in https://github.com/global-121/121-platform/pull/6517)
--- …
> chore: portalicious CI not failing with broken translations

- interfaces/Portalicious/src/app/components/colored-chip/colored-chip.helper.ts
- interfaces/Portalicious/src/app/domains/registration/registration.helper.ts
- interfaces/Portalicious/src/app/domains/transaction/transaction.helper.ts
- interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
- interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
- interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/table-cell-overview.component.ts
- interfaces/Portalicious/src/locale/messages.xlf
[AB#33610](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33610)
This reduces some duplication, and inadvertently fixes the transaction statuses in the activity log which were incorrect.
https://lively-river-04adce503-6520.westeurope.5.azurestaticapps.net
> chore: refactor colored chip helpers

- interfaces/Portalicious/src/app/components/form/form-sidebar.component.html
- interfaces/Portalicious/src/app/components/form/form-sidebar.component.ts
- interfaces/Portalicious/src/app/components/page-layout/components/header/header.component.html
[AB#33223](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33223)
[AB#33599](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33599)
https://lively-river-04adce503-6516.westeurope.5.azurestaticapps.net
> Set focus on the first form-control, but preventing "too soon" validation-errors

- interfaces/Portalicious/src/app/components/registration-page-layout/components/add-note-form/add-note-form.component.ts
- interfaces/Portalicious/src/app/domains/registration/registration.api.service.ts
- interfaces/Portalicious/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
- interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.html
- interfaces/Portalicious/src/app/pages/project-registration-personal-information/project-registration-personal-information.page.ts
- interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
- interfaces/Portalicious/src/app/pages/project-registrations/components/import-registrations/import-registrations.component.ts
[AB#33731](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33731)
This makes sure that we invalidate cache for registration queries that rely on referenceId, as well as the queries that rely on registration.id
This was causing issues because the new "getDuplicates" endpoint (implemented in #6522) uses referenceId, and the cache for it was not being invalidated after editing personal information.
https://lively-river-04adce503-6530.westeurope.5.azurestaticapps.net
> fix: registration data cache invalidation

- .github/workflows/deploy_client-ethiopia_portal.yml
[AB#33740](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33740)
These secrets/vars need to be 'handed down' explicitly;
But this workflow-file was manually 'upgraded', so this step was overlooked. :'(
> fix: Hand over correct secrets/configuration values

- e2e/portalicious/tests/ViewPayment/ImportReconciliationDataForExcelFsp.spec.ts
- e2e/portalicious/tests/ViewPayment/RetryPaymentWithExcelFsp.spec.ts
- services/121-service/test/registrations/pagination/pagination-data.ts
[AB#33354](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33354) 
Tests flow of import reconciliation data.
> E2E test for reconciliation data import

- .github/workflows/test_k6.yml
- k6/helpers/registration-default.data.js
- k6/models/registrations.js
- k6/run-all-tests.sh
- k6/tests/findDuplicates100kRegistrations.js
- services/121-service/src/scripts/scripts.service.ts
[AB#33539](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33539) 
> K6 test for finding duplicates

- .github/workflows/test_k6.yml
- k6/helpers/registration-default.data.js
- k6/models/registrations.js
- k6/run-all-tests.sh
- k6/tests/findDuplicates100kRegistrations.js
- services/121-service/src/migration/1739551473017-duplicate-status.ts
- services/121-service/src/registration/const/filter-operation.const.ts
- services/121-service/src/registration/dto/duplicate-response.dto.ts
- services/121-service/src/registration/enum/duplicate-status.enum.ts
- services/121-service/src/registration/interfaces/get-duplicates-result.interface.ts
- services/121-service/src/registration/registration-view.entity.ts
- services/121-service/src/registration/registrations.controller.ts
- services/121-service/src/registration/registrations.service.ts
- services/121-service/src/registration/repositories/registration-scoped.repository.ts
- services/121-service/src/registration/services/registrations-pagination.service.ts
- services/121-service/src/registration/validators/registrations-input-validator.spec.ts
- services/121-service/src/registration/validators/registrations-input-validator.ts
- services/121-service/src/scripts/scripts.service.ts
- services/121-service/src/scripts/seed-mock-helpers.ts
- services/121-service/src/scripts/seed-multiple-nlrc-mock.ts
- services/121-service/src/scripts/sql/mock-introduce-duplicates.sql
- services/121-service/swagger.json
- services/121-service/test/helpers/registration.helper.ts
- services/121-service/test/registrations/bulk-update-registration.test.ts
- services/121-service/test/registrations/duplicates/get-duplicates.test.ts
- services/121-service/test/registrations/duplicates/get-registration-duplicate-status.test.ts
[AB#33530](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33530) [AB#33533](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33533) [AB#33540](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33540) 
This PR adds:
- duplicates status in get registrations endpoint
- get duplicates endpoint to get duplicate information per registration
- integration tests to test them both
> Duplicates backend & integration tests

- services/.env.example
- services/121-service/src/registration/registrations.service.ts
- services/121-service/src/registration/validators/registrations-input-validator.spec.ts
- services/121-service/src/registration/validators/registrations-input-validator.ts
[AB#33713](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33713) [AB#33701](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33701) 
Send contact info to intersolve for intersolve attributes only & make validations of registration updates more consistent
See[ bug item](https://dev.azure.com/redcrossnl/121%20Platform/_sprints/taskboard/121%20Development%20Team/121%20Platform/Sprint%20148?System.State=Flagged%2CIn%20Progress%2CNew%2CReady%2CReview%2CTo%20Do&workitem=33701)
> Fix validation consistency of null values & send contact info to intersolve for intersolve attributes only

- interfaces/Portalicious/eslint.config.js
- interfaces/Portalicious/src/app/app.config.ts
- interfaces/Portalicious/src/app/components/privacy/privacy-copy-no-tracking.component.ts
- interfaces/Portalicious/src/app/components/privacy/privacy-copy-tracking.component.ts
- interfaces/Portalicious/src/app/pages/privacy/privacy.page.html
- interfaces/Portalicious/src/app/pages/privacy/privacy.page.ts
- interfaces/Portalicious/src/app/services/tracking.service.ts
[AB#33897](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33897)
Following up on the work done by @elwinschmitz in #6535 - I decided to refactor some of the conditions into a separate service, similarly to what was done with the authservice, so that the application as a whole is unaware (and does not care) whether Matomo is enabled / configured for the current instance.
https://lively-river-04adce503-6539.westeurope.5.azurestaticapps.net
> chore: add tracking service to portalicious

- services/121-service/src/payments/fsp-integration/intersolve-visa/intersolve-visa.api.service.ts
- services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.controller.ts
- services/mock-service/src/fsp-integration/intersolve-visa/intersolve-visa.mock.service.ts
[AB#33427](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33427) 
I tested this locally against the mock service of intersolve and it seemed to work fine
> Intersolve visa physical card data endpoint change (Merge after 26 of February)

- interfaces/Portalicious/src/app/domains/registration/registration.model.ts
- interfaces/Portalicious/src/app/pages/project-registrations/project-registrations.page.ts
- interfaces/Portalicious/src/app/services/registration-action-menu.service.ts
[AB#33898](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/33898) 
Moved logic from to project-registrations.page to seperate service. Refactor to prepare for the introcution of an actions menu on the profile page
https://lively-river-04adce503-6538.westeurope.5.azurestaticapps.net
> Refactor move logic to registration action menu service

- interfaces/Portalicious/src/app/components/query-table/components/query-table-column-management/query-table-column-management.component.ts
- interfaces/Portalicious/src/locale/messages.xlf
[AB#34011](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34011)
https://lively-river-04adce503-6559.westeurope.5.azurestaticapps.net
> fix: unresponsive if no columns selected in table

- services/.env.example
- services/121-service/README.md
[AB#34160](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34160) 
Docker Compose will read the `FORCE_COLOR` environment variable from the host which Jest will use to color the test
> chore: run Jest with colors

- interfaces/Portalicious/src/app/app.routes.ts
- interfaces/Portalicious/src/app/pages/registration-by-reference-id/registration-by-reference-id.page.html
- interfaces/Portalicious/src/app/pages/registration-by-reference-id/registration-by-reference-id.page.ts
[AB#34373](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34373)
Adding a new endpoint like this:
`/en-GB/project/:projectId/registration-by-reference-id/:referenceId`
https://lively-river-04adce503-6608.westeurope.5.azurestaticapps.net
> feat: registration-by-reference-id endpoint

- interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.html
[AB#34366](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34366) 
Show nothing if registration has no debit cards instead of an infinite loading state
https://lively-river-04adce503-6607.westeurope.5.azurestaticapps.net
> Show nothing if debit  card is empty

- .vscode/settings.json
- interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
[AB#34382](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34382)
I'm also sneaking in a settings.json change. This exception is seemingly not necessary anymore (I think because of a fix in the Angular Language Service extension). This means that clicking through on components in a template should work again.
https://lively-river-04adce503-6630.westeurope.5.azurestaticapps.net
> feat: change position of fail reason in activity overview

- services/.env.example
- services/121-service/src/cronjob/cronjob.service.ts
- services/121-service/src/payments/fsp-integration/intersolve-voucher/dto/remove-deprecated-image-codes-dto.ts
- services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.controller.ts
- services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.service.ts
- services/121-service/src/payments/imagecode/image-code.service.ts
- services/121-service/src/shared/services/custom-http.service.ts
- services/121-service/swagger.json
- services/121-service/test/helpers/program.helper.ts
- services/121-service/test/voucher/delete-deprecated-vouchers.test.ts
[AB#34346](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34346) [AB#34445](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34445) 
> Fix: remove image codes after a day instead of immidiately

- e2e/portalicious/tests/ChangeRegistrationStatus/MovePasFromCompletedToIncluded.spec.ts
- services/121-service/src/registration/services/registrations-import.service.ts
- services/121-service/src/registration/validators/registrations-input.validator.helper.spec.ts
- services/121-service/src/registration/validators/registrations-input.validator.helper.ts
[AB#34340](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34340) 
Registration data has been refactor to allow non required values (see isRequired in ProgramRegistrationAttributeEntity)
However for registration data of type boolean we would always revert to a default value 'false' if a registration was imported with the value not set. 
> Allow non required boolean values to be empty

- .github/actions/build-interface/action.yml
[AB#34716](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34716)
These steps where separated before, so they wouldn't share the ENV-variables.
That made the `build:production`-step(which now INCLUDES the `build:download-translations`!) assume the ENV-variables where not set, therefore set to "only create mock translations-files" (and thus overriding the previously downloaded production/real translations-files.)
Triggered manually: https://github.com/global-121/121-platform/actions/runs/14030759837/job/39277663600
https://new.portal.test.121.global/
> fix: Combine build-steps, so they share ENV-variables

- interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
(let the data-list.component handle the '-')
[AB#34773](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34773)
[AB#34789](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34789)
https://lively-river-04adce503-6658.westeurope.5.azurestaticapps.net
> fix: Only handle in numbers when using the currencyPipe

- .github/workflows/test_e2e_portalicious.yml
[AB#34724](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/34724)
The task/command `npm run build:download-translations` is now included into the generic `npm run build`-command, see https://github.com/global-121/121-platform/pull/6628
> fix: Reduce downloads of translations (in E2E-test runs)

- services/121-service/src/notifications/whatsapp/whatsapp.service.ts
- services/mock-service/src/twilio/twilio.controller.ts
- services/mock-service/src/twilio/twilio.service.ts
[AB#34877](https://dev.azure.com/redcrossnl/121%20Platform/_sprints/taskboard/121%20Development%20Team/121%20Platform/Sprint%20151?System.State=Flagged%2CIn%20Progress%2CNew%2CReady%2CReview%2CTo%20Do&workitem=34877)
Apparently when getting message using message sid the same bug occurs as with the return object. So instead of fetching the body using the messageSid this PR uses contentSid
> Body by content sid instead of message sid

- e2e/portalicious/components/TableComponent.ts
- e2e/portalicious/pages/RegistrationsPage.ts
- e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusCompleted.spec.ts
- e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusDeclined.spec.ts
- e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusIncluded.spec.ts
- e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusPaused.spec.ts
- e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusRegistered.spec.ts
- e2e/portalicious/tests/ChangeRegistrationStatus/DeleteRegistrationWithStatusValidated.spec.ts
- e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDate.spec.ts
- e2e/portalicious/tests/ViewFilterAndSortRegistrations/FilterRegistrationsByDropdownSelection.spec.ts
[AB#35094](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35094) 
Adds additional test steps for existing e2e tests "Filter by date" to allocate advanced filtering: Equals, less then, more then etc.
> E2E test for advanced filtering by date cherry pick

- e2e/portalicious/tests/DoPayment/ShowPaymentSummary.spec.ts
- interfaces/Portalicious/eslint.config.mjs
- interfaces/Portalicious/src/app/components/registrations-table/registrations-table.component.html
[AB#35373](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35373)
I haven't asked design for a review, even though it affects the UI, because this is using an existing design pattern which was already used on other pages.
https://lively-river-04adce503-6740.westeurope.5.azurestaticapps.net
> feat: default sort by registrationProgramId -> descending in registrations table

- .github/workflows/test_pull_request_formatting.yml
- interfaces/Portalicious/src/app/app.config.ts
- interfaces/Portalicious/src/app/components/data-list/data-list.component.html
- interfaces/Portalicious/src/app/pages/project-monitoring/project-monitoring.page.html
- interfaces/Portalicious/src/app/pages/project-payment/project-payment.page.ts
- interfaces/Portalicious/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
- interfaces/Portalicious/src/app/pages/project-payments/components/payment-summary-card/payment-summary-card.component.ts
- interfaces/Portalicious/src/app/pages/project-registration-activity-log/components/activity-log-expanded-row/activity-log-expanded-row.component.ts
- interfaces/Portalicious/src/app/pages/project-registration-activity-log/project-registration-activity-log.page.ts
- interfaces/Portalicious/src/app/pages/project-registration-debit-cards/project-registration-debit-cards.page.ts
- interfaces/Portalicious/src/app/pages/projects-overview/components/project-summary-card/project-summary-card.component.ts
[AB#35525](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35525) 
Transfer rows in `Activity log` always showed `EUR` as currency, because the actual currency wasn't added to those rows.
- Added the project currency to transfer rows in `Activity log` and to `Debit cards`
- Removed the fallback to `EUR` to every field using `CurrencyPipe`
- Added a global fallback to `XXX` so no currency is shown if it's missing from the Project settings
https://lively-river-04adce503-6763.westeurope.5.azurestaticapps.net
> fix: currency defaulting to EUR

- services/121-service/src/payments/reconciliation/commercial-bank-ethiopia-reconciliation/commercial-bank-ethiopia-reconciliation.controller.ts
- services/121-service/src/utils/soap/soap.service.ts
[AB#35563](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35563)
This would make the cron-triggered-endpoint *not* wait for the results of the loop...
So effectively moving the timeout-window from something controlled by the Nest.js-API to the Node-process...
And hopefully keep the Docker-logs in a sane shape...
> fix: Prevent timeout on CBE-endpoint triggered by Cronjob (to improve clarity in logs/monitoring)

- .github/workflows/test_interface_portalicious.yml
[AB#35606](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35606)
This will ONLY check for any changes to the `messages.xlf`-file.
So this will prevent any "false positives" triggered by other changes/errors/bugs. (These will be covered by other tests/fixes, see #6770)
Also, this removes the need/risk of using an external party for a relatively simple check/test.
> ci: Replace external diff-check with local, specific test for translations ONLY

- e2e/portalicious/helpers/PersonalInformationFields.ts
- e2e/portalicious/pages/RegistrationPersonalInformationPage.ts
- services/mock-service/src/fsp-integration/commercial-bank-ethiopia/commercial-bank-ethiopia.mock.controller.ts
[AB#35619](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35619)
As in this whole file there are 2 methods of this package used: `xml2js` AND `js2xml`... which looks to me as if the issue from the comment is already fixed...
> fix: Remove unclear/already-resolved/blocking comment

- .github/actions/build-interface/action.yml
- .github/workflows/deploy_client-benin_portal.yml
- .github/workflows/deploy_client-demo_portal.yml
- .github/workflows/deploy_client-drc_portal.yml
- .github/workflows/deploy_client-eswatini_portal.yml
- .github/workflows/deploy_client-ethiopia_portal.yml
- .github/workflows/deploy_client-greece_portal.yml
- .github/workflows/deploy_client-ivorycoast_portal.yml
- .github/workflows/deploy_client-jrethiopia_portal.yml
- .github/workflows/deploy_client-krcs_portal.yml
- .github/workflows/deploy_client-nigeria_portal.yml
- .github/workflows/deploy_client-nlrc_portalicious.yml
- .github/workflows/deploy_client-slovakia_portal.yml
- .github/workflows/deploy_client-somalia_portal.yml
- .github/workflows/deploy_client-southafrica_portal.yml
- .github/workflows/deploy_client-sudan_portal.yml
- .github/workflows/deploy_client-togo_portal.yml
- .github/workflows/deploy_client-training_portal.yml
- .github/workflows/deploy_client-zambia_portal.yml
- .github/workflows/deploy_staging_portalicious.yml
- .github/workflows/deploy_test_portalicious.yml
- .github/workflows/test_e2e_portalicious.yml
- interfaces/Portalicious/_build-download-translations.mjs
[AB#35632](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35632)
TopPrevent flaky build-steps...
- Disable download of translations in E2E-test runs
- Create cache of downloaded translations
- Will be re-used on multiple builds/deployments on the same day (test/staging-environment)
- Will be at least run once-per-day for production release/deploys (so once for first client, reuse for other clients)
https://lively-river-04adce503-6790.westeurope.5.azurestaticapps.net
> Reduce downloads of translations via cache-per-day + Disable async-downloading (for now)

- README.md
- package.json
[AB#35953](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35953)
When running 121-service locally it's helpful to see all the logs and to be able to quickly stop it. By *not* detaching it we:
- see the logs and keep seeing them in the terminal where we run `npm run start:services`
- can easily stop the 121-service by pressing Ctrl + c
It is possible to do both things using Docker commands, but then you need to take extra steps.
> chore: make 121-service start non-detached

- interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.html
- interfaces/Portalicious/src/app/pages/project-registrations/components/change-status-dialog/change-status-dialog.component.ts
- interfaces/Portalicious/src/locale/messages.xlf
[AB#35796](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/35796)
This applies to two scenarios:
1. Try to change a status and 0 registrations support the new status
2. Try to change a status and only some of the registrations support the new status
Previously, the error messages for these two scenarios were duplicated.
Now there is a variable `changeStatusWarningMessage` that is used in both scenarios.
I've also removed customised suggested actions for the warnings in both scenarios, making the suggested action more vague to avoid additional, IMHO unnecessary ifs.
In other words, in the following screenshots
- the text circled in red is customised per status (as it was before)
- the text circled in green is generic and does not change per status …
> fix: warning message when including included registrations

- e2e/portal/pages/RegistrationsPage.ts
- e2e/portal/tests/UpdateRegistrations/BulkUpdateOnlyVisibleForAdminPermissions.spec.ts
- e2e/portal/tests/UpdateRegistrations/BulkUpdateVisibleInActivityLog.spec.ts
- e2e/portal/tests/__screenshots__/UpdateRegistrations/BulkUpdateVisibleInActivityLog.spec.ts/exported-csv.csv
[AB#36625](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36625) 
Adds extra tests for bulk update:
1. CSV bulk update should be reflected in activity log
2. User does not have sufficient Role to bulk update with CSV (import modal not visible)
3. Column export should only include selected columns // (maybe)
https://happy-rock-0411d2003-6931.westeurope.3.azurestaticapps.net
> Add extra e2e tests for bulk update registrations

- services/121-service/test/event/filter-events.test.ts
- services/121-service/test/helpers/registration.helper.ts
- services/121-service/test/registrations/delete-registration.test.ts
- services/121-service/test/registrations/pagination/update-registration-status.test.ts
[AB#36898](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/36898) 
In the 121-service docker logs of the [failed api tests](https://github.com/global-121/121-platform/actions/runs/15773000731/job/44461262205) I found the followig event related errors: 
My assumption is, is the we reset the database while our 121-service is still trying to store events. The registrations in the database are than already gone due to the reset. Which is why that error is thrown in the screenshot and the server crashes.
To fix this I changed the `waitForStatusChangeToComplete` to wait for the registration status change events to be created instead of waiting for the moment that registration.status changed. Because the events are created after the registrations status …
> Test flakiness: wait for events instead of changed registrations

- services/121-service/test/helpers/registration.helper.ts
[AB#37009](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37009)
- when looking at a recent occurence of this here: https://github.com/global-121/121-platform/actions/runs/15972884791/job/45048604813#step:6:469
- I saw that a recent change actually caused the code to break on eventsResult.body.filter if eventsResult.body was not an array yet, instead of staying in the while loop until it was.
- So if directly an array, the test still passes, but if not, then it fails. This PR should solve that.
> fix: flaky do-payment-filter AB#37009

- .github/workflows/test_e2e_portal.yml
- .github/workflows/test_service_api.yml
- package.json
- services/121-service/Dockerfile
- services/docker-compose.development.yml
- services/docker-compose.yml
- services/mock-service/Dockerfile
[AB#37006](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37006)
Be explicit in each service's `Dockerfile`, to remove some confusion on "what this `localhost`-URL actually is".
To summarise/visualise:
- Inside a `Dockerfile` (inside the individual container), the container is 'known' as `localhost`, addressable to any port you `EXPOSE`
- So this address should be used for the health-check.
- We _could_ expose port `8080` for every service/container here...
- In a `docker-compose.yml`-file, you define something that 'wraps around some containers'.  
So in there, you can map the 'internal ports' to 'externally exposed ports'.  
This is what enables the URL `localhost:3000`(=your local development machine's `localhost`+the external port `3000`) to …
> refactor: Align Dockerfile(s) + define their own healthcheck

- services/121-service/src/kobo-connect/kobo-connect.service.ts
[AB#37113](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37113) 
A 500 error triggers an email. If we use this: 
```
throw new HttpException(
{
message: 'Kobo-Connect API did not return a result',
errors,
},
HttpStatus.INTERNAL_SERVER_ERROR,
);
```
instead of 
```
throw new Error()
```
we get an email but we see nothing in the logs. In this case we do not want to use a normal error because than our CVA_IM user will get no feedback because the errors are not returned to the caller. 
I therefore added a line to also log the error.
We could also argue it should be a bad request instead of an INTERNAL_SERVER_ERROR. But maybe we do want the email, i am not sure. But such a change could be a separate PR
> Also log kobo errors

- services/121-service/src/config.ts
- services/121-service/src/payments/fsp-integration/onafriq/services/onafriq.api.service.ts
[AB#37316](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37316) 
Since test uses the Onafriq sandbox API, it also needs the workaround to ignore the certificate error that we use on local.
> chore: also workaround onafriq sandbox cert error on test

- .github/workflows/test_e2e_portal.yml
- .github/workflows/test_service_api.yml
[AB#37303](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37303)
> ci: Make the path-filter external-action only run on PRs, to prevent confusing errors

- .github/workflows/test_e2e_portal.yml
- services/docker-compose.development.yml
[AB#37189](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37189)
Now that we're all running the development-stack on macOS, I think it is safe to remove the 'one-way shared volume' of the `node_modules`-folders.
This was supposed to 'speed up' the `watch`-type commands or to fix/prevent some other speed/performance issue...
But sometimes, after locally rebasing back on `main`, this was causing the need to run `npm i` in the `services/121-service`-folder an extra time, even if you already "created the Docker-containers from scratch"..
Now the `node_modules`-folder in the Docker-container should contain the same files as the local `node_modules`-folder. And each OS (Ubuntu from within the container; macOS from 'outside') should be able to use the same …
> refactor: Remove the extraneous volumes that require double installs of dependencies

- services/121-service/src/fsps/enums/fsp-name.enum.ts
- services/121-service/src/program-fsp-configurations/dtos/program-fsp-configuration-property-response.dto.ts
- services/121-service/src/program-fsp-configurations/mappers/program-fsp-configuration.mapper.ts
- services/121-service/src/program-fsp-configurations/program-fsp-configurations.controller.ts
- services/121-service/src/program-fsp-configurations/program-fsp-configurations.service.ts
- services/121-service/swagger.json
- services/121-service/test/helpers/program-fsp-configuration.helper.ts
- services/121-service/test/program/manage-program-fsp-configuration.test.ts
[AB#37617](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37617) 
Adds GET endpoint that returns only allowed/ visible properties of the FSP program configuration:
1. When visibility set to true: returns name and value
2. When visibility set to false: returns name and '[********]'
Adds integration tests:
1. For Visible properties
2. For Hidden properties
> Add GET endpoint for visible FspConfig properties

- services/121-service/src/program-fsp-configurations/mappers/program-fsp-configuration.mapper.ts
- services/121-service/src/program-fsp-configurations/program-fsp-configurations.controller.ts
- services/121-service/src/program-fsp-configurations/program-fsp-configurations.service.ts
- services/121-service/test/program/manage-program-fsp-configuration.test.ts
[AB#37703](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37703) 
- Fix: hidden properties still vissible on /api/programs/{programId}/fsp-configurations
- Refactor the code surrounding the hidden properties a bit
> Fix: hidden properties still vissible on /api/programs/{programId}/fsp-configurations

- services/121-service/src/payments/fsp-integration/airtel/dtos/airtel-api-disbursement-request-body.dto.ts
- services/121-service/src/payments/fsp-integration/airtel/services/__snapshots__/airtel.api.service.spec.ts.snap
- services/121-service/src/payments/fsp-integration/airtel/services/airtel.api.service.ts
[AB#37747](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37747) 
For the Airtel FSP integration, the disbursement payload apparently needs a value for `payee.name`.
> feat: Airtel - add (static) payee.name in payload

- services/121-service/module-dependencies.md
- services/121-service/src/activities/activities.service.ts
- services/121-service/src/migration/1755852548143-VoucherPaymentRelation.ts
- services/121-service/src/notifications/message-incoming/message-incoming.module.ts
- services/121-service/src/notifications/message-incoming/message-incoming.service.ts
- services/121-service/src/payments/fsp-integration/intersolve-voucher/intersolve-voucher.entity.ts
- services/121-service/src/payments/fsp-integration/intersolve-voucher/services/intersolve-voucher-cron.service.ts
- services/121-service/src/payments/reconciliation/nedbank-reconciliation/nedbank-reconciliation.service.ts
- services/121-service/src/payments/reconciliation/onafriq-reconciliation/onafriq-reconciliation.service.ts
- services/121-service/src/payments/reconciliation/safaricom-reconciliation/safaricom-reconciliation.service.spec.ts
- services/121-service/src/payments/reconciliation/safaricom-reconciliation/safaricom-reconciliation.service.ts
- services/121-service/src/payments/services/payments.service.spec.ts
- services/121-service/src/payments/services/payments.service.ts
- services/121-service/src/payments/transactions/transaction.repository.ts
- services/121-service/src/payments/transactions/transaction.scoped.repository.ts
- services/121-service/src/payments/transactions/transactions.module.ts
- services/121-service/src/payments/transactions/transactions.service.ts
- services/121-service/src/program-fsp-configurations/program-fsp-configurations.service.spec.ts
- services/121-service/src/transaction-jobs/services/transaction-jobs-airtel.service.spec.ts
- services/121-service/src/transaction-jobs/services/transaction-jobs-airtel.service.ts
- services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.spec.ts
- services/121-service/src/transaction-jobs/services/transaction-jobs-helper.service.ts
- services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.spec.ts
- services/121-service/src/transaction-jobs/services/transaction-jobs-nedbank.service.ts
- services/121-service/src/transaction-jobs/services/transaction-jobs-onafriq.service.spec.ts
- services/121-service/src/transaction-jobs/services/transaction-jobs-onafriq.service.ts
- services/121-service/src/transaction-jobs/services/transaction-jobs-safaricom.service.spec.ts
- services/121-service/src/transaction-jobs/services/transaction-jobs-safaricom.service.ts
[AB#37678](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37678)
- change logic of which unsent voucher to reply to incoming message to last 3 paymentIds for a registration (instead of using generic paymentId, which no longer worked)
- change logic of unsent voucher reminders to send to last 2 weeks instead of on generic minimum paymentId, which no longer worked.
> adapt logic of which AH vouchers / reminder to send to paymentId refactor

- e2e/portal/pages/PaymentPage.ts
- e2e/portal/pages/PaymentsPage.ts
- e2e/portal/tests/ViewPayment/PaymentInProgressVisible.spec.ts
- e2e/portal/tests/ViewPayment/ViewPaymentLog.spec.ts
- e2e/portal/tests/ViewPayment/ViewPaymentNote.spec.ts
- interfaces/portal/src/app/app.routes.ts
- interfaces/portal/src/app/components/data-list/data-list.component.html
- interfaces/portal/src/app/components/page-layout-payment/components/payment-menu/payment-menu.component.ts
- interfaces/portal/src/app/domains/payment/payment.api.service.ts
- interfaces/portal/src/app/domains/payment/payment.helpers.ts
- interfaces/portal/src/app/domains/payment/payment.model.ts
- interfaces/portal/src/app/pages/project-payment-log/components/table-cell-payment-event-activity.component.ts
- interfaces/portal/src/app/pages/project-payment-log/components/table-cell-payment-event-overview.component.ts
- interfaces/portal/src/app/pages/project-payment-log/project-payment-log.page.html
- interfaces/portal/src/app/pages/project-payment-log/project-payment-log.page.ts
- interfaces/portal/src/app/pages/project-payments/components/create-payment/create-payment.component.html
- interfaces/portal/src/app/pages/project-payments/components/create-payment/create-payment.component.ts
- interfaces/portal/src/app/pages/project-registration-activity-log/components/table-cell-activity.component.ts
- interfaces/portal/src/app/utils/unique-users.ts
- interfaces/portal/src/locale/messages.xlf
[AB#37700](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37700)
- This PR contains
- add payment note (front-end) > already approved by @elwinschmitz 
- view payment log (front-end) > all comments by @elwinschmitz are addressed or reverted to post-merge review task [AB#37776](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37776)
- e2e test combining both features above > to be reviewed 
For the post-merge review:
- Specific feedback welcome on naming, which I struggled with a bit. This rose partly from the following: the design of this log is exactly equal to the Registration Activities log. That one is called 'activities' because it is a combination of 'registration events' and other things (like payments). In …
> feat: add payment note and see payment log (front-end)

- e2e/README.md
- e2e/package.json
[AB#37791](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37791)
- e2e tests can fail because of a newline that is automatically added to snapshot csv's upon save (if that file is touched for another reason)
- in that case, it can be fixed by running the e2e test with --update-snapshots flag.
- Passing that flag was however not easily combinable with only running specific tests. This PR creates that option.
> chore: update snapshots of specific e2e files

- services/121-service/src/metrics/metrics.controller.ts
- services/121-service/src/metrics/metrics.service.ts
- services/121-service/src/payments/services/__snapshots__/payments-reporting.service.spec.ts.snap
- services/121-service/src/payments/services/payments-reporting.service.spec.ts
- services/121-service/src/payments/services/payments-reporting.service.ts
- services/121-service/src/registration/mappers/registration-views.mapper.spec.ts
- services/121-service/src/registration/mappers/registration-views.mapper.ts
[AB#37684](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37684) 
> We check for correct export type in both the metrics controller and the metrics service probably better to do that once.
Done
> `metrics.service:getRegistrationsList` is now only used by `getAllPeopleAffectedList`, no longer should be a separate method
I renamed the method names a bit. I think it's still valuable to have a seperate method
> `getRegistrationsGenericFields` should be moved under `getAllPeopleAffectedList` it's now in a weird position in the class
Done
> `etRegistrationsGenericFields` is called by only one function so it does not need to receive `exportType` (as it's always `registrations`), the conditional inside that function can then also be simplified
Done
in …
> Post merge review niels small changes

- interfaces/portal/src/app/services/auth.service.spec.ts
- interfaces/portal/src/app/services/auth.service.ts
[AB#37836](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37836)
- This change came out of the program-to-project rename work, where permissions (e.g. 'program:metrics.read) were also renamed. For logged in users after deploy, this would lead to portal where certain things are not visible (Monitoring page menu-item) or not work.
- After discussion [here](https://teams.microsoft.com/l/message/19:ce634fd37f34477d9f98391f70e1f0ef@thread.skype/1756730859255?tenantId=d3ab9790-6ae2-4bd8-aa5e-02864483e7c7&groupId=55f2fa49-7d9b-4c63-b616-b986f3136c3a&parentMessageId=1756730859255&teamName=510%20-%20CVA&channelName=121%20Development&createdTime=1756730859255) I in the end arrived at the 'force manual re-login' option. 
- I looked into the option of directly …
> feat: logout on deprecated permissions

- interfaces/portal/src/app/components/page-layout-payment/components/import-reconciliation-data/import-reconciliation-data.component.html
- interfaces/portal/src/app/components/page-layout-payment/components/import-reconciliation-data/import-reconciliation-data.component.ts
- interfaces/portal/src/app/components/page-layout-payment/components/single-payment-export/single-payment-export.component.ts
- interfaces/portal/src/locale/messages.xlf
- services/121-service/module-dependencies.md
- services/121-service/src/payments/payments.controller.ts
- services/121-service/src/payments/payments.module.ts
- services/121-service/src/payments/reconciliation/excel/excel-reconciliation.controller.ts
- services/121-service/src/payments/reconciliation/excel/excel-reconciliation.module.ts
- services/121-service/src/payments/reconciliation/excel/excel-reconciliation.service.spec.ts
- services/121-service/src/payments/reconciliation/excel/excel-reconciliation.service.ts
- services/121-service/src/payments/services/payments-excel-fsp.service.spec.ts
- services/121-service/src/payments/services/payments-excel-fsp.service.ts
[AB#37922](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37922)
- Now that payment with excel FSP is done via queue we don't await the initial storing of transactions any more like before.
- ~~To mitigate this, I block the 'export fsp instructions' while still in progress. I do this in the same way as was already done for import-reconciliation data.~~
- ~~It made sense to me to also block 'payment report' during this same time.~~
- After discussion, I changed this validation to back-end. The resulting back-end error is handled out of the box nicely in the front-end. 
- I removed the FE validation again and also the pre-existing one on import-reconciliation.
- I decided not to put any validation now on the 'export payment report', as it is in quite a …
> feat: block export fsp instructions while in progress

- services/121-service/package.json
- services/121-service/src/migration/1758014323364-PhoneNumberPaymentOnafriq.ts
[AB#38066](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38066)
- Data migration for phoneNumberPayment on DRC
- the package.json change was needed because migration:create was failing on unknown argument dataSource.
- This was tested on drc production data, and after this migration a local retry transfer indeed leads to a successful transaction.
- The plan and details were confirmed with Erna.
- I created a task in release item to check the data migration
> chore: data migration for phoneNumberPayment

- e2e/portal/tests/ViewPayments/ExportPayments.spec.ts
[AB#38159](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38159)
In #7106 the payments export changed the name of the payment ID column from `payment` to `paymentId`.
The snapshot was updated to reflect this change, but a piece of the test code was still relying on sorting the records based on `payment`.
This sort function was silently failing, introducing flakiness on the test.
Besides fixing the sort function, I've also added assertions to make sure that a change in column name would not go unnoticed again.
> chore: fix flaky ExportPayments test

- services/121-service/src/notifications/dto/twilio.dto.ts
- services/121-service/src/notifications/enum/twilio-error-codes.enum.ts
- services/121-service/src/notifications/message-incoming/message-incoming.service.ts
- services/121-service/src/notifications/sms/sms.service.ts
- services/121-service/src/notifications/whatsapp/whatsapp.service.ts
- services/121-service/src/payments/transactions/repositories/latest-transaction.repository.ts
- services/121-service/src/payments/transactions/transactions.service.ts
- services/121-service/src/registration/modules/registration-utilts/registration-utils.service.ts
- services/121-service/src/shared/enum/postgres-status-codes.enum.ts
- services/121-service/src/user/user.service.ts
- services/121-service/src/utils/comparison.helper.spec.ts
- services/121-service/src/utils/comparison.helper.ts
- services/121-service/test/registrations/pagination/send-message.test.ts
- services/mock-service/src/twilio/twilio.dto.ts
- services/mock-service/src/twilio/twilio.service.ts
[AB#38126](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38126)
Add a utility to use when dealing with response/status-codes coming from (insufficiently typed) third-parties.
So the logic is easier to read AND it prevents 'false negatives';
In which case a "don't throw an error for this code" was incorrectly handled and still causing a lot of (unecessary) log-lines.
> fix: Make checks around (error-)status/response-codes easier to read, less error-prone = less (unnecessary) noise in the logs

- services/121-service/src/registration/registrations.controller.spec.ts
- services/121-service/src/registration/registrations.controller.ts
- services/121-service/src/registration/services/registrations-bulk.service.spec.ts
- services/121-service/src/registration/services/registrations-bulk.service.ts
[AB#38201](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38201) 
This PR refactors the bulk registration status update and message update. 
- Instead of gathering all the registration data of the start of the function data is gathered per use case (1) get data to check which registrations are applicable for the data change (2) get data to status change (3) get data to send messages
- Send bulk message endpoint and registration status change code use to same underlying function
- Rename functions to make it more clearer
- Preparation to allow to call registration status change from a different place without the initial check if registrations are applicable
> Refactor registration bulk service

- k6/run-all-tests.sh
- services/121-service/src/payments/services/payments-execution.service.ts
- services/121-service/src/payments/services/transaction-jobs-creation.service.ts
- services/121-service/src/registration/services/registrations-bulk.service.ts
[AB#38219](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38219) 
- Fixed an issue related to query size when doing a payment with 60k + registrations
- Solution: filtering on referenceId in a querybuilder instead of using the pagination filter functionality
- Enable related k6 test
> Fix query size eror on very large payments and enable related k6 test

- interfaces/portal/src/app/components/import-file-dialog/import-file-dialog.component.ts
- interfaces/portal/src/app/components/page-layout-registration/components/add-note-dialog/add-note-dialog.component.ts
- interfaces/portal/src/app/components/page-layout-registration/components/ignore-duplicates-dialog/ignore-duplication-dialog.component.ts
- interfaces/portal/src/app/components/project-form-budget/project-form-budget.component.html
- interfaces/portal/src/app/components/project-form-budget/project-form-budget.component.ts
- interfaces/portal/src/app/components/project-form-information/project-form-information.component.html
- interfaces/portal/src/app/components/project-form-information/project-form-information.component.ts
- interfaces/portal/src/app/components/project-form-name/project-form-name.component.html
- interfaces/portal/src/app/components/project-form-name/project-form-name.component.ts
- interfaces/portal/src/app/domains/project/project.helper.ts
- interfaces/portal/src/app/pages/project-monitoring-files/components/monitoring-upload-file-dialog/monitoring-upload-file-dialog.component.ts
- interfaces/portal/src/app/pages/project-monitoring-files/project-monitoring-files.page.ts
- interfaces/portal/src/app/pages/project-registration-personal-information/components/edit-personal-information/edit-personal-information.component.ts
- interfaces/portal/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.ts
- interfaces/portal/src/app/pages/project-registrations/components/update-registrations/update-registrations.component.ts
- interfaces/portal/src/app/pages/project-settings-information/components/project-settings-basic-information/project-settings-basic-information.component.html
- interfaces/portal/src/app/pages/project-settings-information/components/project-settings-basic-information/project-settings-basic-information.component.ts
- interfaces/portal/src/app/pages/project-settings-information/components/project-settings-budget/project-settings-budget.component.html
- interfaces/portal/src/app/pages/project-settings-information/components/project-settings-budget/project-settings-budget.component.ts
- interfaces/portal/src/app/pages/project-settings-team/components/add-project-team-user-dialog/add-project-team-user-dialog.component.ts
- interfaces/portal/src/app/pages/projects-overview/components/create-project-dialog/create-project-dialog.component.ts
- interfaces/portal/src/app/pages/users/components/add-user-dialog/add-user-dialog.component.ts
- interfaces/portal/src/app/utils/form-validation.ts
- interfaces/portal/src/locale/messages.xlf
[AB#38218](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38218)
I'm pulling these forms out into separate components so they can eventually be re-used in the create project wizard.
I've separated these changes from the rest of the wizard because
- they can be merged in isolation without waiting for the wizard to be completed
- I think it might make this a bit easier to review without the "noise" of the wizard
- I want approval / review on this new pattern from multiple people - if this is approved, then it's "safe" to use in the wizard without further discussion
Some things that are new / I have doubts / I would like feedback on
- naming/placement of the new `project-form` components
- clarity of the new paradigm of extracting a formGroup from a …
> chore: refactor project forms

- interfaces/portal/src/app/services/log.service.ts
So we can correlate it with requests to the API
[AB#37849](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/37849)
See: https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-map?tabs=javascript#set-cloud-role-name
https://happy-rock-0411d2003-7311.westeurope.3.azurestaticapps.net
> feat: Add "Cloud Role name" to all telemetry of the Portal

- interfaces/portal/eslint-rules/no-form-control-undefined-value.js
- interfaces/portal/eslint.config.mjs
- interfaces/portal/src/app/components/project-form-budget/project-form-budget.component.ts
- interfaces/portal/src/app/components/project-form-information/project-form-information.component.ts
- interfaces/portal/src/app/components/project-form-name/project-form-name.component.ts
- interfaces/portal/src/app/pages/project-payments/components/export-payments/export-payments.component.ts
- interfaces/portal/src/app/pages/project-registrations/components/change-status-contents-with-custom-message/change-status-contents-with-custom-message.component.ts
- interfaces/portal/src/app/pages/project-registrations/components/export-registrations/export-registrations.component.ts
- interfaces/portal/src/app/pages/project-registrations/components/send-message-dialog/send-message-dialog.component.ts
[AB#38421](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/38421)
- Add custom ESLint rule 'no-form-control-undefined-value' to prevent passing undefined as the first argument to FormControl constructors
- Move rule to separate file with documentation explaining the Angular issue (https://github.com/angular/angular/issues/40608)
- Update FormControl usage in 8 component files to follow the recommended pattern
https://happy-rock-0411d2003-7364.westeurope.3.azurestaticapps.net
> chore: prevent quirky undefined behaviour in FormControls
